package com.game.constant;

// 做成数据库配置读表示最好的
public enum GameError {
	OK(200, "OK") {
	},
	PARAM_ERROR(10001, "PARAM FORMAT ERROR") {
	},
	INVALID_PARAM(10002, "INVALID PARAM VALUE") {
	},
	MSG_LEN(10003, "MSG LENTH ERROR") {
	},
	DDOS_ERROR(10004, "SEND MSG TOO FAST") {
	},
	PROTOCAL_ERROR(10005, "WRONG ENCODE") {
	},
	SERVER_EXCEPTION(10006, "OCCUR EXCEPTION") {
	},
	CUR_VERSION(10007, "CURRENT VERSION OLD") { // 版本有更新，请退出重进
	},
	SESSION_LOST(10008, "SESSION LOST") { // SESSION失效，请重新登录
	},
	TOKEN_LOST(10009, "TOKEN LOST") { // token丢失，请重新登录
	},
	NO_LORD(10010, "NOT FOUND LORD") {
	},
	SENSITIVE_WORD(10011, "CONTAIN SENSITIVE WORD") {
	},
	INVALID_CHAR(10012, "INVALID CHAR") {
	},

	SAME_NICK(10013, "SAME NICK NAME") {
	},
	ALREADY_CREATE(10014, "ALREADY CREATE ROLE") {
	},
	NO_REPAIR(10015, "NO NEED REPAIR") {
	},
	NO_CONFIG(10016, "NO CONFIG") {
	},
	DATA_EXCEPTION(10017, "PLAYER DATA EXCEPTION") {
	},
	STONE_NOT_ENOUGH(10018, "STONE NOT ENOUGH") {
	},
	NOT_ENOUGH_GOLD(10019, "GOLD NOT ENOUGH") {
	},
	LORD_LV_NOT_ENOUGH(10020, "LORD LEVEL NOT ENOUGH") { // 指挥官等级不足
	},
	COMMAND_LV_NOT_ENOUGH(10021, "COMMAND LEVEL NOT ENOUGH") {
	},
	RESOURCE_NOT_ENOUGH(10022, "RESOURCE NOT ENOUGH") {
	},
	HERO_CAN_NOT_ADVANCE(10023, "HERO CAN NOT ADVANCE") {
	},
	WAR_NOT_EXISTS(10024, "WAR NOT EXISTS") { // 战争不存在
	},
	WAR_IS_OVER(10025, "WAR IS OVER") { // 战争结束了
	},
	BUILD_LEVEL(10026, "BUILD LEVEL NOT ENOUGH") {
	},
	MAX_TANK_QUE(10027, "MAX TANK QUE") {
	},
	NO_EXIST_QUE(10028, "NOT FOUND THIS QUE") {
	},
	NO_PROP(10029, "DON'T HAVA PROP") {
	},
	BOOK_NOT_ENOUGH(10030, "SKILL BOOK NOT ENOUGH") {
	},
	MAX_PROP_QUE(10031, "MAX PROP QUE") {
	},
	SPEED_WAIT_QUE(10032, "CAN'T SPEED WAIT QUE") {
	},
	CANT_REFIT(10033, "THIS CAN'T BE REFIT") {
	},
	DRAWING_NOT_ENOUGH(10034, "DRWAING NOT ENOUGH") {
	},
	HERO_CHIP_NOT_ENOUGH(10035, "HERO CHIP NOT ENOUGH") {
	},
	PROP_NOT_ENOUGH(10036, "PROP NOT ENOUGH") {
	},
	MAX_REFIT_QUE(10037, "MAX REFIT QUE") {
	},
	TANK_COUNT(10038, "TANK COUNT NOT ENOUGHT") {
	},
	NO_EQUIP(10039, "DON'T HAVA THIS EQUIP") {
	},
	MAX_EQUIP_LV(10040, "MAX EQUIP LEVEL") {
	},
	ALRADY_EQUIP(10041, "ALREADY EQUIP") {
	},
	MAX_EQUIP_STORE(10042, "MAX EQUIP STORE") {
	},
	FULL_EQUIP_ON(10043, "FULL EQUIP ON") {
	},
	EQUIP_STORE_LIMIT(10044, "STORE LIMIT") {
	},
	CHIP_NOT_ENOUGH(10045, "PART CHIP NOT ENOUGH") {
	},
	NO_PART(10046, "DON'T HAVA THIS PART") {
	},
	MAX_PART_UP_LV(10047, "MAX PART UP LV") {
	},
	METAL_NOT_ENOUGH(10048, "METAL NOT ENOUGH") {
	},
	MAX_PART_REFIT_LV(10049, "MAX PART REFIT LV") {
	},
	INGREDIENT_NOT_ENOUGH(10050, "INGREDIENT NOT ENOUGH") {
	},
	DRAW_NOT_ENOUGH(10051, "DRAW NOT ENOUGH") {
	},
	FULL_PART_ON(10052, "FULL PART ON") {
	},
	MAX_PART_STORE(10053, "MAX PART STORE") {
	},
	FAME_LEVEL_ERROR(10054, "FAME LEVEL NOT ENOUGH") {
	},
	COMBAT_PASS_BEFORE(10055, "DON'T PASS BEFORE") {
	},
	NO_POWER(10056, "POWER NOT ENOUGH") {
	},
	NO_RANKS(10057, "LORD RANKS NOT ENOUGH") {
	},
	HAD_PASS(10058, "HAD PASS THIS EXTREME EXPLORE") {
	},
	NEED_3STAR(10059, "NEED 3 STAR") {
	},
	VIP_NOT_ENOUGH(10060, "VIP NOT ENOUGH") {
	},
	COMBAT_NOT_OPEN(10061, "COMBAT NOT OPEN") {
	},
	MAX_BUY_COUNT(10062, "MAX BUY COUNT") {
	},
	HERO_CANT_UP(10063, "HERO CANT UP") {
	},
	NO_PASS(10064, "WIPE UNPASS COMBAT") {
	},
	NO_STAR(10065, "COMBAT STAR NOT ENOUGH") {
	},
	HUANGBAO_NOT_ENOUGH(10066, "HUANGBAO NOT ENOUGH") {
	},
	MAX_RANKS(10067, "MAX RANKS") {
	},

	MAX_COMMAND(10068, "MAX COMMAND") {
	},

	FULL_PROSP(10069, "FULL PROSP") {
	},

	ALREADY_FAME(10070, "ALREADY FAME") {
	},

	ALREADY_GET_BOX(10071, "ALREADY GET BOX") {
	},

	ALREADY_RANK_FAME(10072, "ALREADY GET RANK FAME") {
	},

	FRIEND_HAD(10073, "FRIEND HAD") {
	},
	FRIEND_NOT_EXIST(10074, "FRIEND NOT EXIST") {
	},
	BLESS_HAD(10075, "BLESS HAD") {
	},
	NO_BUILDING(10076, "NO BUILDING") {
	},
	ALREADY_MILL(10077, "ALREADY HAD MILL AT POS") {
	},
	MAX_MILL(10078, "EXCESS MILL COUNT LIMIT") {
	},
	PLAYER_NOT_EXIST(10079, "PLAYER NOT EXIST") {
	},
	HERO_NOT_EXISTS(10080, "HERO NOT EXISTS") {
	},
	CITY_NOT_EXISTS(10081, "CITY NOT EXISTS") {
	},
	ARENA_FORM(10082, "NO ARENA FORM") {
	},
	ARENA_CD(10083, "ARENA CD") {
	},
	NOT_HERO(10084, "IT'S NOT HERO") {
	},
	MAX_BUY_ARENA(10085, "MAX BUY ARENA") {
	},
	ARENA_SCORE(10086, "ARENA SCORE NOT ENOUGH") {
	},
	ALREADY_SPEED_BUILD(10087, "ALREADY SPEED BUILD") { // 初级采集已经加速过了
	},
	ALREADY_ARENA_AWARD(10089, "ALREADY GET AWARD") {
	},
	WAR_PERMISSION_ERROR(10090, "NOT KING") {
	},
	PARTY_NOT_EXIST(10091, "PARTY NOT EXIST") {
	},
	CANNOT_ATTEND_COUNTRY(10092, "CANNOT ATTEND COUNTRY") { // 参加国战的等级过低
	},
	AUTHORITY_ERR(10093, "AUTHORITY_ERR") {
	},
	DONATE_NOT_ENOUGH(10094, "DONATE NOT ENOUGH") {
	},
	WEAL_NOT_EXIST(10095, "WEAL NOT EXIST") {
	},
	WEAL_GOT(10096, "WEAL GOT") {
	},
	PARTY_HAD(10097, "PARTY HAD") {
	},
	SAME_PARTY_NAME(10098, "SAME PARTY NAME") {
	},
	PARTY_APPLY_FULL(10099, "PARTY APPLY FULL") {
	},
	FIGHT_NOT_ENOUGH(10100, "FIGHT NOT ENOUGH") {
	},
	PARTY_MEMBER_FULL(10101, "PARTY MEMBER FULL") {
	},
	EMPTY_POS(10102, "EMPTY POS") {
	},
	MAX_ARMY_COUNT(10103, "MAX ARMY COUNT") {
	},
	UP_JOB_FAIL(10104, "UP JOB FAIL") {
	},
	PARTY_COMBAT_EXIST(10105, "PARTY_COMBAT_EXIST") {
	},
	AWARD_HAD_GOT(10106, "AWARD HAD GOT") {
	},
	COMBAT_PASS(10107, "COMBAT PASS") {
	},
	POS_NOT_EMPTY(10108, "POS NOT EMPTY") {
	},
	NO_ARMY(10109, "NO ARMY") {
	},
	IN_MARCH(10110, "IN MARCHING") {
	},
	MAIL_NOT_EXIST(10111, "MAIL NOT EXIST") {
	},
	NOT_IN_MARCH(10112, "NOT IN MARCHING") {
	},
	UN_LOGIN(10113, "UN LOGIN") {
	},
	NO_TASK(10114, "NO TASK") {
	},
	TASK_NO_FINISH(10115, "TASK NO FINISH") {
	},
	HAD_ACCEPT(10116, "HAD ACCEPT") {
	},
	TASK_DAYIY_FULL(10117, "TASK DAYIY FULL") {
	},
	MAX_CHAT_LENTH(10118, "MAX CHAT LENTH") {
	},
	MAX_SCIENCE_QUE(10120, "MAX SCIENCE QUE") {
	},
	TARGET_NOT_ONLINE(10121, "TARGET NOT ONLINE") {
	},
	NO_REPORT(10122, "NO THIS REPORT") {
	},
	LIVE_NO_ENOUGH(10123, "LIVE NO ENOUGH") {
	},
	NOT_SAME_PARTY(10124, "NOT SAME PARTY") {
	},
	IN_WIPE(10125, "IN WIPE") {
	},
	NOT_IN_WIPE(10126, "NOT IN WIPE") {
	},
	LEFT_ONE_MEMBER(10127, "LEFT ONE MEMBER") {
	},
	GIFT_HAD_GOT(10128, "GIFT HAD GOT") {
	},
	COUNT_NOT_ENOUGH(10129, "COUNT NOT ENOUGH") {
	},
	ATTACK_FREE(10130, "CAN'T ATTACK OR SCOUT") {
	},
	HAD_APPLY(10131, "HAD APPLY") {
	},
	PARTY_RECRUIT_CD(10132, "CAN'T RECRUIT IN 30 MINUTE") {
	},
	GIFT_CODE_LENTH(10133, "GIFT CODE LENTH ERROR") {
	},
	GIFT_CODE_FORMAT(10134, "GIFT CODE FORMAT ERROR") {
	},
	ACTIVITY_NOT_FINISH(10135, "ACTIVITY_NOT_FINISH") {
	},
	ACTIVITY_NOT_OPEN(10136, "ACTIVITY_NOT_OPEN") {
	},
	GIFT_CODE_INVALID(10137, "GIFT CODE INVALID") {
	},
	INVALID_POS(10138, "INVALID POS") {
	},
	CHAT_CD(10139, "IN CHAT CD TIME") {
	},
	PART_NOT_ENOUGH(10140, "PART NOT ENOUGH") {
	},
	OL_NOT_ENOUGH(10141, "ONLINE TIME NOT ENOUGH") {
	},
	ACTIVITY_GOT(10142, "ACTIVITY GOT") {
	},
	CHAT_SILENCE(10143, "YOU ARE SILENCE") {
	},
	NO_AUTHORITY(10144, "NOT HAVE AUTHORITY") {
	},
	IN_SAME_PARTY(10145, "IN SAME PARTY") {
	},
	IN_COLLECT(10146, "IN COLLECT") {
	},
	TIME_NOT_ENOUGH(10147, "TIME NOT ENOUGH") {
	},
	PARTY_LV_ERROR(10148, "PARTY LV ERROR") { // 不能超过军团大厅等级
	},
	SCIENCE_LV_ERROR(10149, "PARTY LV ERROR") { // 不能超过军团大厅等级
	},
	ALREADY_REG(10150, "ALREADY REG PARTY WAR") {
	},
	OUT_REG_TIME(10151, "OUT REG TIME") {
	},
	NOT_ON_RANK(10152, "NOT ON RANK") {
	},
	IN_WAR(10153, "IN WAR") {
	},
	IN_PARTY_TIME(10154, "NEED 24 HOURS") {
	},
	MAX_BLESS_LV(10155, "MAX BLESS LV") {
	},
	BOSS_STATE(10156, "NOT IN BOSS STATE") {
	},
	BOSS_END(10157, "BOSS END") {
	},
	BOSS_CD(10158, "BOSS CD") {
	},
	BOSS_FORM(10159, "NO BOSS FORM") {
	},
	WAR_PROCESS(10160, "WAR IN PROCESS") {
	},
	BOSS_NOT_END(10161, "BOSS NOT END") {
	},
	BUY_ONLY_ONCE(10162, "BUY ONLY ONCE") {
	},
	ARENA_ERROR(10163, "ARENA ERROR") {
	},
	STAFFING_NOT_OPEN(10165, "STAFFING NOT OPEN") {
	},
	SENIOR_MINE_DAY(10166, "SENIOR NOT OPEN TODAY") {
	},
	SENIOR_ATTACK_1(10167, "CAN'T OCCUPA") {
	},
	SENIOR_ATTACK_2(10168, "CAN'T ROB") {
	},
	NO_SENIOR_COUNT(10169, "SENIOR COUNT NOT ENOUGH") {
	},
	SENIOR_MINE_NOT_END(10170, "SENIOR MINE NOT END") {
	},
	NOT_ON_SCORE_RANK(10171, "NOT ON SCORE RANK") {
	},
	ALREADY_GET_AWARD(10172, "ALREADY GET AWARD") {
	},
	FUNCTION_NO_OPEN(10173, "FUNCTION_NO_OPEN") {
	},
	SCORE_NOT_ENOUGH(10174, "SCORE_NOT_ENOUGH") {
	},
	TOPUP_NOT_ENOUGH(10175, "TOPUP_NOT_ENOUGH") {
	},
	REFRESH_FAIL(10176, "REFRESH_FAIL") {
	},
	PARTY_NAME_IS_EXIST(10177, "PARTY_NAME_IS_EXIST") { // 军团名已存在
	},
	HERO_STAR_NOT_SAME(10178, "HERO_STAR_NOT_SAME") { // 武将等级不一致
	},
	HERO_STAR_ERROR(10179, "HERO_STAR_ERROR") { // 将星不可超过银
	},
	COUNT_ERROR(10180, "COUNT_ERROR") { // 数量不对
	},
	PART_LOCKED(10181, "PART_LOCKED") { // 配件已锁定
	},
	PRAY_EXIST(10182, "PRAY_EXIST") { // 已祝福
	},
	NO_PRAY(10183, "NO_PRAY") { // 未祝福
	},
	SCIENCE_FIT_SCOPE_IS_NOT_RIGHT(10184, "SCIENCE_FIT_SCOPE_IS_NOT_RIGHT") { // 军工科技装载范围不对
	},
	SCIENCE_FIT_POS_IS_NOT_RIGHT(10185, "SCIENCE_FIT_POS_IS_NOT_RIGHT") { // 装载的位置不存在
	},
	SCIENCE_POS_CAN_NOT_FIT(10186, "SCIENCE_POS_CAN_NOT_FIT") { // 该位置不能装载军工科技
	},
	SCIENCE_Military_NOT_ENOUGH(10187, "SCIENCE_Military_NOT_ENOUGH") { // 军工材料不够
	},
	SCIENCE_RefitTank_UN_ACTIVE(10188, "SCIENCE_RefitTank_UN_ACTIVE") { // 军工改造未激活
	},
	SCIENCE_RefitTank_NO_CONFIG(10189, "SCIENCE_RefitTank_NO_CONFIG") { // 未配置该坦克改造信息
	},
	SCIENCE_MILITARY_NO_CONFIG(10190, "SCIENCE_MILITARY_NO_CONFIG") { // 未配置该军工科技信息
	},
	SCIENCE_THE_POS_UN_LOCK_NO_CONFIG(10191, "SCIENCE_THE_POS_UN_LOCK_NO_CONFIG") { // 该位置没有配置解锁信息
	},
	SCIENCE_UN_LOCK_Material_NOT_ENOUGTH(10192, "SCIENCE_UN_LOCK_Material_NOT_ENOUGTH") { // 解锁军工格子材料不够
	},
	SCIENCE_NO_GRID_NEED_UN_LOCK(10193, "SCIENCE_NO_GRID_NEED_UN_LOCK") { // 没有需要解锁格子
	},
	SCIENCE_UN_BEGIN_CAUSE_LEVEL(10194, "SCIENCE_UN_BEGIN_CAUSE_LEVEL") { // 等级未达到开启军工副本等级条件
	},
	SCIENCE_LOCKED(10195, "SCIENCE_LOCKED") { // 军工科技未解锁
	},
	SCIENCE_LEVEL_MAX_LIMIT(10196, "SCIENCE_LEVEL_MAX_LIMIT") { // 军工科技等级上限
	},
	SCIENCE_NO_INIT(10197, "SCIENCE_NO_INIT") { // 军工科技未初始化
	},
	SCIENCE_LEVE_CAN_NOT_FIT(10198, "SCIENCE_LEVE_CAN_NOT_FIT") { // 军工科技等级为0不可装配
	},
	TARGET_TASK_NOT_DONE(10199, "TARGET_TASK_NOT_DONE") { // 目标任务未完成
	},
	SIEGE_PARTY_REG(10200, "SIEGE_PARTY_REG") { // 丧尸围城已报名
	},
	SIEGE_FORM(10201, "ALREADY SET FORM") {
	},
	SIEGE_NOT_REG(10202, "SIEGE_NOT_REG") { // 军团长未报名
	},
	SIEGE_REG_TIME(10203, "OUT REG TIME") {
	},
	IN_SIEGE(10204, "IN SIEGE") {
	},
	SIEGE_NO_FORM(10205, "ALREADY SET FORM") {
	},
	ALREADY_VIP(10206, "ALREADY BECOME VIP") {
	},
	BECOME_VIP_STATE(10207, "VIP STATE ERROR") {
	},
	BECOME_VIP_TIME(10208, "VIP TIME ERROR") {
	},
	NOT_GET_PORTRAIT(10209, "NOT GET PORTRAIT") {
	},
	PRAY_BEEN(10210, "PRAY_BEEN") {
	},
	PRAY_CD(10211, "PRAY_CD") {
	},
	DEPRATED_1(10212, "ENERGON_POS_ERROR") {
	},
	DEPRATED_2(10213, "ENERGON_NOT_ENOUGH") {
	},
	NO_SCIENCE_GRID(10214, "NO_SCIENCE_GRID") {
	},
	SAME_MILITARY_ATTR_ID(10215, "SAME_MILITARY_ATTR_ID") {
	},
	MILITARY_PRODUCT(10216, "MILITARY_PRODUCT") {
	},
	MILITARY_BEEN_FIT(10217, "MILITARY_BEEN_FIT") {
	},
	PARTY_BUILD_NOT_ENOUGH(10218, "PARTY_BUILD_NOT_ENOUGH") {
	},
	PARTY_LEADER_CALL_BOSS(10219, "PARTY_LEADER_CALL_BOSS") {
	},
	FORT_UN_OPEN(10220, "FORT_UN_OPEN") {
	},
	FORT_BEEN_SET(10221, "FORT_BEEN_SET") {
	},
	FORT_FIGHT(10222, "FORT_FIGHT") {
	},
	NO_FORT_ACCESS(10223, "NO_FORT_ACCESS") {
	},
	NO_FORT_ATTACK(10224, "NO_FORT_ATTACK") {
	},
	NO_FORT_FORM(10225, "NO_FORT_FORM") {
	},
	NEED_FORT_WIN(10226, "NEED_FORT_WIN") {
	},
	NO_TITLE(10227, "NO_TITLE") {
	},
	NEED_PARTY_LEADER(10228, "NEED_PARTY_LEADER") {
	},
	NO_TARGET(10229, "NO_TARGET") {
	},
	TITLE_HAD(10230, "TITLE_HAD") {
	},
	FORT_DEFEND_CD(10231, "FORT_DEFEND_CD") {
	},
	FORT_FIGHT_CD(10232, "FORT_FIGHT_CD") {
	},
	NO_EQUIP_CONFIG(10233, "DON'T HAVA THIS EQUIP CONFIG") {
	},
	MAX_EQUIP_BUY_TIMES(10234, "REACHE MAX EQUIP BUY TIMES") {
	},
	NO_EQUIP_TYPE(10235, "DON'T HAVA THIS EQUIP TYPE") {
	},
	NOT_ENOUGH_EQUIP_SLOT(10236, "DON'T HAVA ENOUGH EQUIP SLOT") {
	},
	NO_HERO_EQUIP(10237, "NO HERO EQUIP") {
	},
	NOT_ENOUGH_WASH_SKILL_TIMES(10238, "NOT ENOUGH WASH SKILL TIMES") {
	},
	NO_EQUIP_SKILL(10239, "NO EQUIP SKILL") {
	},
	ERROR_EMBATTLE_INDEX(10240, "ERROR EMBATTLE INDEX") {
	},
	EMBATTLE_NOT_OPEN(10241, "EMBATTLE NOT OPEN") {
	},
	HERO_ALREADY_EMBATTLE(10242, "HERO ALREADY EMBATTLE") {
	},
	NO_HERO_IN_THIS_INDEX(10243, "NO HERO IN THIS INDEX") {
	},
	NO_THIS_TYPE_SOLDIER(10244, "NO THIS TYPE SOLDIER") {
	},
	REACH_MAX_SOLDIER_LARGER_TIMES(10245, "REACH MAX SOLDIER LARGER TIMES") {
	},
	NO_SOLDIER_CAPACITY_CONFIG(10246, "NO SOLDIER CAPACITY CONFIG") {
	},
	REACH_MAX_SOLDIER_EMPLOYEE_TIME_BUYTIMES(10247, "REACH MAX SOLDIER EMPLOYEE TIME BUYTIMES") {
	},
	NO_SOLDIER_EMPLOYEE_TIME_CONFIG(10248, "NO SOLDIER EMPLOYEE TIME CONFIG") {
	},
	SILVER_COIN_NOT_ENOUGH(10249, "SILVER COIN NOT ENOUGH") {
	},
	NOT_ENOUGH_WASH_HERO_TIMES(10250, "NOT ENOUGH WASH HERO TIMES") {
	},
	WASH_TYPE_ERROR(10251, "WASH TYPE ERROR") {
	},
	TOTAL_RATE_NOT_1000(10252, "TOTAL RATE NOT 1000") {
	},
	WASH_SKILL_PRICE_ERROR(10253, "WASH SKILL PRICE ERROR") {
	},
	WASH_HERO_PRICE_ERROR(10254, "WASH HERO PRICE ERROR") {
	},
	BUY_EQUIP_SLOT_PRICE_ERROR(10255, "BUY EQUIP SLOT PRICE ERROR") {
	},
	CAPACITY_SOLDIER_PRICE_ERROR(10256, "CAPACITY SOLDIER PRICE ERROR") {
	},
	MISSIONID_NOT_EXISTS(10257, "MISSION ID NOT EXISTS.") {
	},
	ERROR_MISSION_TYPE(10258, "ERROR MISSION TYPE") {
	},
	ENERGY_COST_ERROR(10259, "ERROR COST ERROR") {
	},
	ENERGY_NOT_ENOUGH(10260, "ENERGY NOT ENOUGH ") {
	},
	MAPID_NOT_EXISTS(10261, "MAPID NOT EXISTS") {
	},
	MISSION_STATE_WRONG(10262, "MISSION STATE WRONG") {
	},
	RESOURCE_CONFIG_ERROR(10263, "RESOURCE CONFIG ERROR") {
	},
	MISION_IS_LOCK(10264, "MISSION IS LOCK") {
	},
	MISSION_HERO_CONFIG_ERROR(10265, "MISSION HERO CONFIG ERROR") { // 关卡英雄配置错误
	},
	MISSION_STATE_COMPLETE(10266, "MISSION STATE COMPLETE") {
	},
	HERO_NULL(10267, "GAME HERO IS NULL") { // 英雄对象为空
	},
	HERO_ADD_EXP_IS_ZERO(10268, "HERO ADD EXP IS ZERO") { // 游戏经验值<=0
	},
	HERO_LEVEL_HIGHER_THAN_PLAYER(10269, "HERO LEVEL HIGHER THAN PLAYER") { // 英雄等级不能高于玩家等级
	},
	COUNTRY_ERROR(10270, "COUNTRY ERROR") { // 国家错误
	},
	MISSION_RESOURCE_TIME_END(10271, "MISSION RESOURCE TIME END") { // 资源关卡时间结束
	},
	REACH_MAX_BUY_RESOURCE_TIMES(10272, "NOT ENOUGH BUY RESOURCE TIMES") { // 资源关卡购买次数不足
	},
	REACH_MAX_EQUIP_PAPER_BUY_TIMES(10273, "EQUIP PAPER BUY TIMES OVER") { // 装备图纸购买次数不足
	},
	MISSION_HERO_BOUGHT(10274, "MISSION HERO BOUGHT") { // 关卡英雄已经购买
	},
	NICK_NAME_ERROR(10275, "NICK NAME ERROR") { // 昵称错误
	},
	COLLECT_RESOURCE_NO_TIMES(10276, "COLLECT RESOURCE NO TIMES") { // 征收资源次数不足
	},
	BUILDING_IS_EXISTS(10277, "BUILDING NOT EXISTS") { // 建筑已存在
	},
	EMPLOY_INFO_NULL(10278, "EMPLOY INFO NULL") {
	},
	EMPLOYEE_CONFIG_ERROR(10279, "EMPLOYEE CONFIG ERROR") {
	},
	COMMAND_LEVEL_LOW_EMPLOYEE(10280, "COMMAND LEVEL LOW EMPLOYEE") { // 招募的内政官需要的司令部等级不足
	},
	HIRE_SAME_TYPE_OFFICER(10281, "HIRE SAME OFFICER") {
	},
	HIRE_OFFICER_NOT_ENOUGH_IRON(10282, "HIRE OFFICER NOT ENOUGH IRON") {
	},
	HIRE_OFFICER_NOT_ENOUGH_GOLD(10283, "HIRE OFFICER NOT ENOUGH GOLD") {
	},
	ALREADY_HIRE_OFFICER(10284, "ALREADY HIRE OFFICER") { // 已经雇佣了这个内政官
	},
	EQUIP_PAPER_CONFIG_ERROR(10285, "EQUIP PAPER CONFIG ERROR") {
	},
	ERROR_BUILDING_TYPE_CONFIG(10286, "ERROR BUILDING TYPE CONFIG") { // 错误的建筑类型配置
	},
	BUILDING_IS_UPING(10287, "BUILDING IS UPING") { // 建筑正在升级
	},
	NO_MORE_BUILDING_TEAM(10288, "NO MORE BUILDING TEAM") { // 没有多余的建造队
	},
	BUILD_TEAM_PARAM_ERROR(10289, "BUILD TEAM PARAM ERROR") { // 建造队伍参数错误
	},
	COMMAND_LEVEL_PARAM_ERROR(10290, "COMMAND LEVEL PARAM ERROR") { // 司令部等级参数错误
	},
	LORD_LEVEL_PARAM_ERROR(10291, "LORD LEVEL PARAM ERROR") { // 指挥官等级参数错误
	},
	ERROR_MAX_BUILDING_LEVEL(10292, "ERROR MAX COMMAND LEVEL") { // 错误的最大等级
	},
	REACH_MAX_BUILDING_LEVEL(10293, "REACH MAX COMMAND LEVEL") { // 达到最高建筑等级
	},
	BUILDING_CONFIG_LV_ERROR(10294, "BUILDING CONFIG LV ERROR") { // 建筑配置等级错误
	},
	RESOURCE_PARAM_ERROR(10295, "RESOURCE PARAM ERROR") { // 资源参数错误
	},
	RESOURCE_TYPE_ERROR(10296, "RESOURCE TYPE ERROR") { // 资源类型错误
	},
	PLAYER_NOT_REGISTER(10297, "PLAYER NOT REGISTER") { // 玩家没有注册
	},
	CREATE_PLAYER_FAILED(10298, "CREATE PLAYER FAILED") { // 创建玩家失败
	},
	ITEM_NUMBER_ERROR(10299, "ITEM NUMBER ERROR") { // 物品数量错误
	},
	BEYOND_MAX_ITEM_STACKSIZE(10300, "BEYOND MAX ITEM STACKSIZE") { // 超过物品最大堆叠数
	},
	ITEM_NOT_FOUND(10301, "ITEM NOT FOUND") { // 物品没有找到
	},
	ITEM_EFFECT_VALUE_IS_NULL(10302, "ITEM EFFECT VALUE IS NULL") { // 物品没有使用效果
	},
	ITEM_CAN_NOT_USE(10303, "ITEM CAN NOT USE") { // 物品无法使用
	},
	ADD_RESOURCE_PARAM_ERROR(10304, "ADD RESOURCE ACTION ERROR") { // 增加资源配置错误
	},
	PROP_RESOURCE_TYPE_ERROR(10305, "PROP RESOURCE TYPE ERROR") { // 资源类型错误
	},
	NOT_ENOUGH_ITEM(10306, "NOT ENOUGH ITEM") { // 没有足够的物品
	},
	ITEM_COUNT_LESS_ZERO(10307, "ITEM COUNT LESS ZERO") { // 物品数量小于0
	},
	AWARD_RESOURCE_TYPE_ERROR(10308, "AWARD RESOURCE TYPE ERROR") { // 物品数量小于0
	},
	ADD_HERO_EXP_PARAM_ERROR(10309, "ADD HERO EXP PARAM ERROR") { // 增加英雄经验值参数错误
	},
	NO_HERO_ID_FILED(10310, "NO HERO ID FILED") { // 没有HeroId字段
	},
	ADD_HERO_EXP_AWARDTYPE_ERROR(10311, "ADD HERO EXP AWARDTYPE ERROR") { // 增加英雄经验值类型错误
	},
	ADD_HONOR_PARAM_ERROR(10312, "ADD HONOR PARAM ERROR") { // 增加威望参数错误
	},
	ADD_HONOR_AWARDTYPE_ERROR(10313, "ADD HONOR AWARDTYPE ERROR") { // 增加威望类型错误
	},
	HONOR_PROPERTY_TYPE_ERROR(10314, "HONOR PROPERTY TYPE ERROR") { // 荣誉类型错误
	},
	ADD_ENERGY_PARAM_ERROR(10315, "ADD HONOR PARAM ERROR") { // 增加体力值参数错误
	},
	ADD_ENERGY_AWARDTYPE_ERROR(10316, "ADD HONOR AWARDTYPE ERROR") { // 增加体力值类型错误
	},
	ENERGY_PROPERTY_TYPE_ERROR(10317, "HONOR PROPERTY TYPE ERROR") { // 体力值类型错误
	},
	REACH_MAX_ENERGY_USE_TIMES(10318, "REACH MAX ENERGY USE TIMES") { // 达到体力值最大使用次数
	},
	BUY_BUILD_CD_COST_ERROR(10319, "BUY BUILD CD COST ERROR") { // 加速建筑cd消费类型错误
	},
	BUILDQUE_NOT_EXISTS(10320, "BUILDQUE NOT EXISTS") { // 建造队列不存在
	},
	BUILDQUE_NO_TIME(10321, "BUILDQUE NO TIME") { // 建造队列时间不正确
	},
	ITEM_TYPE_ERROR(10322, "ITEM_TYPE_ERROR") { // 道具类型错误
	},
	USE_KILL_BUILD_RECRUIT_CD_ERROR(10323, "USE KILL BUILD RECRUIT CD ERROR") { // 使用秒建造或者招募cd参数个数错误
	},
	KILL_BUILD_RECRUIT_CD_AWARD_TYPE_ERROR(10324, "KILL BUILD RECRUIT CD AWARD TYPE ERROR") { // 使用秒建造或者招募cd游戏类型个数错误
	},
	EFFECTVALUE_SIZE_ERROR(10325, "EFFECTVALUE_SIZE_ERROR") { // 物品效果参数个数错误
	},
	AWARD_PARAM_SIZE_ERROR(10326, "AWARD PARAM SIZE ERROR") { // award类型参数个数错误
	},
	DEPOT_CD(10327, "DEPOT_CD") { // 聚宝盆CD
	},
	DEPOT_GRID_NO_EXIST(10328, "DEPOT_GRID_NO_EXIST") { // 聚宝盆格子不存在
	},
	DEPOT_IS_BUY(10329, "DEPOT_IS_BUY") { // 聚宝盆已经购买
	},
	NOT_ENOUGH_IRON(10330, "NOT_ENOUGH_IRON") { // 铁不足
	},
	DEPOT_GRID_BEEN_OPEN(10331, "DEPOT_GRID_BEEN_OPEN") { // 聚宝盆该格子已经翻开
	},
	RECRUIT_SODIER_COUNT_ERROR(10332, "RECRUIT SODIER COUNT ERROR") {
	},
	NO_FREE_QUEUE_SIZE(10333, "NO FREE QUEUE SIZE") {
	},
	OIL_NOT_ENOUGH(10334, "OIL NOT ENOUGH") {
	},
	SOLDIER_TYPE_ERROR(10335, "SOLDIER TYPE ERROR") {
	},
	SOLDIER_WORKQUE_IS_EMPTY(10336, "SOLDIER WORK QUE IS EMPTY") {
	},
	SOLDIER_WORKQUE_ONLY_ONE(10337, "SOLDIER WORKQUE ONLY ONE") { // 士兵生产队列只有一个即为建造队列
	},
	SOLDIER_WORKQUE_NOT_EXISTS(10338, "SOLDIER WORKQUE NOT EXISTS!") { // 士兵生产队列不存在
	},
	BUY_SOLDIER_WORK_CD_COST_ERROR(10339, "BUY WORK CD COST ERROR") { // 秒士兵募兵类型错误
	},
	WORKQUE_NOT_EXISTS(10340, "WORKQUE NOT EXISTS") { // 生产队列不存在
	},
	SOLDIER_FULL(10341, "SOLDIER FULL") { // 士兵已满
	},
	NO_EXIST_VIP_SHOP(10342, "NO_EXIST_VIP_SHOP") { // 特价商品不存在
	},
	ADD_RANDOM_BOX_PARAM_ERROR(10343, "ADD FIX BOX PARAM ERROR") { // 增加固定箱子参数错误
	},
	NO_EXIST_SHOP(10344, "NO_EXIST_SHOP") { // 商品不存在
	},
	HAD_BUY_VIP_GIFT(10345, "HAD_BUY_VIP_GIFT") { // VIP礼包已购买
	},
	EQUIP_WORKQUE_IS_EXISTS(10346, "EQUIP WORKQUE IS EXISTS") { // 铁匠铺打造队列已经存在
	},
	NO_BLACK_SMITH(10347, "NO BLACK SMITH") { // 没有铁匠官
	},
	BLACK_SMITH_TIME_UP(10348, "BLACK SMITH TIME UP") { // 铁匠官时间结束
	},
	NO_FREE_EQUIP_CD_TIMES(10349, "NO FREE EQUIP CD TIMES") { // 铁匠官装备打造cd已经扣除过了
	},
	EQUIP_WORK_QUE_NOT_OVER(10350, "EQUIP WORK QUE NOT OVER") { // 打造队列cd没有结束
	},
	EQUIP_FULL(10351, "EQUIP FULL") { // 背包已满
	},
	PROP_BUY_ITEM_NOT_EXISTS(10352, "PROP BUY ITEM NOT EXISTS") { // 物品购买并使用的道具不存在
	},
	HERO_FIGHT_NOT_EXISTS(10353, "HERO FIGHT NOT EXISTS") { // 出站的英雄不存在
	},
	HAS_SAME_HERO_ID(10354, "HAS SAME HERO ID") { // 出站的英雄有重复的
	},
	NO_HERO_FIGHT(10355, "NO HERO FIGHT") { // 没有出站的英雄
	},
	STAR_CONDITION_IS_NULL(10356, "STAR CONDITION IS NULL") { // 星级条件为空
	},
	STAR_CONDITION_SIZE_ERROR(10357, "STAR CONDITION SIZE ERROR") { // 星级条件个数错误
	},
	MISSION_CONFIG_NOT_EXISTS(10358, "MISSION CONFIG NOT EXISTS") { // 关卡配置不存在
	},
	MISSION_STAR_ERROR(10359, "MISSION STAR ERROR") { // 关卡星级错误
	},
	NO_VIP_CONFIG(10360, "NO VIP CONFIG") { // 没有vip配置
	},
	NO_BUY_ENERGY_TIMES(10361, "NO BUY ENERGY TIMES") { // 购买体力次数不足
	},
	COST_TYPE_ERROR(10362, "COST TYPE ERROR") { // 消费类型错误
	},
	NO_BUY_ENERGY_TIME_PPRICE_CONFIG(10363, "NO BUY ENERGY TIME PPRICE CONFIG") { // 没有购买体力值价格配置
	},
	RESOURCE_NULL(10364, "RESOURCE_NULL") { // 资源为空
	},
	REACH_MAX_RESOURCE(10395, "RESOURCE NUM ERROR") { // 资源数达到最大
	},
	RESOURCE_NUM_ERROR(10396, "RESOURCE NUM ERROR") { // 资源数量错误
	},
	ITEM_CAN_NOT_SELL(10397, "ITEM CAN NOT SELL") { // 物品无法出售
	},
	NO_LOOT_HERO_ID(10398, "NO LOOT HERO ID") { // 英雄寻访掉落id不存在
	},
	ERROR_CONFIG_LOOT_HERO_TYPE(10399, "ERROR CONFIG LOOT HERO TYPE") { // 错误的配置掉落类型
	},
	LOOT_GOOD_HERO_TIME_UP(10400, "LOOT GOOD HERO TIME UP") { // 抽神将时间结束
	},
	LOOT_GOOD_HERO_PROCESS_LOW(10401, "LOOT GOOD HERO PROCESS LOW") { // 抽神将进度不足
	},
	ADVANCE_HERO_TYPE_ERROR(10402, "ADVANCE HERO CONFIG NULL") { // 武将进阶配置不存在
	},
	HERO_ADVANCE_CONFIG_NULL(10403, "HERO ADVANCE ID NULL") { // 武将进阶配置不存在
	},
	PROP_BUILDING_CONFIG_NOT_EXISTS(10404, "PROP BUILDING CONFIG NOT EXISTS") { // 资源合成建筑配置不存在
	},
	OPEN_BUILDING_IS_NULL(10405, "OPEN BUILDING IS NULL") { // 开放的资源建筑不存在
	},
	ACCOUNT_NOT_CREATED(10406, "ACCOUNT NOT CREATED") { // 账号没有创建
	},
	HERO_CAN_NOT_WASH(10407, "HERO CAN NOT WASH") { // 英雄洗练品质不够
	},
	TECH_TYPE_NOT_EXISTS(10408, "TECH TYPE NOT EXISTS") { // 科技类型不存在
	},
	TECH_NOT_EXISTS(10409, "TECH NOT EXISTS") { // 科技不存在
	},
	TECH_LEVEL_INFO_NOT_EXISTS(10410, "TECH LEVEL INFO NOT EXISTS") { // 科技等级信息不存在
	},
	TECH_REACH_MAX_LEVEL(10411, "TECH REACH MAX LEVEL") { // 科技达到最大等级
	},
	TECH_IS_LEVEL_UPING(10412, "TECH IS LEVEL UPING") { // 科技正在升级
	},
	TECH_CONFIG_ERROR(10413, "TECH CONFIG ERROR") { // 科技配置错误
	},
	REACH_MAX_TECH_PROCESS(10414, "REACH MAX TECH PROCESS") { // 科技达到最大进度
	},
	TECH_LEVEL_PARAM_ERROR(10415, "TECH LEVEL PARAM ERROR") { // 科技等级参数错误
	},
	NOT_ENOUGH_TECH_LEVEL(10416, "NOT ENOUGH TECH LEVEL") { // 科技等级不足
	},
	TECH_RESEARCH_PARAM_ERROR(10417, "TECH RESEARCH PARAM ERROR") { // 科技研发等级参数错误
	},
	TECH_RESEARCH_NOT_ENOUGH(10418, "TECH RESEARCH NOT ENOUGH") { // 科研进度不足
	},
	NO_TECH_IS_LEVEL_UPING(10419, "NO TECH IS LEVEL UPING") { // 没有科技正在升级
	},
	HIRE_SAME_TYPE_RESEACHER(10420, "HIR SAM TYP RESEACHER") { // 招募规则错误
	},
	TECH_ALREADY_SPEED(10421, "TECH ALREADY SPEED") { // 研发进度已经免费加速过了
	},
	RESEARCHER_NOT_EXISTS(10422, "RESEARCHER NOT EXISTS") { // 研究员已经失效
	},
	LIMIT_CONFIG_IS_NULL(10423, "LIMIT CONFIG IS NULL") { // limit表配置为空
	},
	HERO_QUALITY_ERROR(10424, "HERO QUALITY ERROR") { // 英雄品质错误
	},
	HERO_TYPE_ALREADY_EXISTS(10425, "HERO ALREADY HAS") { // 英雄已经存在了
	},
	HERO_ADVANCE_ALREADY_EXISTS(10426, "HERO ADVANCE ALREADY EXISTS") { // 进阶武将已经存在
	},
	BUY_ENERGY_TIME_NOT_ENOUGH(10427, "BUY ENERGY TIME NOT ENOUGH") { // 购买体力次数不足
	},
	GOOD_HERO_PROCESS_LESS(10428, "GOOD HERO PROCESS LESS") { // 神将进度不足100
	},
	TECH_LEVEL_NOT_ENOUGH(10429, "TECH LEVEL NOT ENOUGH") { // 科技等级不足
	},
	PRE_TECH_NOT_OK(10430, "PRE TECH NOT OK") { // 前置科技没有研究完
	},
	ADD_WALL_PROTECTED_PARAM_ERROR(10431, "ADD WALL PROTECTED PARAM ERROR") { // 城防物品参数错误
	},
	TASK_AWARD_CAN_NOT_TAKE(10432, "TASK AWARD CAN NOT TAKE") { // 任务无法领奖
	},
	TASK_PROCESS_NOT_OK(10433, "TASK PROCESS NOT OK") { // 任务进度不足
	},
	NOT_EMBATTLE_HERO(10434, "NOT EMBATTLE HERO") { // 非上阵武将
	},
	NOT_FREE_HERO_ID(10435, "NOT FREE HERO ID") { // 不是免费Id的武将
	},
	WORKSHOP_QUALITY_ERROR(10436, "WORKSHOP QUALITY ERROR") { // 作坊的材料品质不对
	},
	WORKSHOP_PROP_QUALITY_ERROR(10437, "WORKSHOP QUALITY ERROR") { // 作坊的合成所需要的物品的品质不对
	},
	WORKSHOP_QUE_FULL(10438, "WORKSHOP QUE FULL") { // 作坊生产队列满
	},
	BUILDING_NULL(10439, "BUILDING NULL") { // 建造队列为空
	},
	WORK_SHOP_IS_NULL(10440, "WORK SHOP IS NULL") { // 作坊为空
	},
	WORKQUE_INDEX_ERROR(10441, "WORKQUE INDEX ERROR") { // 作坊建造index错误
	},
	WORKSHOP_WORKQUE_EXISTS(10442, "WORKSHOP WORKQUE EXISTS") { // 作坊生产队列存在
	},
	WORKSHOP_AWARD_ERROR(10443, "WORKSHOP AWARD ERROR") { // 作坊生产奖励错误
	},
	NO_BUY_VIP7_GIFTS(10444, "NO_BUY_VIP_GIFTS") { // 没有购买vip7礼包
	},
	NO_WORKSHOP_WORKQUE(10445, "NO WORKSHOP QUE") { // 没有作坊生产队列
	},
	WORKSHOP_WAITQUE_EXISTS(10446, "WORKSHOP WAITQUE EXISTS") { // 等待队列已经存在
	},
	WORKSHOP_TIME_IS_NOT_UP(10447, "WORKSHOP TIME IS NOT UP") { // 等待队列时间没有结束
	},
	WORKSHOP_AWARD_NULL(10448, "WORKSHOP AWARD NULL") { // 等待队列没有奖励
	},
	REACH_MAX_BUY_WORKSHOP_QUE_TIMES(10449, "REACH MAX BUY WORKSHOP QUE TIMES") { // 购买工坊队列达到最大等级
	},
	CONFIG_ERROR(10450, "CONFIG ERROR") { // 配置错误
	},
	KILL_EQUIPID_NOT_FOUND(10451, "KILL EQUIPID NOT FOUND") { // 杀器的Id没有找到
	},
	HAS_KILL_EQUIP(10452, "HAS KILL EQUIP") { // 已经有一件杀器了
	},
	REACH_MAX_EQUIP_CHIPS(10453, "REACH MAX EQUIP CHIPS") { // 达到最大的碎片数了
	},
	KILL_EQUIP_CHIP_NOT_EXISTS(10454, "KILL EQUIP CHIP NOT EXISTS") { // 合成杀器的物品id配置不存在
	},
	KILL_EQUIP_REACH_MAX__LEVEL(10455, "KILL EQUIP REACH MAX LEVEL") { // 国器等级达到最大等级
	},
	FREE_HERO_ALREADY_HAS(10456, "FREE HERO ALREADY HAS") { // 免费英雄已经存在了
	},
	REACH_MAX_COUNTRY_CHIP(10457, "REACH MAX COUNTRY CHIP") { // 国器碎片已满
	},
	PRIMARY_COLLECT_NOT_EXISTS(10458, "PRIMARY COLLECT NOT EXISTS") { // 初级采集资源点不存在
	},
	PRIMARY_COLLECT_NOT_FINISED(10459, "PRIMARY COLLECT NOT FINISHED") { // 初级采集资源点还没完成
	},
	WORKQUE_CAN_NOT_SPEED(10460, "WORKQUE CAN NOT SPEED") { // 初级资源不能进行加速募兵
	},
	WORLD_MONSTER_NOT_FOUND(10461, "WORLD MONSTER NOT FOUND") { // 世界野怪没有找到
	},
	HERO_NOT_EMBATTLE(10462, "HERO NOT EMBATTLE") { // 英雄没有上阵
	},
	HERO_STATE_ERROR(10463, "HERO STATE ERROR") { // 英雄状态错误
	},
	TECH_REACH_MAX_PROCESS(10464, "TECH REACH MAX PROCESS") { // 科技达到最大进度
	},
	NOT_ENOUGH_COUNT(10465, "NOT_ENOUGH_COUNT") {
	},
	MONSTER_LEVEL_TO_HIGH(10466, "MONSTER LEVEL TO HIGH") { // 怪物等级过高
	},
	WORLD_RESOURCE_NOT_FOUND(10467, "WORLD RESOURCE NOT FOUND") { // 世界资源没有找到
	},
	SAME_COUNTRY(10468, "SAME COUNTRY") { // 国家相同
	},
	NOT_SAME_MAP(10469, "NOT SAME MAP") { // 不在一个地图上
	},
	PLAYER_IS_PROTECTED(10470, "PLAYER IS PROTECTED") { // 玩家正在保护中
	},
	NO_SOLDIER_COUNT(10471, "NO SOLDIER COUNT") { // 带兵量不足
	},
	PRIMARY_QUEUE_SIZE_FULL(10472, "PRIMARY QUEUE SIZE FULL") { // 初始队列数已满
	},
	TO_LONG_MARCH(10473, "TO LONG MARCH") { // 行军时间过长
	},
	POS_ERROR(10474, "POS ERROR") { // 位置错误
	},
	SAME_POS(10475, "SAME POS") { // 相同的位置
	},
	NO_MORE_POS_FOR_DEFENDER(10476, "NO MORE POS FOR DEFENDER") { // 没有更多位置可以招募城防军
	},
	WALL_HAS_CD(10477, "WALL HAS CD") { // 城墙有cd时间
	},
	DEFENDER_INDEX_ERROR(10478, "DEFENDER INDEX ERROR") { // 城防军Index错误
	},
	DEFENDER_LEVEL_ENOUGH(10479, "DEFENDER LEVEL ENOUGH") { // 城防军已经升满
	},
	REACH_MAX_DEFENDER(10480, "REACH MAX DEFENDER") { // 达到最大驻防武将数
	},
	WALL_CANNOT_ASSIST(10481, "WALL CANNOT ASSIST") { // 城墙无法进行驻防
	},
	PLAYER_CITY_NOT_FOUND(10482, "PLAYER CITY NOT FOUND") { //
	},
	AWARD_TYPE_ERROR(10483, "AWARD TYPE ERROR") {
	},
	NOT_ENOUGH_HONOR(10484, "NOT ENOUGH HONOR") {
	},
	NOT_FINISH_TASK(10485, "NOT_FINISH_TASK") {
	},
	NOT_ENOUGH_COUNTRY_LV(10486, "NOT_ENOUGH_COUNTRY_LV") {
	},
	HAD_SELL(10487, "HAD_SELL") {
	},
	ERROR_POS(10489, "ERROR POS") { // 坐标错误
	},
	WAR_IS_STARTED(10490, "WAR IS STARTED") { // 战斗开始了
	},
	HERO_STATE_CAN_NOT_ADVANCE(10491, "HERO STATE CAN NOT ADVANCE") { // 出征的武将不能进阶
	},
	NOT_FINISH_GLORY(10492, "NOT_FINISH_GLORY") { // 国家荣誉目标未达到
	},
	NOT_ENOUGH_GOVERN(10493, "NOT_ENOUGH_GOVERN") { // 国家权限不足
	},
	MISSION_NO_MONSTER(10493, "MISSION NO MONSTER") { // 关卡没有配怪物
	},
	ELECTION_IS_OVER(10494, "ELECTION IS OVER") { // 选举已经结束
	},
	NO_CITY(10495, "NO CITY") { // 没有城池
	},
	ELECTION_ALREADY_ATTEND(10496, "ELECTION ALREADY ATTEND") { // 选举参加了
	},
	ELECTION_NOT_SAME_COUNTRY(10497, "ELECTION NOT SAME COUNTRY") { // 选举国籍不同
	},
	CITY_NOT_TAKEN(10498, "CITY NOT TAKEN") { // 城池没有被攻下
	},
	ELECTION_NOT_ATTEND(10499, "ELECTION NOT ATTEND") { // 没有参加选举
	},
	MAP_INFO_NOT_EXISTS(10500, "MAP INFO NOT EXISTS") { // map信息不存在
	},
	GENERAL_FULL(10501, "GENERAL_FULL") { // 将军已满
	},
	NOT_EXIST_MAIL(10502, "NOT_EXIST_MAIL") { // 邮件不存在
	},
	NOT_EXIST_REPORT(10503, "NOT_EXIST_REPORT") { // 播报不存在
	},
	ALREADY_HAVE_CITY_OWNER(10504, "ALREADY HAVE CITY OWNER") { // 已经有了城主了
	},
	IS_ELECTIONING(10505, "IS ELECTIONING") { // 正在选举中
	},
	CAN_NOT_FIX(10506, "CAN NOT FIX") { // 无法修复
	},
	CITY_SOLDIER_FULL(10507, "CITY SOLDIER FULL") { // 城池兵力已满
	},
	WOLRDBOSS_IS_FIGHT(10508, "WOLRDBOSS IS FIGHT") { // 世界boss已打
	},
	NO_SHARE(10509, "NO_SHARE") { // 不能分享
	},
	WORLD_TARGET_STATUS_ERROR(10510, "WORLD TARGET STATUS ERROR") { // 世界目标状态不对
	},
	NO_WORLD_TARGET(10511, "NO WORLD TARGET") { // 没有这个世界目标
	},
	WORLD_AWARD_HAD_TAKEN(10512, "WORLD AWARD HAD TAKEN") { // 世界奖励已经被领取
	},
	CITY_COUNTRY_ERROR(10513, "CITY COUNTRY ERROR") { // 国家错误
	},
	MAP_ID_ERROR(10514, "MAP ID ERROR") {
	}, // 地图错误
	NO_CITY_AWARD_NUM(10515, "NO CITY AWARD NUM") {
	}, // 没有征收次数了
	CITY_TYPE_ERROR(10516, "CITY TYPE ERROR") {
	}, // 城池类型错误
	SCOUT_TYPE_ERRPR(10517, "SCOUT TYPE ERRPR") {
	}, // 侦察类型错误
	NO_SCOUT_TARGET(10518, "NO SCOUT TARGET") {
	}, // 侦察目标不存在
	SCOUT_CONFIG_ERROR(10519, "SCOUT CONFIG ERROR") {
	}, // 侦察配置不存在
	ITEM_ID_NOT_EXISTS(10520, "ITEM_ID_NOT_EXISTS") {
	}, // 物品Id不存在
	CANNOT_MAP_MOVE(10521, "CANNOT_MAP_MOVE") {
	}, // 无法迁城
	POS_IS_TAKEN(10522, "POS_IS_TAKEN") {
	}, // 位置被占用了
	APPOINT_RANK(10524, "APPOINT_RANK") { // 只能任命前30名玩家
	},
	CAN_NOT_ATTEND_WAR(10525, "CAN_NOT_ATTEND_WAR") { // 无法加入战斗
	},
	SPEED_ITEM_ERROR(10526, "SPEED ITEM ERROR") { // 行军令道具Id错误
	},
	NO_MARCH(10527, "NO MARCH") { // 没有行军
	},
	SPEED_MARCH_TYPE_ERROR(10528, "SPEED MARCH TYPE ERROR") {
		/* 加速行军类型错误 */
	},
	MARCH_STATE_ERROR(10529, "MARCH STATE ERROR") {
		/* 行军状态错误 */
	},
	WAR_END_OR_NOT_EXIST(10530, "WAR_END_OR_NOT_EXIST") {
		/* 战斗结束或者不存在 */
	},
	WAR_CANNT_HELP(10531, "WAR_CANNT_HELP") {
		/* 该战争不能请求支援 */
	},
	TARGET_LOST(10532, "TARGET LOST") {
		/* 目标点丢失 */
	},
	NO_WAR_INFO(10533, "NO_WAR_INFO") { // 没有战斗信息
	},
	NO_HERO_MARCH(10534, "NO HERO MARCH") { // 没有部队行军
	},
	TRANSFER_CD(10535, "TRANSFER_CD") { // 召唤CD中
	},
	NOT_ENOUGH_TRANSFER(10536, "NOT_ENOUGH_TRANSFER") { // 召唤次数不足
	},
	NO_TRANSFER(10537, "NO_TRANSFER") { // 没有召唤
	},
	SAME_MAP(10538, "SAME_MAP") { // 同一地图上
	},
	NO_WALL_FRIEND(10539, "NO WALL FRIEND") { // 没有城墙驻防友军
	},
	MARCH_ID_ERROR(10540, "MARCH ID ERROR") { // 行军Id错误
	},
	ALREADY_CALL_COUNTRY_WAR(10541, "ALREADY CALL COUNTRY WAR") { // 已经发起了国战
	},
	NO_MARCH_HEROS(10542, "NO MARCH HEROS") { // 行军没有英雄
	},
	NO_FREE_BUILD_TEAM(10543, "NO FREE BUILD TEAM") { // 没有空闲的建造队
	},
	IS_ALREADY_CITY_OWNER(10544, "IS ALREADY CITY OWNER") { // 已经是城主了
	},
	NO_ATTEND_WAR(10545, "NO_ATTEND_AWAR") { // 没有参战
	},
	BUILD_QUE_FREE_UESD(10546, "BUILD QUE FREE UESD") { // 建造免费已用
	},
	CITY_IS_PROTECTED(10547, "CITYx ISx PROTECTED") { // 城池正在保护中
	},
	HERO_IN_MARCH(10548, "HERO IN MARCH") { // 英雄正在行军之中
	},
	MAP_INFO_IS_NULL(10549, "MAP INFO IS NULL") {
	},
	TECH_IS_RESEARCHING(10550, "TECH IS RESEARCHING") { // 科技正在升级
	},
	NOT_ENOUGH_CALL_BACKTIMES(10551, "NOT ENOUGH CALL BACKTIMES") {
	},
	GRID_ERROR(10552, "GRID ERROR") { // 补给站格子错误
	},
	NO_LEVEL_AWARD(10553, "NO LEVEL AWARD") { // 升级奖励不存在
	},
	CD_EXCHANGE_RES(10554, "CD_EXCHANGE_RES") { // 兑换资源CD
	},
	NOT_OPEN_SOLDIER_AUTO(10555, "NOT OPEN SOLDIER AUTO") { // 自动补兵科技没有开启
	},
	HERO_LEVEL_NOT_ENOUGH(10556, "HERO LEVEL NOT ENOUGH") { // 英雄等级不足
	},
	HERO_QUALITY_NOT_ENOUGH(10557, "HERO QUALITY NOT ENOUGH") { // 英雄品质不足
	},
	HERO_EQUIPNUM_NOT_ENOUGH(10558, "HERO EQUIPNUM NOT ENOUGH") { // 英雄装备数目不足
	},
	HERO_EQUIP_ERRPR(10559, "HERO EQUIP ERRPR") { // 英雄装备错误
	},
	HERO_EQUIP_QUALITY_ERRPR(10560, "HERO EQUIP QUALITY ERRPR") { // 英雄装备品质不是红色
	},
	NOT_ENOUGH_SKILL_NUM(10561, "NOT ENOUGH SKILL NUM") { // 技能不足
	},
	SKILL_LEVEL_LOW(10562, "SKILL LEVEL LOW") { // 技能等级不足
	},
	SKILL_TYPE_ERROR(10563, "SKILL TYPE ERROR") { // 技能类型错误
	},
	ALREADY_SPECIAL_HERO(10564, "ALREADY SPECIAL HERO") { // 已经进行升级突破了
	},
	CAN_NOT_CALL_WAR(10565, "CAN NOT CALL WAR") { // 无法宣战
	},
	ALREADY_HAS_CITY(10566, "ALREADY HAS CITY") { // 已经有一个都城了
	},
	DONOT_CROSS_MAP_DEV_CITY(10567, "DONOT CROSS MAP DEV CITY") { // 不能跨区域开发城池
	},
	CITY_REACH_MAX_LEVEL(10568, "CITY REACH MAX LEVEL") { // 城池达到最大等级
	},
	BLACK(10569, "BLACK") { // 已被拉黑
	},
	SQUARE_HAS_CITY(10570, "SQUARE_HAS_CITY") { // 四方要塞已经有国家了
	},
	REACH_MAX_FAMOUS_NUM(10571, "REACH_MAX_FAMOUS_NUM") { // 已经有7个名城了
	},
	MAP_NOT_OPEN(10572, "MAP NOT OPEN") { // 地图未开放[暂时关闭世界地图野怪]
	},
	NO_RESOURCE_ENTITY(10573, "NO RESOURCE ENTITY") { // 没有资源点
	},
	HERO_ALREADY_COLLECTED(10574, "HERO ALREADY COLLECTED") { // 英雄已经正在采集中
	},
	CANT_BUY(10575, "CANT_BUY") { // 已经买满无法继续购买
	},
	WALL_LEVEL_NOT_ENOUGH(10578, "WALL LEVEL NOT ENOUGH") { // 城墙等级不足
	},
	CAN_NOT_COLLECT_PAPER(10579, "CAN NOT COLLECT PAPER") {
	},
	CAN_NOT_ATTACK_PLAYER(10580, "CAN NOT ATTACK PLAYER") { // 不能跨区域打玩家
	},
	SOLDIER_IS_TRAINING(10581, "SOLDIER IS TRAINING") { // 士兵正在训练
	},
	CAN_NOT_COMPOSE(10582, "CAN NOT COMPOSE") { // 无法合成
	},
	COUNTRY_DATA_NOT_EXISTS(10583, "COUNTRY DATA NOT EXISTS") { // 国家数据不存在
	},
	NOT_ENOUGH_COPPER(10584, "NOT_ENOUGH_COPPER") { // 铜不足
	},
	NOT_ENOUGH_OIL(10585, "NOT_ENOUGH_OIL") { // 石油不足
	},
	REACH_MAX_COUNTRY_LEVEL(10586, "REACH MAX COUNTRY LEVEL") { // 达到国家最大等级
	},
	REACH_MAX_TITLE(10587, "REACH MAX TITLE") { // 达到最高爵位等级
	},
	TASK_NOT_FOUND(10588, "TASK_NOT_FOUND") { // 任务未找到
	},
	COUNTRY_GLORY_NOT_EXISTS(10589, "COUNTRY_GLORY_NOT_EXISTS") { // 国家排行榜不存在
	},
	ALREADY_EMPLOYEE(10590, "ALREADY_EMPLOYEE") { // 已经招募了
	},
	REACH_MAX_BUILD_COUNTRY(10591, "REACH_MAX_BUILD_COUNTRY") { // 已经达到国家建设上限
	},
	VIP_EXP_ITEM_PARAM_ERROR(10592, "VIP_EXP_ITEM_PARAM_ERROR") { // vip道具参数错误
	},
	CITY_NO_OWNER(10592, "CITY NO OWNER") { // 城池没有城主
	},
	CITY_HAS_OWNER(10593, "CITY HAS OWNER") { // 城池有城主
	},
	SOLDIER_IS_BUILDING(10594, "SOLDIER IS BUILDING") { // 兵营正在建造
	},
	GET_ONE_KILL_EQUIP_CHIP(10595, "GET ONE KILL EQUIP CHIP") { // 至少获得一个杀器碎片
	},
	BUILD_TEAM_NOT_OPEN(10596, "BUILD TEAM NOT OPEN") { // 建造队没有开启
	},
	WORK_SHOP_LV_ERROR(10597, "WORK_SHOP_LV_ERROR") { // 作坊等级错误
	},
	WORK_SHOP_CAN_NOT_UP(10598, "work Shop Can Not Up") { // 生产的时候不能升级建筑
	},
	WORK_SHOP_CAN_NOT_MAKE(10599, "work Shop Can Not Make") { // 升级建筑的时候不能生产
	},
	REACH_MAX_KILL_DIMO_TIMES(10600, "REACH_MAX_KILL_DIMO_TIMES") { // 已达到击杀警卫的最大次数
	},
	AUTO_SOLDIER_NOT_OPEN(10601, "AUTO_SOLDIER_NOT_OPEN") { // 自动补兵没有开启
	},
	QUICK_WAR_CAN_NOT_ATTEND(10602, "QUICK WAR CAN NOT ATTEND") { // 闪电战无法参战
	},
	RAND_POS_ERR(10603, "RAND_POS_ERR") { // 随机坐标失败
	},
	REACH_MAX_KILL_REBEL_TIMES(10604, "REACH_MAX_KILL_REBEL_TIMES") { // 已达到击杀叛军的最大次数
	},
	HERO_IS_EMPTY(10605, "HERO_IS_EMPTY") { // 英雄为空
	},
	MASS_SAME_HERO(10606, "MASS_SAME_HERO") { // 集结了相同的英雄
	},
	HERO_IS_IN_PVP_BATTLE(10607, "HERO_IS_IN_PVP_BATTLE") { // 英雄在PVP战斗中
	},
	MASS_TO_MANY_HERO(10608, "MASS_TO_MANY_HERO") { // 集结太多将领了
	},
	HERO_IN_MASS(10609, "HERO IN MASS") { // 英雄正在集结之中
	},
	HERO_NOT_IN_MASS(10610, "HERO NOT IN MASS") { // 英雄不在集结列表
	},
	PLACE_AND_COUNTRY_NOT_SAME(10611, "PLACE_AND_COUNTRY_NOT_SAME") { // 位置和国家不一致
	},
	PLACEID_IS_WRONG(10612, "PLACEID_IS_WRONG") { // 位置Id错误
	},
	SAME_HERO_GO_ACTION(10613, "SAME_HERO_GO_ACTION") { // 前往相同Id英雄
	},
	PVP_BATTLE_HAS_ATTACKER(10614, "PVP_BATTLE_HAS_ATTACKER") { // 参战方兵力不为0
	},
	PVP_BATTLE_STARTED(10615, "PVP BATTLE STARTED") { // 血战开始了
	},
	PVP_BATTLE_CAN_NOT_ACTION(10616, "PVP_BATTLE_CAN_NOT_ACTION") { // 血战无法操作
	},
	PVP_BATTLE_IS_NULL(10617, "PVP_BATTLE_IS_NULL") { // pvp战斗为空
	},
	PVP_HERO_IS_NULL(10618, "PVP HERO IS NULL") { // pvp英雄是空的
	},
	CAN_NOT_GO_TO_SAME_PLACE(10619, "CAN_NOT_GO_TO_SAME_PLACE") { // 不能前往到相同的区域
	},
	NOT_IN_PVP_BATTLE_STATE(10620, "NOT_IN_PVP_BATTLE_STATE") { // 不在战斗状态
	},
	HERO_IS_ALIVE(10621, "HERO IS ALIVE") { // 英雄还存活
	},
	SOLDIER_NOT_ENOUGH(10622, "SOLDIER_NOT_ENOUGH") { // 兵营兵力不足
	},
	ATTACK_TEAM_NO_HEROES(10623, "ATTACK_TEAM_NO_HEROES") { // 对方没有兵力
	},
	DIG_STATE_ERROR(10624, "DIG_STATE_ERROR") { // 还有宝物没有挖
	},
	REACH_MAX_WORD_TIMES(10625, "REACH_MAX_BUY_TIMES") { // 达到最大套话次数
	},
	NOT_ENOUGH_PVP_SCORE(10626, "NOT_ENOUGH_PVP_SCORE") { // 血战积分不足
	},
	IS_ALREADY_DIGED_PAPER(10627, "IS_ALREADY_DIGED_PAPER") { // 已经挖到红色图纸了
	},
	BANQUET_OVER(10628, "BANQUET_OVER") { // 国宴结束
	},
	PVP_IS_GREETED_PAPER(10629, "PVP_IS_GREETED_PAPER") { // pvp已经恭贺
	},
	WORLD_PVP_STATE_ERROR(10630, "WORLD_PVP_STATE_ERROR") { // 开战状态错误
	},
	NOT_YOUR_COUNTRY_AREA(10631, "NOT_YOUR_COUNTRY_AREA") { // 通过血战占领了世界要塞的国家指挥官可出击
	},
	COUNTRY_HERO_NULL(10632, "COUNTRY_HERO_NULL") { // 国家英雄为空
	},
	COUNTRY_HERO_STATE_ERROR(10633, "COUNTRY_HERO_STATE_ERROR") { // 国家名将状态错误
	},
	HERO_IS_ACTIVATE(10634, "HERO_IS_ACTIVATE") { // 名将已经激活
	},
	NO_PROP_ID(10635, "NO_PROP_ID") { // 国家名将喂养道具Id错误
	},
	REACH_MAX_LOYALTY(10636, "REACH_MAX_LOYALTY") { // 达到最大忠诚度
	},
	HERO_IS_NOT_ACTIVATE(10637, "HERO_IS_NOT_ACTIVATE") { // 名将未激活
	},
	HERO_IN_PVP_BATTLE(10638, "HERO_IN_PVP_BATTLE") { // 英雄在皇城血战中
	},
	MAIL_FULL(10639, "MAIL_FULL") { // 私聊邮件已满
	},
	CAMP_IS_ALREADY_BUILD(10640, "CAMP_IS_ALREADY_BUILD") { // 战备工厂已经建造
	},
	CAN_NOT_DESTROY(10641, "CAN_NOT_DESTROY") { // 建筑无法拆除
	},
	CAMP_IS_NOT_BUILD(10642, "CAMP_IS_NOT_BUILD") { // 战备工厂没有建造
	},
	USE_TO_MUCH_ENERGY(10643, "USE_TO_MUCH_ENERGY") { // 使用太多体力丹
	},
	STAFF_TASK_STATE_ERROR(10644, "STAFF_TASK_STATE_ERROR") { // 参谋部任务状态不正确
	},
	STAFF_TASK_ID_IS_NOT_INVALID(10645, "STAFF_TASK_ID_IS_NOT_INVALID") { // 参谋部任务Id不合法
	},
	PRE_STAFF_TASK_NOT_ACTIVATED(10646, "PRE_STAFF_TASK_NOT_ACTIVATED") { // 前置任务没有激活
	},
	STAFF_TASK_NOT_EXISTS(10647, "STAFF_TASK_NOT_EXISTS") { // 参谋部任务不存在!
	},
	STAFF_ACTIVATE_COND_ERROR(10648, "STAFF_ACTIVATE_COND_ERROR") { // 点兵符数量不足或者等级不足
	},
	PVP_SOLO_STATE_ERROR(10649, "PVP SOLO STATE ERROR") { // 不满足单挑条件
	},
	HAS_ALL_HEROES(10650, "HAS_ALL_HEROES") { // 当前副本拥有所有的英雄
	},
	SUGGEST_COUNT(10651, "SUGGEST_COUNT") { // 超出服务器当日建议上限,或者当日2次数建议已用完
	},
	PRIMARY_COLLECT_FINISED(10652, "PRIMARY_COLLECT_FINISED") { // 初级采集点已经完成过了
	},
	STAR_NUM_ERROR(10653, "STAR_NUM_ERROR") { // 星级数量错误
	},
	STAR_STATE_ERROR(10654, "STAR_STATE_ERROR") { // 领取星级奖励错误
	},
	HAS_NO_BUILDING_ID(10655, "HAS_NO_BUILDING_ID") { // 客户端没有发送BuildingId
	},
	REMOVE_BUILDING_ERROR(10656, "REMOVE_BUILDING_ERROR") { // 删除建筑错误
	},
	BUILING_IS_BUILDED(10657, "BUILING_IS_BUILDED") { // 资源建筑已经建造
	},
	RIOT_NOT_SAME_MAP(10658, "RIOT_NOT_SAME_MAP") { // 不在一个地图上
	},
	NEW_STATE_IS_DONE(10659, "NEW_STATE_IS_DONE") { // 新手引导已经完成
	},
	EXCHANGE_EQUIP_DONE(10660, "EXCHANGE_EQUIP_DONE") { // 兑换装备
	},
	PORTRAITS_NOT_OPEN(10661, "PORTRAITS_NOT_OPEN") { // 头像没有开启
	},
	CAN_NOT_BUILD(10662, "CAN_NOT_BUILD") { // 无法建造
	},
	LOOT_NUM_ERROR(10663, "LOOT_NUM_ERROR") { // 抽奖次数错误
	},
	CITY_WAR_LEVEL_NOT_ENOUGH(10664, "CITY_WAR_LEVEL_NOT_ENOUGH") { // 城战不足30级
	},
	DO_SOME(19999, "DO_SOME") { // 特殊标记
	},
	HERO_MINING_EMBATTLE(10665, "HERO ALREADY EMBATTLE") { // 采集武将已经上阵
	},
	ERROR_MINING_INDEX(10666, "ERROR MINING INDEX") { // index参数不正确
	},
	EMBATTLE_MINING_OPEN(10667, "ERROR MINING OPEN") { // 采集部队槽位未开启
	},

	STAFF_LEVEL_NOT_ENOUGH(10668, "ERROR MINING OPEN") { // 参谋部等级不足
	},
	MEETING_TASK_STATE_ERROR(10669, "ERROR MEETINF  STATE  ERROR") { // 参谋部等级不足
	},

	MEETING_TASK_PROCESS_ERROR(10670, "ERROR MEETINF  TASK   PROCESS") { // 指挥学任务进度不足
	},

	DEFENSE_SOLDIER_NOT_EXIST(10671, "ERROR DEFENSE SOLDIER NOT EXIST") { // 城防部英雄不存在
	},

	WORLD_TARGET_TASK_NOT_EXIST(10672, "WORLD TARGET TASK  NOT EXIST") { // 世界目标任务不存在
	},

	TARGET_AWARD_IS_AWARD(10673, "TARGET AWARD IS AWARD") { // 任务奖励已经领取
	},

	TARGET_NOT_SUCCESS(10674, "TARGET NOT SUCCESS") { // 任务目标未达成
	},

	WORLD_BOSS_IS_DIE(10675, "WORLD BOSS IS DIE") { // 世界boss已经死亡
	},

	ATTACK_WORLD_BOSS_TIME_NOT_ENOUGH(10676, "WORLD BOSS TIME NOT ENOUGH") { // 挑战世界boss次数不够
	},

	RES_NOT_ENOUGH(10677, "RES NOT ENOUGH") { // 资源不足
	},

	STAFF_NOT_OPEN(10678, "STAFF NOT OPEN") { // 参谋部尚未开启
	},

	SWEEP_HERO_INFO_ERROR(10679, "SWEEP HERO INFO ERROR") { // 扫荡武将信息错误
	},

	PLAYER_IS_NOT_KING(10680, "PLAYER IS NOT KING") { // 该玩家不是总统
	},

	MODIFY_NAME_IS_CHECKING(10681, "MODIFY NAME IS CHECKING") { // 有国家改名在审核中
	},

	REBUILD_ID_ERROR(10682, "REBUILD ID ERROR") { // 重建的id错误
	},

	REBEL_MONSTER_ERROR(10683, "REBEL MONSTER ERROR") { // 叛军不存在或者叛军已经被宣战
	},

	REBEL_ACTIVITY_ERROR(10684, "REBEL ACTIVITY ERROR") { // 伏击叛军活动没有开启
	},

	REBEL_SCORE_NOT_ENOUGH(10685, "REBEL SCORE NOT ENOUGH") { // 伏击叛军积分不够
	},

	REBEL_EXCHANGE_NUM_NOT_ENOUGH(10686, "REBEL EXCHANGE NUM NOT ENOUGH") { // 伏击叛军兑换次数不够
	},

	PAY_CREATE_ORDERNUM_ERROR(10690, "PAY CREATE ORDERNUM ERROR") { // 创建订单失败
	},

	ALREADY_CALL_REBEL_WAR(10691, "ALREADY CALL REBEL WAR") { // 已经发起了伏击叛军
	},

	ACTIVITY_MONTHCARD_OFF_ERROR(10692, "PAY CREATE ORDERNUM ERROR") { // 月卡已经过期
	},

	ACTIVITY_MONTHCARD_AWARD_ERROR(10693, "PAY CREATE ORDERNUM ERROR") { // 当天奖励已经领取
	},

	WORLD_TARGET_NOT_OPEN(10694, "WORLD TARGET NOT OPEN") { // 世界进程没有开启
	},

	CDK_IS_ERROR(10695, "CDK IS  ERROR") { // cdk 不合法
	},

	MAX_ONLINE_NUM(10696, "MAX ONLINE NUM") { // 服务器已达最大在线人数
	},

	MAX_REGISTER_NUM(10697, "MAX REGISTER NUM") { // 服务器已达最大注册人数
	},

	BEAUTY_SGAME_COUNT_ERROR(10698, "BEAUTY_SGAME_COUNT_ERROR") { // 购买小游戏次数超过vip等级限制次数
	},
	BEAUTY_SGAME_PRICE_ERROR(10699, "BEAUTY_SGAME_PRICE_ERROR") { // 购买小游戏次数价格异常
	},
	BEAUTY_NO_HAVE_ERROR(10700, "BEAUTY_NO_HAVE_ERROR") { // 玩家未拥有当前美女
	},

	BEAUTY_SEEKING_TIMES_ERROR(10701, "BEAUTY_SEEKING_TIMES_ERROR") { // 玩家美女约会次数超过拥有次数
	},
	BEAUTY_GIFT_COUNT_ERROR(10702, "BEAUTY_GIFT_COUNT_ERROR") { // 玩家送礼物品不足
	},
	ADD_ADDBUILDTEAMTIME_PARAM_ERROR(10703, "ADD_ADDBUILDTEAMTIME_PARAM_ERROR") { // 增加建造队时间参数错误
	},

	WORLD_ENTITY_NOT_EXIST(10704, "WORLD ENTITY NOT EXIST") { // 世界实体不存在
	},

	BUILD_IS_RECOVERED(10705, "BUILD IS RECOVERED") { // 建筑已经被收复
	},

	BEAUTY_SEEKING_COUNT_ERROR(10706, "BEAUTY_SEEKING_COUNT_ERROR") { // 购买约会次数超过vip等级限制次数
	},

	BEAUTY_SEEKING_PRICE_ERROR(10707, "BEAUTY_SEEKING_PRICE_ERROR") { // 购买约会次数价格异常
	},

	COLLECT_NUN_MAX(10708, "COLLECT NUN MAX") { // 同时采集的 超过四个了
	},

	CITY_FIGHTHELP_NUN_MAX(10709, "CITY_FIGHTHELP_NUN_MAX") { // 超过城战的最大支援次数
	},

	ALREADY_FRIEND(10710, "ALREADY_FRIEND") { // 已是好友
	},

	PLAYER_FIREND_NUM_MAX(10711, "PLAYER_FIREND_NUM_MAX") { // 自己好友数量已到达上限
	},

	TARGET_FIREND_NUM_MAX(10712, "TARGET_FIREND_NUM_MAX") { // 对方好友数量已到达上限
	},

	APPRENTICE_NUM_NOT_ENOUGH(10713, "APPRENTICE NUM NOT ENOUGH") { // 徒弟个数不够(领奖时)
	},

	NOT_IN_FRIEND_LIST(10714, "NOT_IN_FRIEND_LIST") { // 还不是好友
	},

	NOT_IN_APPLY_LIST(10715, "NOT_IN_APPLY_LIST") { // 不在申请列表
	},

	OMAMENT_COUNT_MORE_ZERO(10716, "NOT_IN_APPLY_LIST") { // 配饰数量大于0
	},

	OMAMENT_NOT_FOUND(10717, "OMAMENT_NOT_FOUND") { // 玩家没有此配饰
	},

	NOT_ENOUGH_OMAMENT(10718, "NOT_ENOUGH_OMAMENT") { // 配饰数量不足
	},

	POS_NOT_OPEN(10719, "POS_NOT_OPEN") { // 配饰数量不足
	},

	POS_WEAR_TYPE_ERROR(10720, "POS_WEAR_TYPE_ERROR") { // 配饰槽位穿戴类型错误
	},

	POS_WEAR_SAME_ERROR(10721, "POS_WEAR_SAME_ERROR") { // 槽位已经穿戴此配饰
	},

	POS_NOT_HAVE_OMAMENT(10722, "POS_NOT_HAVE_OMAMENT") { // 槽位未穿戴此配饰
	},

	TARGET_LORD_LV_NOT_ENOUGH(10723, "TARGET LORD LEVEL NOT ENOUGH") { // 对方等级不够
	},

	ALREADY_HAVE_MASTER(10724, "ALREADY HAVE MASTER") { // 已有师父
	},

	TARGET_APPRENTICE_NUM_MAX(10725, "TARGET APPRENTICE NUM MAX") { // 对方徒弟数量已到达上限
	},

	NOT_ENOUGH_FRIEND_SHOP_SCORE(10726, "NOT ENOUGH FRIEND SHOP SCORE") { // 师徒商店积分不足
	},

	FRIEND_SHOP_EXCHANGE_NUM_NOT_ENOUGH(10727, "FRIEND SHOP EXCHANGE NUM NOT ENOUGH") { // 师徒商店兑换次数不足
	},

	NOT_SAME_COUNTRY(10728, "NOT_SAME_COUNTRY") { // 不同阵营不能拜师
	},

	APPRENTICE_LV_NOT_ENOUGH(10729, "APPRENTICE_LV_NOT_ENOUGH") { // 玩家超过拜师等级
	},

	ALREADY_APPRENTICE(10730, "ALREADY_APPRENTICE") { // 不能加徒弟为好友
	},

	ALREADY_MASTER(10731, "ALREADY_MASTER") { // 不能加师父为好友
	},

	JOURNEY_CONFIG_NOT_EXISTS(10732, "JOURNEY_CONFIG_NOT_EXISTS") { // 远征关卡配置不存在
	},

	JOURNEY_STATE_WRONG(10733, "JOURNEY_STATE_WRONG") { // 远征关卡状态错误
	},

	ERROR_JOURNEY_TYPE(10734, "ERROR_JOURNEY_TYPE") { // 远征关卡类型错误
	},

	JOURNEY_COST_ERROR(10735, "JOURNEY_COST_ERROR") { // 远征关卡次数不足
	},

	JOURNEY_BUY_COUNT_ERROR(10736, "JOURNEY_BUY_COUNT_ERROR") { // 远征关卡购买次数到达上限
	},

	JOURNEY_PRICE_ERROR(10737, "JOURNEY_PRICE_ERROR") { // 远征关卡购买价格错误
	},

	JOURNEY_NO_MONSTER(10738, "JOURNEY_NO_MONSTER") { // 远征关卡无野怪配置
	},
	IS_SELF(10739, "IS_SELF") { // 不能加自己
	},
	SUMMIT_OMAMENT(10740, "SUMMIT_OMAMENT") { // 配饰已是顶级无法在升级
	},
	MARCH_OVER_TIME(10741, "MARCH_OVER_TIME") { // 行军时间大于活动结束时间
	},
	TOWER_NON_EXISTENT(10742, "TOWER IS NOT EXISTENT"), // 关卡不存在
	TOWER_NON_REWARD(10743, "TOWER IS NOT REWARD"), // 奖励不存在
	TOWER_NOT_OPEN(10744, "TOWER IS NOT OPEN"), // 关卡未开启
	BEAUTY_EXP_DEFICIENCY(10745, "BEAUTY_EXP_DEFICIENCY") { // 秘书经验不足
	},
	ALREADY_FAIL(10746, "ALREADY_FAIL") { // 该英雄已战败，无法进行此操作
	},
	RIOT_ITEM_NOT_ENOUGH(10747, "item not enough"),//虫族暴乱道具不足
	RIOT_SCORE_NOT_ENOUGH(10748, "score not enough"), // 虫族暴乱积分不足
	GIFT_BUY_COUNT_ENOUGH(10749, "GIFT_BUY_COUNT_ENOUGH") { // 礼包购买次数不足
	},
	STEAL_CITY_IS_AWARD(10750, "STEAL_CITY_IS_AWARD") { // 名城奖励已经领取过
	},
	STEAL_CITY_IS_OVER(10751, "STEAL_CITY_IS_OVER") { // 名城已经恢复正常生产
	},
	STEAL_CITY_IS_NOT_GOVERN(10752, "STEAL_CITY_IS_NOT_GOVERN") { // 非阵营官员不能宣战
	},
	NO_WAR_BOOK(10753, "NO_WAR_BOOK") { // 兵书不存在
	},
	NO_WAR_BOOK_CONFIG(10754, "NO_WAR_BOOK_CONFIG") { // 兵书配置不存在
	},
	VERSION_LOW(10755, "VERSION IS LOW"), // 客户端版本过低
	WAR_BOOK_LOCK(10756, "WAR_BOOK_LOCK"), // 兵书已经锁住
	WORLD_BOX_COIN_NOT_ENOUGH(10757, "WORLD_BOX_COIN_NOT_ENOUGH"), // 宝箱积分不足
	WORLD_BOX_NOT_OPEN(10758, "WORLD_BOX_NOT_OPEN"), // 宝箱还未开启
	WORLD_BOX_IN_OPEN(10759, "WORLD_BOX_IN_OPEN"), // 宝箱开启中，无需前置
	WORLD_BOX_TO_MORE(10760, "WORLD_BOX_TO_MORE"), // 超过宝箱每日可开启上线
	WAR_BOOK_LEVLE_ENOUGH(10761, "WAR_BOOK_LOCK"), // 兵书等级已满
	PASS_PORT_PRO_NOT_BUY(10762, "PASS_PORT_PRO_NO_BUY"), // 通行证进阶版未购买
	PASS_PORT_LV_ERROR(10763, "PASS_PORT_LV_ERROR"), // 通行证购买等级错误
	SIGNATURE_IS_NULL(10764, "SIGNATURE_IS_NULL"), // 个性签名输入为空
	SIGNATURE_MORE_THAN_30_WORDS(10765, "SIGNATURE_MORE_THAN_30_WORDS"), // 个性签名最多只能输入30个字
	SIGNATURE_SAME_AS_THE_OLD_ONE(10766, "SIGNATURE_SAME_AS_THE_OLD_ONE"), // 指挥官,您未做任何修改
	CANT_MOVE(10768, "CANT_MOVE"), // 不满75级 不让飞母巢
	SKIN_LEV_EXISTS(10767, "SKIN_LEV_EXISTS"), // 主城皮肤等级不存在
	NOT_ENOUGH_LUCK_POOL_TIMES(10769, "NOT_ENOUGH_LUCK_POOL_TIMES"), // 幸运奖池抽奖次数不够
	LACK_OF_COMBAT_POWER(10770, "LACK_OF_COMBAT_POWER"), // 指挥官战力不足
	SKIN_NOT_EXISTS(10771, "SKIN_NOT_EXISTS"), // 主城皮肤不存在
	BEAUTY_UPLV_ERROR(10772, "BEAUTY_LV_ERROR"), // 秘书升星错误
	NOT_JEWELLERY_TIEM(10773, "NOT_JEWELLERY_TIEM"), // 珠宝数量不够
	BEAUTY_SKILL_LV_MAX(10774, "BEAUTY_SKILL_LV_MAX"), // 秘书星级已达到最大
	NOT_ENOUGH_GAMES(10775, "NOT_ENOUGH_GAMES"), // 剩余玫瑰不足,您可以等待至明日,每日的玫瑰都会自动补满
	BEAUTY_NOT_UNLOCKED(10776, "BEAUTY_NOT_UNLOCKED"), // 秘书未解锁
	BEAUTY_UNLOCKED(10777, "BEAUTY_UNLOCKED"), // 秘书已解锁
	BEAUTY_CLICK_TIMES_NOT_ENOUGH(10778, "BEAUTY_CLICK_TIMES_NOT_ENOUGH"), // 秘书点击获取奖励次数不够
	// 自动杀虫特权过期
	AUTO_KILL_EXPIRE(10779, "AUTO KIll EXPIRE"), AUTO_SOLDIER_FULL(10780, "AUTO SOLDIER_FULL"), BEAUTY_INTIMACY_IS_FULL(10781, "BEAUTY_INTIMACY_IS_FULL"), // 秘书亲密度已满
	REQUEST_LIMIT(10782, "REQUEST_LIMIT"), // 30秒内仅可发一次，玩家30秒内连续点击时，提示：30秒仅可请求一次
	LEVEL_LIMIT(10783, "LEVEL_LIMIT"), // 35级之后可参与进攻
	LESS_THAN_15_DAYS_OFFLINE(10784, "LESS_THAN_15_DAYS_OFFLINE"), // 离线时间不足十五天
	HERO_ALREADY_DEFENSE_ARMY(10785, "HERO_ALREADY_DEFENSE_ARMY"), // 英雄已经在城防
	CAN_NOT_BUY_NOW(10786, "CAN NOT BUY NOW"), // 现在不能购买
	CAN_NOT_BUY_ENOUGH(10787, "CAN NOT BUY NOW"), // 购买次数不足
	HERO_IN_REVIVE(10788, "CAN NOT BUY NOW"), // 英雄恢复中
	MARCH_RETURNED(10789, "MARCH_RETURNED"), // 英雄正在撤回
	MARCH_ERR(10790, "MARCH_ERR"), APPLY_MASTER_REPEAT(10791, "APPLY_MASTER_REPEAT"), // 拜师请求已送达
	MASTER_AND_APPRENTICE_REPEAT(10792, "MASTER_AND_APPRENTICE_REPEAT"), // 已经是师徒关系
	ZERG_SCORE_NOT_ENOUGH(10794, "ZERG_SCORE_NOT_ENOUGH"), // 虫族主宰积分不足
	ZERG_EXCHANGE_NOT_ENOUGH(10795, "ZERG_EXCHANGE_NOT_ENOUGH"), // 兑换次数达到上限
	MARCH_FIGHTING(10796, "MARCH_FIGHTING"), // 战斗中，无法操作
	NOT_ON_THE_LIST(10797, "NOT_ON_THE_LIST"), // 未上榜
	REMAINING_TIMES_NOT_ENOUGH(10798, "REMAINING_TIMES_NOT_ENOUGH"), // 剩余挑战次数不够
	NO_CHALLENGES_THIS_WEEK(10799, "NO_CHALLENGES_THIS_WEEK"), // 本周还未挑战
	DUPLICATE_TYPE_CANNOT_BE_SELECTED(10800, "DUPLICATE_TYPE_CANNOT_BE_SELECTED"), // 不能重复选择同类型的道具
	TD_MONEY_NOT_ENOUGH(10801, "TD_MONEY_NOT_ENOUGH"), // 塔防币不够
	DIFFERENT_COUNTRIES(10802, "DIFFERENT_COUNTRIES"), // 非本阵营指挥官不可切磋
	TARGET_HERO_IS_EMPTY(10803, "TARGET_HERO_IS_EMPTY"), // 对方未上阵英雄
	WIN_COUNT_NOT_ENOUGH(10804, "WIN_COUNT_NOT_ENOUGH"), //连胜次数不够
	NO_MANOEUVRE(10805, "NO_MANOEUVRE"), //沙盘演武活动未开启
	NO_MANOEUVRE_APPLY(10806, "NO_MANOEUVRE_APPLY"), //活动非报名阶段
	NOT_COUNTRY_MASTER(10807, "NOT_COUNTRY_MASTER"), //只有总统才key调换分路
	MANOEUVRE_PARAM_ERROR(10808, "MANOEUVRE_PARAM_ERROR"), //参数错误
	MANOEUVRE_BEEN_APPLY(10809, "MANOEUVRE_BEEN_APPLY"), //沙盘演武已报名
	MANOEUVRE_NOT_ENOUGH_SCORE(10810, "MANOEUVRE_NOT_ENOUGH_SCORE"), //沙盘演武积分不足
	COMMAND_LV_NOT_ENOUGH_12(10811, "COMMAND_LV_NOT_ENOUGH_12"), //指挥部不足12级
	MANOEUVRE_NEED_APPLY(10812, "MANOEUVRE_NEED_APPLY"), //调换路线需要报名
	MANOEUVRE_NEED_PARE(10813, "MANOEUVRE_NEED_PARE"), //只有准备阶段可以调换路线
	FISHING_DATA_ERROR(10814, "FISHING_DATA_ERROR"), // 玩家钓鱼数据不存在
	FISHING_TEAM_STATUS_ERROR(10815, "FISHING_TEAM_STATUS_ERROR"), // 采集鱼饵队列状态有误
	FISHING_TEAM_TIME_ERROR(10816, "FISHING_TEAM_TIME_ERROR"), // 未到达领取时间
	FISHING_RECORD_NOT_EXIST(10817, "FISHING_RECORD_NOT_EXIST"), // 钓鱼记录不存在
	FISHING_ATLAS_AWARD_ALREADY_GET(10819, "FISHING_ATLAS_AWARD_ALREADY_GET"), // 已经领取过该奖励
	FISHING_POINTS_EXCHANGE_NOT_EXIST(10820, "FISHING_POINTS_EXCHANGE_NOT_EXIST"), // 该商品不存在
	FISHING_POINTS_EXCHANGE_NOT_ENOUGH(10821, "FISHING_POINTS_EXCHANGE_NOT_ENOUGH"), // 积分不足
	FISHING_POINTS_EXCHANGE_LIMIT(10822, "FISHING_POINTS_EXCHANGE_LIMIT"), // 超过每日兑换次数
	FISHING_TEAM_MEMBER_ERROR(10823, "FISHING_TEAM_MEMBER_ERROR"), // 队伍成员不足
	FISHING_SHARE_COUNT_LIMIT(10824, "FISHING_SHARE_COUNT_LIMIT"), // 超过分享次数限制
	FISHING_BAIT_NOT_ENOUGH(10825, "FISHING_BAIT_NOT_ENOUGH"), // 鱼饵不足

	FIRE_OUT(10826, "FIRE OUT TIME"),
	FIRE_NOT_MOVE_SAFE(10827, "FIRE NOT MOVE SAFE"),
	FIRE_NOT_ATT_SAFE(10828, "FIRE NOT ATT SAFE"),
	FIRE_MAX(10829, "FIRE MAX"),//人数达到上限
	FRI_APPLY_LOW_TIME(10830, "FRI_APPLY_LOW_TIME"), // 解除师徒关系后再次拜师冷却时间
	REMARK_ERROR(10831, "REMARK_ERROR"), // 标记权限不够
	CMD_NO_REGISTER(10832, "COMMAND_NO_EXIST"), //消息不存在
	DAILY_TASK_COMPLETE(10833, "DAILY_TASK_COMPLETE"), //日常任务已完成
	DAILY_TASK_TIME(10834, "DAILY_TASK_TIME"), //日常任务次数不对

	;

	public int getCode() {
		return code;
	}

	public void setCode(int code) {
		this.code = code;
	}

	public String getMsg() {
		return msg;
	}

	public void setMsg(String msg) {
		this.msg = msg;
	}

	private GameError(int code, String msg) {
		this.code = code;
		this.msg = msg;
	}

	private int code;
	private String msg;

	public String toString() {
		return msg + ", code = " + code;
	}
}