package com.game.constant;

public interface MarchReason {
	int FarPlayerFly = 1; // 远征被击飞
	int HighMove = 2; // 高级迁城
	int MiddleMove = 3; // 中级迁城
	int LowMove = 4; // 低级迁城
	int Reply = 5; // 召唤
	int QuickPlayerFly = 6; // 闪电战被击飞
	int MarchCancelByItem = 7; // 道具取消行军
	int MarchCancelFree = 8; // 撤回行军
	int MarchCityAssist = 9; // 友军驻防
	int PlayerOpenProtect = 10; // 闪电战玩家处于保护时间
	int KillRebelWin = 11; // 击杀完流寇成功
	int KillRebelFailed = 12; // 击杀完流寇失败
	int CollectWarWin = 13; // 采集遭遇战成功后返回
    int CollectWarFailed = 14; // 采集遭遇战失败后返回
    int CollectDone = 15; // 采集完成
    int QuickAttackWin = 16; // 闪电战成功
    int QuickAttackFailed = 17; // 闪电战失败
    int LostTarget = 18; // 目标点丢失
    int WallFriendKick = 19; // 解散城防军
    int CountryAttender = 20; // 参加国战
    int FarProtectedTime = 21; // 远征或者奔袭战玩家处于保护时间
    int CtWarProtectedTime = 22; // 国家城池开启保护罩
    int FarWarWin = 23; // 远征或奔袭成功
    int FarWarFailed = 24; // 远征或奔袭失败
    int CtWarWin = 25; // 国战成功
    int CtWarFailed = 26; // 国战失败
    int MarchCancelByGold = 27; // 使用金币取消行军, 且取消相关的战斗行军
    int WallAssistCancelMarch = 28; // 自己主动友军驻防撤回部队
    int WallAssistCancelOthersMarch = 29; // 踢出友军驻防部队
    int MarchCancelVip = 30; // vip免费召回
    int MarchCancelCollect= 31; // 撤回采集行军
    int CountryWarReturn = 32; // 国战返回
    int QuickAttack = 33;   // 闪电战
    int FarAttack = 34;  // 远征或者奔袭
    int KillRebel = 35; // 击杀流寇
    int AttendCountryWar = 36; // 参加国战
    int AttendPvpWar = 37;  // 参加城战
    int JoinInCountryWar = 38; // 加入国战
    int MarchTicker = 39;  // 行军定时器设置
    int UseProtectItem = 40; // 开启城池保护
    int PlayerFlyOrMove = 41; // 玩家被击飞或者迁城
    int NO_WAR = 42; // 没有战斗
    int QUICK_WAR_FINISH = 43; // 闪电战结束
    int RIOT_WAR_ATTEND = 44;  // 参加暴乱战斗
    int KILL_REBEL_MONSTER_SUCCESS = 45;  // 伏击叛军成功
    int KILL_REBEL_MONSTER_FAIL = 46;  // 伏击叛军失败
    int ACTIVITY_REBEL_IS_OVER = 47;  // 伏击叛军活动结束
    int ATTEND_REBEL_WAR = 48;  // 参加伏击叛军
    int REBEL_MONSTER_MISS = 49;  // 伏击叛军目标点丢失
    int CANCEL_REBEL_BACK = 50;  // 取消伏击叛军
    int TopMiddleMove = 56; // 顶级迁城
    int CANCEL_BIGMONSTER_BACK = 57;    //撤回巨型虫族
    int CANCEL_SUPERRES_BACK = 58;    //撤回大型资源
	int AttendZergWar = 59; // 参加虫族主宰
	int DEFEND_ZERG_WAR = 60; // 虫族主宰进攻玩家
}
