// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Banhao.proto

package com.game.pb;

public final class Banhao {
  private Banhao() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.game.pb.Banhao.GetBanhaoTimesRq.ext);
    registry.add(com.game.pb.Banhao.GetBanhaoTimesRs.ext);
  }
  public interface GetBanhaoTimesRqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code GetBanhaoTimesRq}
   */
  public static final class GetBanhaoTimesRq extends
      com.google.protobuf.GeneratedMessage
      implements GetBanhaoTimesRqOrBuilder {
    // Use GetBanhaoTimesRq.newBuilder() to construct.
    private GetBanhaoTimesRq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GetBanhaoTimesRq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GetBanhaoTimesRq defaultInstance;
    public static GetBanhaoTimesRq getDefaultInstance() {
      return defaultInstance;
    }

    public GetBanhaoTimesRq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GetBanhaoTimesRq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.pb.Banhao.internal_static_GetBanhaoTimesRq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.pb.Banhao.internal_static_GetBanhaoTimesRq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.pb.Banhao.GetBanhaoTimesRq.class, com.game.pb.Banhao.GetBanhaoTimesRq.Builder.class);
    }

    public static com.google.protobuf.Parser<GetBanhaoTimesRq> PARSER =
        new com.google.protobuf.AbstractParser<GetBanhaoTimesRq>() {
      public GetBanhaoTimesRq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetBanhaoTimesRq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GetBanhaoTimesRq> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.game.pb.Banhao.GetBanhaoTimesRq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.pb.Banhao.GetBanhaoTimesRq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.pb.Banhao.GetBanhaoTimesRq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.pb.Banhao.GetBanhaoTimesRq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.pb.Banhao.GetBanhaoTimesRq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.pb.Banhao.GetBanhaoTimesRq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.game.pb.Banhao.GetBanhaoTimesRq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.game.pb.Banhao.GetBanhaoTimesRq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.game.pb.Banhao.GetBanhaoTimesRq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.pb.Banhao.GetBanhaoTimesRq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.pb.Banhao.GetBanhaoTimesRq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetBanhaoTimesRq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game.pb.Banhao.GetBanhaoTimesRqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.pb.Banhao.internal_static_GetBanhaoTimesRq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.pb.Banhao.internal_static_GetBanhaoTimesRq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.pb.Banhao.GetBanhaoTimesRq.class, com.game.pb.Banhao.GetBanhaoTimesRq.Builder.class);
      }

      // Construct using com.game.pb.Banhao.GetBanhaoTimesRq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.pb.Banhao.internal_static_GetBanhaoTimesRq_descriptor;
      }

      public com.game.pb.Banhao.GetBanhaoTimesRq getDefaultInstanceForType() {
        return com.game.pb.Banhao.GetBanhaoTimesRq.getDefaultInstance();
      }

      public com.game.pb.Banhao.GetBanhaoTimesRq build() {
        com.game.pb.Banhao.GetBanhaoTimesRq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.pb.Banhao.GetBanhaoTimesRq buildPartial() {
        com.game.pb.Banhao.GetBanhaoTimesRq result = new com.game.pb.Banhao.GetBanhaoTimesRq(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.pb.Banhao.GetBanhaoTimesRq) {
          return mergeFrom((com.game.pb.Banhao.GetBanhaoTimesRq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.pb.Banhao.GetBanhaoTimesRq other) {
        if (other == com.game.pb.Banhao.GetBanhaoTimesRq.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.pb.Banhao.GetBanhaoTimesRq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.pb.Banhao.GetBanhaoTimesRq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:GetBanhaoTimesRq)
    }

    static {
      defaultInstance = new GetBanhaoTimesRq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:GetBanhaoTimesRq)
    public static final int EXT_FIELD_NUMBER = 31201;
    /**
     * <code>extend .Base { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.game.pb.BasePb.Base,
        com.game.pb.Banhao.GetBanhaoTimesRq> ext = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.game.pb.Banhao.GetBanhaoTimesRq.getDefaultInstance(),
          0,
          com.game.pb.Banhao.GetBanhaoTimesRq.class,
          com.game.pb.Banhao.GetBanhaoTimesRq.getDefaultInstance());
  }

  public interface GetBanhaoTimesRsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 lootCommonTimes = 1;
    /**
     * <code>optional int32 lootCommonTimes = 1;</code>
     */
    boolean hasLootCommonTimes();
    /**
     * <code>optional int32 lootCommonTimes = 1;</code>
     */
    int getLootCommonTimes();

    // optional int32 lootGoodTimes = 2;
    /**
     * <code>optional int32 lootGoodTimes = 2;</code>
     */
    boolean hasLootGoodTimes();
    /**
     * <code>optional int32 lootGoodTimes = 2;</code>
     */
    int getLootGoodTimes();

    // optional int32 washHeroTimes = 3;
    /**
     * <code>optional int32 washHeroTimes = 3;</code>
     */
    boolean hasWashHeroTimes();
    /**
     * <code>optional int32 washHeroTimes = 3;</code>
     */
    int getWashHeroTimes();

    // optional int32 washEquipTimes = 4;
    /**
     * <code>optional int32 washEquipTimes = 4;</code>
     */
    boolean hasWashEquipTimes();
    /**
     * <code>optional int32 washEquipTimes = 4;</code>
     */
    int getWashEquipTimes();
  }
  /**
   * Protobuf type {@code GetBanhaoTimesRs}
   */
  public static final class GetBanhaoTimesRs extends
      com.google.protobuf.GeneratedMessage
      implements GetBanhaoTimesRsOrBuilder {
    // Use GetBanhaoTimesRs.newBuilder() to construct.
    private GetBanhaoTimesRs(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GetBanhaoTimesRs(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GetBanhaoTimesRs defaultInstance;
    public static GetBanhaoTimesRs getDefaultInstance() {
      return defaultInstance;
    }

    public GetBanhaoTimesRs getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GetBanhaoTimesRs(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              lootCommonTimes_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              lootGoodTimes_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              washHeroTimes_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              washEquipTimes_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.pb.Banhao.internal_static_GetBanhaoTimesRs_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.pb.Banhao.internal_static_GetBanhaoTimesRs_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.pb.Banhao.GetBanhaoTimesRs.class, com.game.pb.Banhao.GetBanhaoTimesRs.Builder.class);
    }

    public static com.google.protobuf.Parser<GetBanhaoTimesRs> PARSER =
        new com.google.protobuf.AbstractParser<GetBanhaoTimesRs>() {
      public GetBanhaoTimesRs parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetBanhaoTimesRs(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GetBanhaoTimesRs> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 lootCommonTimes = 1;
    public static final int LOOTCOMMONTIMES_FIELD_NUMBER = 1;
    private int lootCommonTimes_;
    /**
     * <code>optional int32 lootCommonTimes = 1;</code>
     */
    public boolean hasLootCommonTimes() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 lootCommonTimes = 1;</code>
     */
    public int getLootCommonTimes() {
      return lootCommonTimes_;
    }

    // optional int32 lootGoodTimes = 2;
    public static final int LOOTGOODTIMES_FIELD_NUMBER = 2;
    private int lootGoodTimes_;
    /**
     * <code>optional int32 lootGoodTimes = 2;</code>
     */
    public boolean hasLootGoodTimes() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 lootGoodTimes = 2;</code>
     */
    public int getLootGoodTimes() {
      return lootGoodTimes_;
    }

    // optional int32 washHeroTimes = 3;
    public static final int WASHHEROTIMES_FIELD_NUMBER = 3;
    private int washHeroTimes_;
    /**
     * <code>optional int32 washHeroTimes = 3;</code>
     */
    public boolean hasWashHeroTimes() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 washHeroTimes = 3;</code>
     */
    public int getWashHeroTimes() {
      return washHeroTimes_;
    }

    // optional int32 washEquipTimes = 4;
    public static final int WASHEQUIPTIMES_FIELD_NUMBER = 4;
    private int washEquipTimes_;
    /**
     * <code>optional int32 washEquipTimes = 4;</code>
     */
    public boolean hasWashEquipTimes() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 washEquipTimes = 4;</code>
     */
    public int getWashEquipTimes() {
      return washEquipTimes_;
    }

    private void initFields() {
      lootCommonTimes_ = 0;
      lootGoodTimes_ = 0;
      washHeroTimes_ = 0;
      washEquipTimes_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, lootCommonTimes_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, lootGoodTimes_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, washHeroTimes_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, washEquipTimes_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, lootCommonTimes_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, lootGoodTimes_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, washHeroTimes_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, washEquipTimes_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.game.pb.Banhao.GetBanhaoTimesRs parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.pb.Banhao.GetBanhaoTimesRs parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.pb.Banhao.GetBanhaoTimesRs parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.pb.Banhao.GetBanhaoTimesRs parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.pb.Banhao.GetBanhaoTimesRs parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.pb.Banhao.GetBanhaoTimesRs parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.game.pb.Banhao.GetBanhaoTimesRs parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.game.pb.Banhao.GetBanhaoTimesRs parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.game.pb.Banhao.GetBanhaoTimesRs parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.pb.Banhao.GetBanhaoTimesRs parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.pb.Banhao.GetBanhaoTimesRs prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetBanhaoTimesRs}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game.pb.Banhao.GetBanhaoTimesRsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.pb.Banhao.internal_static_GetBanhaoTimesRs_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.pb.Banhao.internal_static_GetBanhaoTimesRs_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.pb.Banhao.GetBanhaoTimesRs.class, com.game.pb.Banhao.GetBanhaoTimesRs.Builder.class);
      }

      // Construct using com.game.pb.Banhao.GetBanhaoTimesRs.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        lootCommonTimes_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        lootGoodTimes_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        washHeroTimes_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        washEquipTimes_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.pb.Banhao.internal_static_GetBanhaoTimesRs_descriptor;
      }

      public com.game.pb.Banhao.GetBanhaoTimesRs getDefaultInstanceForType() {
        return com.game.pb.Banhao.GetBanhaoTimesRs.getDefaultInstance();
      }

      public com.game.pb.Banhao.GetBanhaoTimesRs build() {
        com.game.pb.Banhao.GetBanhaoTimesRs result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.pb.Banhao.GetBanhaoTimesRs buildPartial() {
        com.game.pb.Banhao.GetBanhaoTimesRs result = new com.game.pb.Banhao.GetBanhaoTimesRs(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.lootCommonTimes_ = lootCommonTimes_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.lootGoodTimes_ = lootGoodTimes_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.washHeroTimes_ = washHeroTimes_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.washEquipTimes_ = washEquipTimes_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.pb.Banhao.GetBanhaoTimesRs) {
          return mergeFrom((com.game.pb.Banhao.GetBanhaoTimesRs)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.pb.Banhao.GetBanhaoTimesRs other) {
        if (other == com.game.pb.Banhao.GetBanhaoTimesRs.getDefaultInstance()) return this;
        if (other.hasLootCommonTimes()) {
          setLootCommonTimes(other.getLootCommonTimes());
        }
        if (other.hasLootGoodTimes()) {
          setLootGoodTimes(other.getLootGoodTimes());
        }
        if (other.hasWashHeroTimes()) {
          setWashHeroTimes(other.getWashHeroTimes());
        }
        if (other.hasWashEquipTimes()) {
          setWashEquipTimes(other.getWashEquipTimes());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.pb.Banhao.GetBanhaoTimesRs parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.pb.Banhao.GetBanhaoTimesRs) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 lootCommonTimes = 1;
      private int lootCommonTimes_ ;
      /**
       * <code>optional int32 lootCommonTimes = 1;</code>
       */
      public boolean hasLootCommonTimes() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 lootCommonTimes = 1;</code>
       */
      public int getLootCommonTimes() {
        return lootCommonTimes_;
      }
      /**
       * <code>optional int32 lootCommonTimes = 1;</code>
       */
      public Builder setLootCommonTimes(int value) {
        bitField0_ |= 0x00000001;
        lootCommonTimes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 lootCommonTimes = 1;</code>
       */
      public Builder clearLootCommonTimes() {
        bitField0_ = (bitField0_ & ~0x00000001);
        lootCommonTimes_ = 0;
        onChanged();
        return this;
      }

      // optional int32 lootGoodTimes = 2;
      private int lootGoodTimes_ ;
      /**
       * <code>optional int32 lootGoodTimes = 2;</code>
       */
      public boolean hasLootGoodTimes() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 lootGoodTimes = 2;</code>
       */
      public int getLootGoodTimes() {
        return lootGoodTimes_;
      }
      /**
       * <code>optional int32 lootGoodTimes = 2;</code>
       */
      public Builder setLootGoodTimes(int value) {
        bitField0_ |= 0x00000002;
        lootGoodTimes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 lootGoodTimes = 2;</code>
       */
      public Builder clearLootGoodTimes() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lootGoodTimes_ = 0;
        onChanged();
        return this;
      }

      // optional int32 washHeroTimes = 3;
      private int washHeroTimes_ ;
      /**
       * <code>optional int32 washHeroTimes = 3;</code>
       */
      public boolean hasWashHeroTimes() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 washHeroTimes = 3;</code>
       */
      public int getWashHeroTimes() {
        return washHeroTimes_;
      }
      /**
       * <code>optional int32 washHeroTimes = 3;</code>
       */
      public Builder setWashHeroTimes(int value) {
        bitField0_ |= 0x00000004;
        washHeroTimes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 washHeroTimes = 3;</code>
       */
      public Builder clearWashHeroTimes() {
        bitField0_ = (bitField0_ & ~0x00000004);
        washHeroTimes_ = 0;
        onChanged();
        return this;
      }

      // optional int32 washEquipTimes = 4;
      private int washEquipTimes_ ;
      /**
       * <code>optional int32 washEquipTimes = 4;</code>
       */
      public boolean hasWashEquipTimes() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 washEquipTimes = 4;</code>
       */
      public int getWashEquipTimes() {
        return washEquipTimes_;
      }
      /**
       * <code>optional int32 washEquipTimes = 4;</code>
       */
      public Builder setWashEquipTimes(int value) {
        bitField0_ |= 0x00000008;
        washEquipTimes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 washEquipTimes = 4;</code>
       */
      public Builder clearWashEquipTimes() {
        bitField0_ = (bitField0_ & ~0x00000008);
        washEquipTimes_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:GetBanhaoTimesRs)
    }

    static {
      defaultInstance = new GetBanhaoTimesRs(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:GetBanhaoTimesRs)
    public static final int EXT_FIELD_NUMBER = 31202;
    /**
     * <code>extend .Base { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.game.pb.BasePb.Base,
        com.game.pb.Banhao.GetBanhaoTimesRs> ext = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.game.pb.Banhao.GetBanhaoTimesRs.getDefaultInstance(),
          0,
          com.game.pb.Banhao.GetBanhaoTimesRs.class,
          com.game.pb.Banhao.GetBanhaoTimesRs.getDefaultInstance());
  }

  public interface BanhaoTimesOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .BanhaoTime timeRecord = 1;
    /**
     * <code>repeated .BanhaoTime timeRecord = 1;</code>
     */
    java.util.List<com.game.pb.Banhao.BanhaoTime> 
        getTimeRecordList();
    /**
     * <code>repeated .BanhaoTime timeRecord = 1;</code>
     */
    com.game.pb.Banhao.BanhaoTime getTimeRecord(int index);
    /**
     * <code>repeated .BanhaoTime timeRecord = 1;</code>
     */
    int getTimeRecordCount();
    /**
     * <code>repeated .BanhaoTime timeRecord = 1;</code>
     */
    java.util.List<? extends com.game.pb.Banhao.BanhaoTimeOrBuilder> 
        getTimeRecordOrBuilderList();
    /**
     * <code>repeated .BanhaoTime timeRecord = 1;</code>
     */
    com.game.pb.Banhao.BanhaoTimeOrBuilder getTimeRecordOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code BanhaoTimes}
   */
  public static final class BanhaoTimes extends
      com.google.protobuf.GeneratedMessage
      implements BanhaoTimesOrBuilder {
    // Use BanhaoTimes.newBuilder() to construct.
    private BanhaoTimes(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BanhaoTimes(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BanhaoTimes defaultInstance;
    public static BanhaoTimes getDefaultInstance() {
      return defaultInstance;
    }

    public BanhaoTimes getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BanhaoTimes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                timeRecord_ = new java.util.ArrayList<com.game.pb.Banhao.BanhaoTime>();
                mutable_bitField0_ |= 0x00000001;
              }
              timeRecord_.add(input.readMessage(com.game.pb.Banhao.BanhaoTime.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          timeRecord_ = java.util.Collections.unmodifiableList(timeRecord_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.pb.Banhao.internal_static_BanhaoTimes_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.pb.Banhao.internal_static_BanhaoTimes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.pb.Banhao.BanhaoTimes.class, com.game.pb.Banhao.BanhaoTimes.Builder.class);
    }

    public static com.google.protobuf.Parser<BanhaoTimes> PARSER =
        new com.google.protobuf.AbstractParser<BanhaoTimes>() {
      public BanhaoTimes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BanhaoTimes(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BanhaoTimes> getParserForType() {
      return PARSER;
    }

    // repeated .BanhaoTime timeRecord = 1;
    public static final int TIMERECORD_FIELD_NUMBER = 1;
    private java.util.List<com.game.pb.Banhao.BanhaoTime> timeRecord_;
    /**
     * <code>repeated .BanhaoTime timeRecord = 1;</code>
     */
    public java.util.List<com.game.pb.Banhao.BanhaoTime> getTimeRecordList() {
      return timeRecord_;
    }
    /**
     * <code>repeated .BanhaoTime timeRecord = 1;</code>
     */
    public java.util.List<? extends com.game.pb.Banhao.BanhaoTimeOrBuilder> 
        getTimeRecordOrBuilderList() {
      return timeRecord_;
    }
    /**
     * <code>repeated .BanhaoTime timeRecord = 1;</code>
     */
    public int getTimeRecordCount() {
      return timeRecord_.size();
    }
    /**
     * <code>repeated .BanhaoTime timeRecord = 1;</code>
     */
    public com.game.pb.Banhao.BanhaoTime getTimeRecord(int index) {
      return timeRecord_.get(index);
    }
    /**
     * <code>repeated .BanhaoTime timeRecord = 1;</code>
     */
    public com.game.pb.Banhao.BanhaoTimeOrBuilder getTimeRecordOrBuilder(
        int index) {
      return timeRecord_.get(index);
    }

    private void initFields() {
      timeRecord_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < timeRecord_.size(); i++) {
        output.writeMessage(1, timeRecord_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < timeRecord_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, timeRecord_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.game.pb.Banhao.BanhaoTimes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.pb.Banhao.BanhaoTimes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.pb.Banhao.BanhaoTimes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.pb.Banhao.BanhaoTimes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.pb.Banhao.BanhaoTimes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.pb.Banhao.BanhaoTimes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.game.pb.Banhao.BanhaoTimes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.game.pb.Banhao.BanhaoTimes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.game.pb.Banhao.BanhaoTimes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.pb.Banhao.BanhaoTimes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.pb.Banhao.BanhaoTimes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BanhaoTimes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game.pb.Banhao.BanhaoTimesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.pb.Banhao.internal_static_BanhaoTimes_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.pb.Banhao.internal_static_BanhaoTimes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.pb.Banhao.BanhaoTimes.class, com.game.pb.Banhao.BanhaoTimes.Builder.class);
      }

      // Construct using com.game.pb.Banhao.BanhaoTimes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTimeRecordFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (timeRecordBuilder_ == null) {
          timeRecord_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          timeRecordBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.pb.Banhao.internal_static_BanhaoTimes_descriptor;
      }

      public com.game.pb.Banhao.BanhaoTimes getDefaultInstanceForType() {
        return com.game.pb.Banhao.BanhaoTimes.getDefaultInstance();
      }

      public com.game.pb.Banhao.BanhaoTimes build() {
        com.game.pb.Banhao.BanhaoTimes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.pb.Banhao.BanhaoTimes buildPartial() {
        com.game.pb.Banhao.BanhaoTimes result = new com.game.pb.Banhao.BanhaoTimes(this);
        int from_bitField0_ = bitField0_;
        if (timeRecordBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            timeRecord_ = java.util.Collections.unmodifiableList(timeRecord_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.timeRecord_ = timeRecord_;
        } else {
          result.timeRecord_ = timeRecordBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.pb.Banhao.BanhaoTimes) {
          return mergeFrom((com.game.pb.Banhao.BanhaoTimes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.pb.Banhao.BanhaoTimes other) {
        if (other == com.game.pb.Banhao.BanhaoTimes.getDefaultInstance()) return this;
        if (timeRecordBuilder_ == null) {
          if (!other.timeRecord_.isEmpty()) {
            if (timeRecord_.isEmpty()) {
              timeRecord_ = other.timeRecord_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTimeRecordIsMutable();
              timeRecord_.addAll(other.timeRecord_);
            }
            onChanged();
          }
        } else {
          if (!other.timeRecord_.isEmpty()) {
            if (timeRecordBuilder_.isEmpty()) {
              timeRecordBuilder_.dispose();
              timeRecordBuilder_ = null;
              timeRecord_ = other.timeRecord_;
              bitField0_ = (bitField0_ & ~0x00000001);
              timeRecordBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTimeRecordFieldBuilder() : null;
            } else {
              timeRecordBuilder_.addAllMessages(other.timeRecord_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.pb.Banhao.BanhaoTimes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.pb.Banhao.BanhaoTimes) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .BanhaoTime timeRecord = 1;
      private java.util.List<com.game.pb.Banhao.BanhaoTime> timeRecord_ =
        java.util.Collections.emptyList();
      private void ensureTimeRecordIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          timeRecord_ = new java.util.ArrayList<com.game.pb.Banhao.BanhaoTime>(timeRecord_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.game.pb.Banhao.BanhaoTime, com.game.pb.Banhao.BanhaoTime.Builder, com.game.pb.Banhao.BanhaoTimeOrBuilder> timeRecordBuilder_;

      /**
       * <code>repeated .BanhaoTime timeRecord = 1;</code>
       */
      public java.util.List<com.game.pb.Banhao.BanhaoTime> getTimeRecordList() {
        if (timeRecordBuilder_ == null) {
          return java.util.Collections.unmodifiableList(timeRecord_);
        } else {
          return timeRecordBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .BanhaoTime timeRecord = 1;</code>
       */
      public int getTimeRecordCount() {
        if (timeRecordBuilder_ == null) {
          return timeRecord_.size();
        } else {
          return timeRecordBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .BanhaoTime timeRecord = 1;</code>
       */
      public com.game.pb.Banhao.BanhaoTime getTimeRecord(int index) {
        if (timeRecordBuilder_ == null) {
          return timeRecord_.get(index);
        } else {
          return timeRecordBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .BanhaoTime timeRecord = 1;</code>
       */
      public Builder setTimeRecord(
          int index, com.game.pb.Banhao.BanhaoTime value) {
        if (timeRecordBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTimeRecordIsMutable();
          timeRecord_.set(index, value);
          onChanged();
        } else {
          timeRecordBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .BanhaoTime timeRecord = 1;</code>
       */
      public Builder setTimeRecord(
          int index, com.game.pb.Banhao.BanhaoTime.Builder builderForValue) {
        if (timeRecordBuilder_ == null) {
          ensureTimeRecordIsMutable();
          timeRecord_.set(index, builderForValue.build());
          onChanged();
        } else {
          timeRecordBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BanhaoTime timeRecord = 1;</code>
       */
      public Builder addTimeRecord(com.game.pb.Banhao.BanhaoTime value) {
        if (timeRecordBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTimeRecordIsMutable();
          timeRecord_.add(value);
          onChanged();
        } else {
          timeRecordBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .BanhaoTime timeRecord = 1;</code>
       */
      public Builder addTimeRecord(
          int index, com.game.pb.Banhao.BanhaoTime value) {
        if (timeRecordBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTimeRecordIsMutable();
          timeRecord_.add(index, value);
          onChanged();
        } else {
          timeRecordBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .BanhaoTime timeRecord = 1;</code>
       */
      public Builder addTimeRecord(
          com.game.pb.Banhao.BanhaoTime.Builder builderForValue) {
        if (timeRecordBuilder_ == null) {
          ensureTimeRecordIsMutable();
          timeRecord_.add(builderForValue.build());
          onChanged();
        } else {
          timeRecordBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BanhaoTime timeRecord = 1;</code>
       */
      public Builder addTimeRecord(
          int index, com.game.pb.Banhao.BanhaoTime.Builder builderForValue) {
        if (timeRecordBuilder_ == null) {
          ensureTimeRecordIsMutable();
          timeRecord_.add(index, builderForValue.build());
          onChanged();
        } else {
          timeRecordBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BanhaoTime timeRecord = 1;</code>
       */
      public Builder addAllTimeRecord(
          java.lang.Iterable<? extends com.game.pb.Banhao.BanhaoTime> values) {
        if (timeRecordBuilder_ == null) {
          ensureTimeRecordIsMutable();
          super.addAll(values, timeRecord_);
          onChanged();
        } else {
          timeRecordBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .BanhaoTime timeRecord = 1;</code>
       */
      public Builder clearTimeRecord() {
        if (timeRecordBuilder_ == null) {
          timeRecord_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          timeRecordBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .BanhaoTime timeRecord = 1;</code>
       */
      public Builder removeTimeRecord(int index) {
        if (timeRecordBuilder_ == null) {
          ensureTimeRecordIsMutable();
          timeRecord_.remove(index);
          onChanged();
        } else {
          timeRecordBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .BanhaoTime timeRecord = 1;</code>
       */
      public com.game.pb.Banhao.BanhaoTime.Builder getTimeRecordBuilder(
          int index) {
        return getTimeRecordFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .BanhaoTime timeRecord = 1;</code>
       */
      public com.game.pb.Banhao.BanhaoTimeOrBuilder getTimeRecordOrBuilder(
          int index) {
        if (timeRecordBuilder_ == null) {
          return timeRecord_.get(index);  } else {
          return timeRecordBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .BanhaoTime timeRecord = 1;</code>
       */
      public java.util.List<? extends com.game.pb.Banhao.BanhaoTimeOrBuilder> 
           getTimeRecordOrBuilderList() {
        if (timeRecordBuilder_ != null) {
          return timeRecordBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(timeRecord_);
        }
      }
      /**
       * <code>repeated .BanhaoTime timeRecord = 1;</code>
       */
      public com.game.pb.Banhao.BanhaoTime.Builder addTimeRecordBuilder() {
        return getTimeRecordFieldBuilder().addBuilder(
            com.game.pb.Banhao.BanhaoTime.getDefaultInstance());
      }
      /**
       * <code>repeated .BanhaoTime timeRecord = 1;</code>
       */
      public com.game.pb.Banhao.BanhaoTime.Builder addTimeRecordBuilder(
          int index) {
        return getTimeRecordFieldBuilder().addBuilder(
            index, com.game.pb.Banhao.BanhaoTime.getDefaultInstance());
      }
      /**
       * <code>repeated .BanhaoTime timeRecord = 1;</code>
       */
      public java.util.List<com.game.pb.Banhao.BanhaoTime.Builder> 
           getTimeRecordBuilderList() {
        return getTimeRecordFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.game.pb.Banhao.BanhaoTime, com.game.pb.Banhao.BanhaoTime.Builder, com.game.pb.Banhao.BanhaoTimeOrBuilder> 
          getTimeRecordFieldBuilder() {
        if (timeRecordBuilder_ == null) {
          timeRecordBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.game.pb.Banhao.BanhaoTime, com.game.pb.Banhao.BanhaoTime.Builder, com.game.pb.Banhao.BanhaoTimeOrBuilder>(
                  timeRecord_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          timeRecord_ = null;
        }
        return timeRecordBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:BanhaoTimes)
    }

    static {
      defaultInstance = new BanhaoTimes(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BanhaoTimes)
  }

  public interface BanhaoTimeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 times = 1;
    /**
     * <code>optional int32 times = 1;</code>
     */
    boolean hasTimes();
    /**
     * <code>optional int32 times = 1;</code>
     */
    int getTimes();

    // optional int32 day = 2;
    /**
     * <code>optional int32 day = 2;</code>
     */
    boolean hasDay();
    /**
     * <code>optional int32 day = 2;</code>
     */
    int getDay();

    // optional int32 timeId = 3;
    /**
     * <code>optional int32 timeId = 3;</code>
     */
    boolean hasTimeId();
    /**
     * <code>optional int32 timeId = 3;</code>
     */
    int getTimeId();
  }
  /**
   * Protobuf type {@code BanhaoTime}
   */
  public static final class BanhaoTime extends
      com.google.protobuf.GeneratedMessage
      implements BanhaoTimeOrBuilder {
    // Use BanhaoTime.newBuilder() to construct.
    private BanhaoTime(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BanhaoTime(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BanhaoTime defaultInstance;
    public static BanhaoTime getDefaultInstance() {
      return defaultInstance;
    }

    public BanhaoTime getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BanhaoTime(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              times_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              day_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              timeId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.pb.Banhao.internal_static_BanhaoTime_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.pb.Banhao.internal_static_BanhaoTime_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.pb.Banhao.BanhaoTime.class, com.game.pb.Banhao.BanhaoTime.Builder.class);
    }

    public static com.google.protobuf.Parser<BanhaoTime> PARSER =
        new com.google.protobuf.AbstractParser<BanhaoTime>() {
      public BanhaoTime parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BanhaoTime(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BanhaoTime> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 times = 1;
    public static final int TIMES_FIELD_NUMBER = 1;
    private int times_;
    /**
     * <code>optional int32 times = 1;</code>
     */
    public boolean hasTimes() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 times = 1;</code>
     */
    public int getTimes() {
      return times_;
    }

    // optional int32 day = 2;
    public static final int DAY_FIELD_NUMBER = 2;
    private int day_;
    /**
     * <code>optional int32 day = 2;</code>
     */
    public boolean hasDay() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 day = 2;</code>
     */
    public int getDay() {
      return day_;
    }

    // optional int32 timeId = 3;
    public static final int TIMEID_FIELD_NUMBER = 3;
    private int timeId_;
    /**
     * <code>optional int32 timeId = 3;</code>
     */
    public boolean hasTimeId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 timeId = 3;</code>
     */
    public int getTimeId() {
      return timeId_;
    }

    private void initFields() {
      times_ = 0;
      day_ = 0;
      timeId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, times_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, day_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, timeId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, times_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, day_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, timeId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.game.pb.Banhao.BanhaoTime parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.pb.Banhao.BanhaoTime parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.pb.Banhao.BanhaoTime parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.pb.Banhao.BanhaoTime parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.pb.Banhao.BanhaoTime parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.pb.Banhao.BanhaoTime parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.game.pb.Banhao.BanhaoTime parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.game.pb.Banhao.BanhaoTime parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.game.pb.Banhao.BanhaoTime parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.pb.Banhao.BanhaoTime parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.pb.Banhao.BanhaoTime prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BanhaoTime}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game.pb.Banhao.BanhaoTimeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.pb.Banhao.internal_static_BanhaoTime_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.pb.Banhao.internal_static_BanhaoTime_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.pb.Banhao.BanhaoTime.class, com.game.pb.Banhao.BanhaoTime.Builder.class);
      }

      // Construct using com.game.pb.Banhao.BanhaoTime.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        times_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        day_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        timeId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.pb.Banhao.internal_static_BanhaoTime_descriptor;
      }

      public com.game.pb.Banhao.BanhaoTime getDefaultInstanceForType() {
        return com.game.pb.Banhao.BanhaoTime.getDefaultInstance();
      }

      public com.game.pb.Banhao.BanhaoTime build() {
        com.game.pb.Banhao.BanhaoTime result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.pb.Banhao.BanhaoTime buildPartial() {
        com.game.pb.Banhao.BanhaoTime result = new com.game.pb.Banhao.BanhaoTime(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.times_ = times_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.day_ = day_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timeId_ = timeId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.pb.Banhao.BanhaoTime) {
          return mergeFrom((com.game.pb.Banhao.BanhaoTime)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.pb.Banhao.BanhaoTime other) {
        if (other == com.game.pb.Banhao.BanhaoTime.getDefaultInstance()) return this;
        if (other.hasTimes()) {
          setTimes(other.getTimes());
        }
        if (other.hasDay()) {
          setDay(other.getDay());
        }
        if (other.hasTimeId()) {
          setTimeId(other.getTimeId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.pb.Banhao.BanhaoTime parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.pb.Banhao.BanhaoTime) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 times = 1;
      private int times_ ;
      /**
       * <code>optional int32 times = 1;</code>
       */
      public boolean hasTimes() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 times = 1;</code>
       */
      public int getTimes() {
        return times_;
      }
      /**
       * <code>optional int32 times = 1;</code>
       */
      public Builder setTimes(int value) {
        bitField0_ |= 0x00000001;
        times_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 times = 1;</code>
       */
      public Builder clearTimes() {
        bitField0_ = (bitField0_ & ~0x00000001);
        times_ = 0;
        onChanged();
        return this;
      }

      // optional int32 day = 2;
      private int day_ ;
      /**
       * <code>optional int32 day = 2;</code>
       */
      public boolean hasDay() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 day = 2;</code>
       */
      public int getDay() {
        return day_;
      }
      /**
       * <code>optional int32 day = 2;</code>
       */
      public Builder setDay(int value) {
        bitField0_ |= 0x00000002;
        day_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 day = 2;</code>
       */
      public Builder clearDay() {
        bitField0_ = (bitField0_ & ~0x00000002);
        day_ = 0;
        onChanged();
        return this;
      }

      // optional int32 timeId = 3;
      private int timeId_ ;
      /**
       * <code>optional int32 timeId = 3;</code>
       */
      public boolean hasTimeId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 timeId = 3;</code>
       */
      public int getTimeId() {
        return timeId_;
      }
      /**
       * <code>optional int32 timeId = 3;</code>
       */
      public Builder setTimeId(int value) {
        bitField0_ |= 0x00000004;
        timeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 timeId = 3;</code>
       */
      public Builder clearTimeId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timeId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BanhaoTime)
    }

    static {
      defaultInstance = new BanhaoTime(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BanhaoTime)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_GetBanhaoTimesRq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetBanhaoTimesRq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_GetBanhaoTimesRs_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetBanhaoTimesRs_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BanhaoTimes_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BanhaoTimes_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BanhaoTime_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BanhaoTime_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Banhao.proto\032\nBase.proto\";\n\020GetBanhaoT" +
      "imesRq2\'\n\003ext\022\005.Base\030\341\363\001 \001(\0132\021.GetBanhao" +
      "TimesRq\"\232\001\n\020GetBanhaoTimesRs\022\027\n\017lootComm" +
      "onTimes\030\001 \001(\005\022\025\n\rlootGoodTimes\030\002 \001(\005\022\025\n\r" +
      "washHeroTimes\030\003 \001(\005\022\026\n\016washEquipTimes\030\004 " +
      "\001(\0052\'\n\003ext\022\005.Base\030\342\363\001 \001(\0132\021.GetBanhaoTim" +
      "esRs\".\n\013BanhaoTimes\022\037\n\ntimeRecord\030\001 \003(\0132" +
      "\013.BanhaoTime\"8\n\nBanhaoTime\022\r\n\005times\030\001 \001(" +
      "\005\022\013\n\003day\030\002 \001(\005\022\016\n\006timeId\030\003 \001(\005B\025\n\013com.ga" +
      "me.pbB\006Banhao"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_GetBanhaoTimesRq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_GetBanhaoTimesRq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_GetBanhaoTimesRq_descriptor,
              new java.lang.String[] { });
          internal_static_GetBanhaoTimesRs_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_GetBanhaoTimesRs_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_GetBanhaoTimesRs_descriptor,
              new java.lang.String[] { "LootCommonTimes", "LootGoodTimes", "WashHeroTimes", "WashEquipTimes", });
          internal_static_BanhaoTimes_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_BanhaoTimes_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BanhaoTimes_descriptor,
              new java.lang.String[] { "TimeRecord", });
          internal_static_BanhaoTime_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_BanhaoTime_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BanhaoTime_descriptor,
              new java.lang.String[] { "Times", "Day", "TimeId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.game.pb.BasePb.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
