// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GmInfo.proto

package com.game.pb;

public final class GmInfoPb {
  private GmInfoPb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ManOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 lordId = 1;
    /**
     * <code>optional int64 lordId = 1;</code>
     */
    boolean hasLordId();
    /**
     * <code>optional int64 lordId = 1;</code>
     */
    long getLordId();

    // optional string nick = 2;
    /**
     * <code>optional string nick = 2;</code>
     */
    boolean hasNick();
    /**
     * <code>optional string nick = 2;</code>
     */
    java.lang.String getNick();
    /**
     * <code>optional string nick = 2;</code>
     */
    com.google.protobuf.ByteString
        getNickBytes();

    // optional int32 level = 3;
    /**
     * <code>optional int32 level = 3;</code>
     */
    boolean hasLevel();
    /**
     * <code>optional int32 level = 3;</code>
     */
    int getLevel();

    // optional int32 title = 4;
    /**
     * <code>optional int32 title = 4;</code>
     */
    boolean hasTitle();
    /**
     * <code>optional int32 title = 4;</code>
     */
    int getTitle();

    // optional int32 vip = 5;
    /**
     * <code>optional int32 vip = 5;</code>
     */
    boolean hasVip();
    /**
     * <code>optional int32 vip = 5;</code>
     */
    int getVip();

    // optional int32 topup = 6;
    /**
     * <code>optional int32 topup = 6;</code>
     */
    boolean hasTopup();
    /**
     * <code>optional int32 topup = 6;</code>
     */
    int getTopup();

    // optional int32 country = 7;
    /**
     * <code>optional int32 country = 7;</code>
     */
    boolean hasCountry();
    /**
     * <code>optional int32 country = 7;</code>
     */
    int getCountry();

    // optional int32 govern = 8;
    /**
     * <code>optional int32 govern = 8;</code>
     */
    boolean hasGovern();
    /**
     * <code>optional int32 govern = 8;</code>
     */
    int getGovern();
  }
  /**
   * Protobuf type {@code Man}
   */
  public static final class Man extends
      com.google.protobuf.GeneratedMessage
      implements ManOrBuilder {
    // Use Man.newBuilder() to construct.
    private Man(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Man(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Man defaultInstance;
    public static Man getDefaultInstance() {
      return defaultInstance;
    }

    public Man getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Man(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              lordId_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              nick_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              level_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              title_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              vip_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              topup_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              country_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              govern_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.pb.GmInfoPb.internal_static_Man_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.pb.GmInfoPb.internal_static_Man_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.pb.GmInfoPb.Man.class, com.game.pb.GmInfoPb.Man.Builder.class);
    }

    public static com.google.protobuf.Parser<Man> PARSER =
        new com.google.protobuf.AbstractParser<Man>() {
      public Man parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Man(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Man> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 lordId = 1;
    public static final int LORDID_FIELD_NUMBER = 1;
    private long lordId_;
    /**
     * <code>optional int64 lordId = 1;</code>
     */
    public boolean hasLordId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 lordId = 1;</code>
     */
    public long getLordId() {
      return lordId_;
    }

    // optional string nick = 2;
    public static final int NICK_FIELD_NUMBER = 2;
    private java.lang.Object nick_;
    /**
     * <code>optional string nick = 2;</code>
     */
    public boolean hasNick() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string nick = 2;</code>
     */
    public java.lang.String getNick() {
      java.lang.Object ref = nick_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nick_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string nick = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNickBytes() {
      java.lang.Object ref = nick_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nick_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 level = 3;
    public static final int LEVEL_FIELD_NUMBER = 3;
    private int level_;
    /**
     * <code>optional int32 level = 3;</code>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 level = 3;</code>
     */
    public int getLevel() {
      return level_;
    }

    // optional int32 title = 4;
    public static final int TITLE_FIELD_NUMBER = 4;
    private int title_;
    /**
     * <code>optional int32 title = 4;</code>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 title = 4;</code>
     */
    public int getTitle() {
      return title_;
    }

    // optional int32 vip = 5;
    public static final int VIP_FIELD_NUMBER = 5;
    private int vip_;
    /**
     * <code>optional int32 vip = 5;</code>
     */
    public boolean hasVip() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 vip = 5;</code>
     */
    public int getVip() {
      return vip_;
    }

    // optional int32 topup = 6;
    public static final int TOPUP_FIELD_NUMBER = 6;
    private int topup_;
    /**
     * <code>optional int32 topup = 6;</code>
     */
    public boolean hasTopup() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 topup = 6;</code>
     */
    public int getTopup() {
      return topup_;
    }

    // optional int32 country = 7;
    public static final int COUNTRY_FIELD_NUMBER = 7;
    private int country_;
    /**
     * <code>optional int32 country = 7;</code>
     */
    public boolean hasCountry() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 country = 7;</code>
     */
    public int getCountry() {
      return country_;
    }

    // optional int32 govern = 8;
    public static final int GOVERN_FIELD_NUMBER = 8;
    private int govern_;
    /**
     * <code>optional int32 govern = 8;</code>
     */
    public boolean hasGovern() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 govern = 8;</code>
     */
    public int getGovern() {
      return govern_;
    }

    private void initFields() {
      lordId_ = 0L;
      nick_ = "";
      level_ = 0;
      title_ = 0;
      vip_ = 0;
      topup_ = 0;
      country_ = 0;
      govern_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, lordId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNickBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, level_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, title_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, vip_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, topup_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, country_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, govern_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, lordId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNickBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, level_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, title_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, vip_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, topup_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, country_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, govern_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.game.pb.GmInfoPb.Man parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.pb.GmInfoPb.Man parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.pb.GmInfoPb.Man parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.pb.GmInfoPb.Man parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.pb.GmInfoPb.Man parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.pb.GmInfoPb.Man parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.game.pb.GmInfoPb.Man parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.game.pb.GmInfoPb.Man parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.game.pb.GmInfoPb.Man parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.pb.GmInfoPb.Man parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.pb.GmInfoPb.Man prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Man}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game.pb.GmInfoPb.ManOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.pb.GmInfoPb.internal_static_Man_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.pb.GmInfoPb.internal_static_Man_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.pb.GmInfoPb.Man.class, com.game.pb.GmInfoPb.Man.Builder.class);
      }

      // Construct using com.game.pb.GmInfoPb.Man.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        lordId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        nick_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        title_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        vip_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        topup_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        country_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        govern_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.pb.GmInfoPb.internal_static_Man_descriptor;
      }

      public com.game.pb.GmInfoPb.Man getDefaultInstanceForType() {
        return com.game.pb.GmInfoPb.Man.getDefaultInstance();
      }

      public com.game.pb.GmInfoPb.Man build() {
        com.game.pb.GmInfoPb.Man result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.pb.GmInfoPb.Man buildPartial() {
        com.game.pb.GmInfoPb.Man result = new com.game.pb.GmInfoPb.Man(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.lordId_ = lordId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.nick_ = nick_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.vip_ = vip_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.topup_ = topup_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.country_ = country_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.govern_ = govern_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.pb.GmInfoPb.Man) {
          return mergeFrom((com.game.pb.GmInfoPb.Man)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.pb.GmInfoPb.Man other) {
        if (other == com.game.pb.GmInfoPb.Man.getDefaultInstance()) return this;
        if (other.hasLordId()) {
          setLordId(other.getLordId());
        }
        if (other.hasNick()) {
          bitField0_ |= 0x00000002;
          nick_ = other.nick_;
          onChanged();
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        if (other.hasVip()) {
          setVip(other.getVip());
        }
        if (other.hasTopup()) {
          setTopup(other.getTopup());
        }
        if (other.hasCountry()) {
          setCountry(other.getCountry());
        }
        if (other.hasGovern()) {
          setGovern(other.getGovern());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.pb.GmInfoPb.Man parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.pb.GmInfoPb.Man) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 lordId = 1;
      private long lordId_ ;
      /**
       * <code>optional int64 lordId = 1;</code>
       */
      public boolean hasLordId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 lordId = 1;</code>
       */
      public long getLordId() {
        return lordId_;
      }
      /**
       * <code>optional int64 lordId = 1;</code>
       */
      public Builder setLordId(long value) {
        bitField0_ |= 0x00000001;
        lordId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 lordId = 1;</code>
       */
      public Builder clearLordId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        lordId_ = 0L;
        onChanged();
        return this;
      }

      // optional string nick = 2;
      private java.lang.Object nick_ = "";
      /**
       * <code>optional string nick = 2;</code>
       */
      public boolean hasNick() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string nick = 2;</code>
       */
      public java.lang.String getNick() {
        java.lang.Object ref = nick_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          nick_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string nick = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNickBytes() {
        java.lang.Object ref = nick_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nick_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string nick = 2;</code>
       */
      public Builder setNick(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        nick_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string nick = 2;</code>
       */
      public Builder clearNick() {
        bitField0_ = (bitField0_ & ~0x00000002);
        nick_ = getDefaultInstance().getNick();
        onChanged();
        return this;
      }
      /**
       * <code>optional string nick = 2;</code>
       */
      public Builder setNickBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        nick_ = value;
        onChanged();
        return this;
      }

      // optional int32 level = 3;
      private int level_ ;
      /**
       * <code>optional int32 level = 3;</code>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 level = 3;</code>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>optional int32 level = 3;</code>
       */
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000004;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 level = 3;</code>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        level_ = 0;
        onChanged();
        return this;
      }

      // optional int32 title = 4;
      private int title_ ;
      /**
       * <code>optional int32 title = 4;</code>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 title = 4;</code>
       */
      public int getTitle() {
        return title_;
      }
      /**
       * <code>optional int32 title = 4;</code>
       */
      public Builder setTitle(int value) {
        bitField0_ |= 0x00000008;
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 title = 4;</code>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000008);
        title_ = 0;
        onChanged();
        return this;
      }

      // optional int32 vip = 5;
      private int vip_ ;
      /**
       * <code>optional int32 vip = 5;</code>
       */
      public boolean hasVip() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 vip = 5;</code>
       */
      public int getVip() {
        return vip_;
      }
      /**
       * <code>optional int32 vip = 5;</code>
       */
      public Builder setVip(int value) {
        bitField0_ |= 0x00000010;
        vip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 vip = 5;</code>
       */
      public Builder clearVip() {
        bitField0_ = (bitField0_ & ~0x00000010);
        vip_ = 0;
        onChanged();
        return this;
      }

      // optional int32 topup = 6;
      private int topup_ ;
      /**
       * <code>optional int32 topup = 6;</code>
       */
      public boolean hasTopup() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 topup = 6;</code>
       */
      public int getTopup() {
        return topup_;
      }
      /**
       * <code>optional int32 topup = 6;</code>
       */
      public Builder setTopup(int value) {
        bitField0_ |= 0x00000020;
        topup_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 topup = 6;</code>
       */
      public Builder clearTopup() {
        bitField0_ = (bitField0_ & ~0x00000020);
        topup_ = 0;
        onChanged();
        return this;
      }

      // optional int32 country = 7;
      private int country_ ;
      /**
       * <code>optional int32 country = 7;</code>
       */
      public boolean hasCountry() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 country = 7;</code>
       */
      public int getCountry() {
        return country_;
      }
      /**
       * <code>optional int32 country = 7;</code>
       */
      public Builder setCountry(int value) {
        bitField0_ |= 0x00000040;
        country_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 country = 7;</code>
       */
      public Builder clearCountry() {
        bitField0_ = (bitField0_ & ~0x00000040);
        country_ = 0;
        onChanged();
        return this;
      }

      // optional int32 govern = 8;
      private int govern_ ;
      /**
       * <code>optional int32 govern = 8;</code>
       */
      public boolean hasGovern() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 govern = 8;</code>
       */
      public int getGovern() {
        return govern_;
      }
      /**
       * <code>optional int32 govern = 8;</code>
       */
      public Builder setGovern(int value) {
        bitField0_ |= 0x00000080;
        govern_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 govern = 8;</code>
       */
      public Builder clearGovern() {
        bitField0_ = (bitField0_ & ~0x00000080);
        govern_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Man)
    }

    static {
      defaultInstance = new Man(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Man)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Man_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Man_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014GmInfo.proto\"~\n\003Man\022\016\n\006lordId\030\001 \001(\003\022\014\n" +
      "\004nick\030\002 \001(\t\022\r\n\005level\030\003 \001(\005\022\r\n\005title\030\004 \001(" +
      "\005\022\013\n\003vip\030\005 \001(\005\022\r\n\005topup\030\006 \001(\005\022\017\n\007country" +
      "\030\007 \001(\005\022\016\n\006govern\030\010 \001(\005B\027\n\013com.game.pbB\010G" +
      "mInfoPb"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Man_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Man_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Man_descriptor,
              new java.lang.String[] { "LordId", "Nick", "Level", "Title", "Vip", "Topup", "Country", "Govern", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
