// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FirstBlood.proto

package com.game.pb;

public final class FirstBloodPb {
  private FirstBloodPb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.game.pb.FirstBloodPb.CityFirstBloodRq.ext);
    registry.add(com.game.pb.FirstBloodPb.CityFirstBloodRs.ext);
    registry.add(com.game.pb.FirstBloodPb.AllFirstBloodRq.ext);
    registry.add(com.game.pb.FirstBloodPb.AllFirstBloodRs.ext);
  }
  public interface CityFirstBloodRqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 mapId = 1;
    /**
     * <code>optional int32 mapId = 1;</code>
     */
    boolean hasMapId();
    /**
     * <code>optional int32 mapId = 1;</code>
     */
    int getMapId();

    // optional int32 page = 2;
    /**
     * <code>optional int32 page = 2;</code>
     *
     * <pre>
     * 页数
     * </pre>
     */
    boolean hasPage();
    /**
     * <code>optional int32 page = 2;</code>
     *
     * <pre>
     * 页数
     * </pre>
     */
    int getPage();

    // optional int32 cityType = 3;
    /**
     * <code>optional int32 cityType = 3;</code>
     *
     * <pre>
     * 城市类型
     * </pre>
     */
    boolean hasCityType();
    /**
     * <code>optional int32 cityType = 3;</code>
     *
     * <pre>
     * 城市类型
     * </pre>
     */
    int getCityType();
  }
  /**
   * Protobuf type {@code CityFirstBloodRq}
   *
   * <pre>
   * 首杀单地图信息
   * </pre>
   */
  public static final class CityFirstBloodRq extends
      com.google.protobuf.GeneratedMessage
      implements CityFirstBloodRqOrBuilder {
    // Use CityFirstBloodRq.newBuilder() to construct.
    private CityFirstBloodRq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CityFirstBloodRq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CityFirstBloodRq defaultInstance;
    public static CityFirstBloodRq getDefaultInstance() {
      return defaultInstance;
    }

    public CityFirstBloodRq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CityFirstBloodRq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              mapId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              page_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              cityType_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.pb.FirstBloodPb.internal_static_CityFirstBloodRq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.pb.FirstBloodPb.internal_static_CityFirstBloodRq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.pb.FirstBloodPb.CityFirstBloodRq.class, com.game.pb.FirstBloodPb.CityFirstBloodRq.Builder.class);
    }

    public static com.google.protobuf.Parser<CityFirstBloodRq> PARSER =
        new com.google.protobuf.AbstractParser<CityFirstBloodRq>() {
      public CityFirstBloodRq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CityFirstBloodRq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CityFirstBloodRq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 mapId = 1;
    public static final int MAPID_FIELD_NUMBER = 1;
    private int mapId_;
    /**
     * <code>optional int32 mapId = 1;</code>
     */
    public boolean hasMapId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 mapId = 1;</code>
     */
    public int getMapId() {
      return mapId_;
    }

    // optional int32 page = 2;
    public static final int PAGE_FIELD_NUMBER = 2;
    private int page_;
    /**
     * <code>optional int32 page = 2;</code>
     *
     * <pre>
     * 页数
     * </pre>
     */
    public boolean hasPage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 page = 2;</code>
     *
     * <pre>
     * 页数
     * </pre>
     */
    public int getPage() {
      return page_;
    }

    // optional int32 cityType = 3;
    public static final int CITYTYPE_FIELD_NUMBER = 3;
    private int cityType_;
    /**
     * <code>optional int32 cityType = 3;</code>
     *
     * <pre>
     * 城市类型
     * </pre>
     */
    public boolean hasCityType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 cityType = 3;</code>
     *
     * <pre>
     * 城市类型
     * </pre>
     */
    public int getCityType() {
      return cityType_;
    }

    private void initFields() {
      mapId_ = 0;
      page_ = 0;
      cityType_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, mapId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, page_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, cityType_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, mapId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, page_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, cityType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.game.pb.FirstBloodPb.CityFirstBloodRq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.pb.FirstBloodPb.CityFirstBloodRq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.pb.FirstBloodPb.CityFirstBloodRq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.pb.FirstBloodPb.CityFirstBloodRq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.pb.FirstBloodPb.CityFirstBloodRq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.pb.FirstBloodPb.CityFirstBloodRq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.game.pb.FirstBloodPb.CityFirstBloodRq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.game.pb.FirstBloodPb.CityFirstBloodRq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.game.pb.FirstBloodPb.CityFirstBloodRq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.pb.FirstBloodPb.CityFirstBloodRq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.pb.FirstBloodPb.CityFirstBloodRq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CityFirstBloodRq}
     *
     * <pre>
     * 首杀单地图信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game.pb.FirstBloodPb.CityFirstBloodRqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.pb.FirstBloodPb.internal_static_CityFirstBloodRq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.pb.FirstBloodPb.internal_static_CityFirstBloodRq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.pb.FirstBloodPb.CityFirstBloodRq.class, com.game.pb.FirstBloodPb.CityFirstBloodRq.Builder.class);
      }

      // Construct using com.game.pb.FirstBloodPb.CityFirstBloodRq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        mapId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        page_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        cityType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.pb.FirstBloodPb.internal_static_CityFirstBloodRq_descriptor;
      }

      public com.game.pb.FirstBloodPb.CityFirstBloodRq getDefaultInstanceForType() {
        return com.game.pb.FirstBloodPb.CityFirstBloodRq.getDefaultInstance();
      }

      public com.game.pb.FirstBloodPb.CityFirstBloodRq build() {
        com.game.pb.FirstBloodPb.CityFirstBloodRq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.pb.FirstBloodPb.CityFirstBloodRq buildPartial() {
        com.game.pb.FirstBloodPb.CityFirstBloodRq result = new com.game.pb.FirstBloodPb.CityFirstBloodRq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.mapId_ = mapId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.page_ = page_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.cityType_ = cityType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.pb.FirstBloodPb.CityFirstBloodRq) {
          return mergeFrom((com.game.pb.FirstBloodPb.CityFirstBloodRq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.pb.FirstBloodPb.CityFirstBloodRq other) {
        if (other == com.game.pb.FirstBloodPb.CityFirstBloodRq.getDefaultInstance()) return this;
        if (other.hasMapId()) {
          setMapId(other.getMapId());
        }
        if (other.hasPage()) {
          setPage(other.getPage());
        }
        if (other.hasCityType()) {
          setCityType(other.getCityType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.pb.FirstBloodPb.CityFirstBloodRq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.pb.FirstBloodPb.CityFirstBloodRq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 mapId = 1;
      private int mapId_ ;
      /**
       * <code>optional int32 mapId = 1;</code>
       */
      public boolean hasMapId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 mapId = 1;</code>
       */
      public int getMapId() {
        return mapId_;
      }
      /**
       * <code>optional int32 mapId = 1;</code>
       */
      public Builder setMapId(int value) {
        bitField0_ |= 0x00000001;
        mapId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 mapId = 1;</code>
       */
      public Builder clearMapId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        mapId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 page = 2;
      private int page_ ;
      /**
       * <code>optional int32 page = 2;</code>
       *
       * <pre>
       * 页数
       * </pre>
       */
      public boolean hasPage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 page = 2;</code>
       *
       * <pre>
       * 页数
       * </pre>
       */
      public int getPage() {
        return page_;
      }
      /**
       * <code>optional int32 page = 2;</code>
       *
       * <pre>
       * 页数
       * </pre>
       */
      public Builder setPage(int value) {
        bitField0_ |= 0x00000002;
        page_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 page = 2;</code>
       *
       * <pre>
       * 页数
       * </pre>
       */
      public Builder clearPage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        page_ = 0;
        onChanged();
        return this;
      }

      // optional int32 cityType = 3;
      private int cityType_ ;
      /**
       * <code>optional int32 cityType = 3;</code>
       *
       * <pre>
       * 城市类型
       * </pre>
       */
      public boolean hasCityType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 cityType = 3;</code>
       *
       * <pre>
       * 城市类型
       * </pre>
       */
      public int getCityType() {
        return cityType_;
      }
      /**
       * <code>optional int32 cityType = 3;</code>
       *
       * <pre>
       * 城市类型
       * </pre>
       */
      public Builder setCityType(int value) {
        bitField0_ |= 0x00000004;
        cityType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 cityType = 3;</code>
       *
       * <pre>
       * 城市类型
       * </pre>
       */
      public Builder clearCityType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        cityType_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CityFirstBloodRq)
    }

    static {
      defaultInstance = new CityFirstBloodRq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CityFirstBloodRq)
    public static final int EXT_FIELD_NUMBER = 60301;
    /**
     * <code>extend .Base { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.game.pb.BasePb.Base,
        com.game.pb.FirstBloodPb.CityFirstBloodRq> ext = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.game.pb.FirstBloodPb.CityFirstBloodRq.getDefaultInstance(),
          0,
          com.game.pb.FirstBloodPb.CityFirstBloodRq.class,
          com.game.pb.FirstBloodPb.CityFirstBloodRq.getDefaultInstance());
  }

  public interface CityFirstBloodRsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .FirstBloodMapInfo mapInfo = 1;
    /**
     * <code>optional .FirstBloodMapInfo mapInfo = 1;</code>
     *
     * <pre>
     * 协助者的信息
     * </pre>
     */
    boolean hasMapInfo();
    /**
     * <code>optional .FirstBloodMapInfo mapInfo = 1;</code>
     *
     * <pre>
     * 协助者的信息
     * </pre>
     */
    com.game.pb.CommonPb.FirstBloodMapInfo getMapInfo();
    /**
     * <code>optional .FirstBloodMapInfo mapInfo = 1;</code>
     *
     * <pre>
     * 协助者的信息
     * </pre>
     */
    com.game.pb.CommonPb.FirstBloodMapInfoOrBuilder getMapInfoOrBuilder();
  }
  /**
   * Protobuf type {@code CityFirstBloodRs}
   *
   * <pre>
   * 首杀单地图信息
   * </pre>
   */
  public static final class CityFirstBloodRs extends
      com.google.protobuf.GeneratedMessage
      implements CityFirstBloodRsOrBuilder {
    // Use CityFirstBloodRs.newBuilder() to construct.
    private CityFirstBloodRs(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CityFirstBloodRs(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CityFirstBloodRs defaultInstance;
    public static CityFirstBloodRs getDefaultInstance() {
      return defaultInstance;
    }

    public CityFirstBloodRs getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CityFirstBloodRs(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.game.pb.CommonPb.FirstBloodMapInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = mapInfo_.toBuilder();
              }
              mapInfo_ = input.readMessage(com.game.pb.CommonPb.FirstBloodMapInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(mapInfo_);
                mapInfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.pb.FirstBloodPb.internal_static_CityFirstBloodRs_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.pb.FirstBloodPb.internal_static_CityFirstBloodRs_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.pb.FirstBloodPb.CityFirstBloodRs.class, com.game.pb.FirstBloodPb.CityFirstBloodRs.Builder.class);
    }

    public static com.google.protobuf.Parser<CityFirstBloodRs> PARSER =
        new com.google.protobuf.AbstractParser<CityFirstBloodRs>() {
      public CityFirstBloodRs parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CityFirstBloodRs(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CityFirstBloodRs> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .FirstBloodMapInfo mapInfo = 1;
    public static final int MAPINFO_FIELD_NUMBER = 1;
    private com.game.pb.CommonPb.FirstBloodMapInfo mapInfo_;
    /**
     * <code>optional .FirstBloodMapInfo mapInfo = 1;</code>
     *
     * <pre>
     * 协助者的信息
     * </pre>
     */
    public boolean hasMapInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .FirstBloodMapInfo mapInfo = 1;</code>
     *
     * <pre>
     * 协助者的信息
     * </pre>
     */
    public com.game.pb.CommonPb.FirstBloodMapInfo getMapInfo() {
      return mapInfo_;
    }
    /**
     * <code>optional .FirstBloodMapInfo mapInfo = 1;</code>
     *
     * <pre>
     * 协助者的信息
     * </pre>
     */
    public com.game.pb.CommonPb.FirstBloodMapInfoOrBuilder getMapInfoOrBuilder() {
      return mapInfo_;
    }

    private void initFields() {
      mapInfo_ = com.game.pb.CommonPb.FirstBloodMapInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, mapInfo_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, mapInfo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.game.pb.FirstBloodPb.CityFirstBloodRs parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.pb.FirstBloodPb.CityFirstBloodRs parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.pb.FirstBloodPb.CityFirstBloodRs parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.pb.FirstBloodPb.CityFirstBloodRs parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.pb.FirstBloodPb.CityFirstBloodRs parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.pb.FirstBloodPb.CityFirstBloodRs parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.game.pb.FirstBloodPb.CityFirstBloodRs parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.game.pb.FirstBloodPb.CityFirstBloodRs parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.game.pb.FirstBloodPb.CityFirstBloodRs parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.pb.FirstBloodPb.CityFirstBloodRs parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.pb.FirstBloodPb.CityFirstBloodRs prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CityFirstBloodRs}
     *
     * <pre>
     * 首杀单地图信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game.pb.FirstBloodPb.CityFirstBloodRsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.pb.FirstBloodPb.internal_static_CityFirstBloodRs_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.pb.FirstBloodPb.internal_static_CityFirstBloodRs_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.pb.FirstBloodPb.CityFirstBloodRs.class, com.game.pb.FirstBloodPb.CityFirstBloodRs.Builder.class);
      }

      // Construct using com.game.pb.FirstBloodPb.CityFirstBloodRs.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMapInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (mapInfoBuilder_ == null) {
          mapInfo_ = com.game.pb.CommonPb.FirstBloodMapInfo.getDefaultInstance();
        } else {
          mapInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.pb.FirstBloodPb.internal_static_CityFirstBloodRs_descriptor;
      }

      public com.game.pb.FirstBloodPb.CityFirstBloodRs getDefaultInstanceForType() {
        return com.game.pb.FirstBloodPb.CityFirstBloodRs.getDefaultInstance();
      }

      public com.game.pb.FirstBloodPb.CityFirstBloodRs build() {
        com.game.pb.FirstBloodPb.CityFirstBloodRs result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.pb.FirstBloodPb.CityFirstBloodRs buildPartial() {
        com.game.pb.FirstBloodPb.CityFirstBloodRs result = new com.game.pb.FirstBloodPb.CityFirstBloodRs(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (mapInfoBuilder_ == null) {
          result.mapInfo_ = mapInfo_;
        } else {
          result.mapInfo_ = mapInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.pb.FirstBloodPb.CityFirstBloodRs) {
          return mergeFrom((com.game.pb.FirstBloodPb.CityFirstBloodRs)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.pb.FirstBloodPb.CityFirstBloodRs other) {
        if (other == com.game.pb.FirstBloodPb.CityFirstBloodRs.getDefaultInstance()) return this;
        if (other.hasMapInfo()) {
          mergeMapInfo(other.getMapInfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.pb.FirstBloodPb.CityFirstBloodRs parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.pb.FirstBloodPb.CityFirstBloodRs) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .FirstBloodMapInfo mapInfo = 1;
      private com.game.pb.CommonPb.FirstBloodMapInfo mapInfo_ = com.game.pb.CommonPb.FirstBloodMapInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.game.pb.CommonPb.FirstBloodMapInfo, com.game.pb.CommonPb.FirstBloodMapInfo.Builder, com.game.pb.CommonPb.FirstBloodMapInfoOrBuilder> mapInfoBuilder_;
      /**
       * <code>optional .FirstBloodMapInfo mapInfo = 1;</code>
       *
       * <pre>
       * 协助者的信息
       * </pre>
       */
      public boolean hasMapInfo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .FirstBloodMapInfo mapInfo = 1;</code>
       *
       * <pre>
       * 协助者的信息
       * </pre>
       */
      public com.game.pb.CommonPb.FirstBloodMapInfo getMapInfo() {
        if (mapInfoBuilder_ == null) {
          return mapInfo_;
        } else {
          return mapInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .FirstBloodMapInfo mapInfo = 1;</code>
       *
       * <pre>
       * 协助者的信息
       * </pre>
       */
      public Builder setMapInfo(com.game.pb.CommonPb.FirstBloodMapInfo value) {
        if (mapInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          mapInfo_ = value;
          onChanged();
        } else {
          mapInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .FirstBloodMapInfo mapInfo = 1;</code>
       *
       * <pre>
       * 协助者的信息
       * </pre>
       */
      public Builder setMapInfo(
          com.game.pb.CommonPb.FirstBloodMapInfo.Builder builderForValue) {
        if (mapInfoBuilder_ == null) {
          mapInfo_ = builderForValue.build();
          onChanged();
        } else {
          mapInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .FirstBloodMapInfo mapInfo = 1;</code>
       *
       * <pre>
       * 协助者的信息
       * </pre>
       */
      public Builder mergeMapInfo(com.game.pb.CommonPb.FirstBloodMapInfo value) {
        if (mapInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              mapInfo_ != com.game.pb.CommonPb.FirstBloodMapInfo.getDefaultInstance()) {
            mapInfo_ =
              com.game.pb.CommonPb.FirstBloodMapInfo.newBuilder(mapInfo_).mergeFrom(value).buildPartial();
          } else {
            mapInfo_ = value;
          }
          onChanged();
        } else {
          mapInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .FirstBloodMapInfo mapInfo = 1;</code>
       *
       * <pre>
       * 协助者的信息
       * </pre>
       */
      public Builder clearMapInfo() {
        if (mapInfoBuilder_ == null) {
          mapInfo_ = com.game.pb.CommonPb.FirstBloodMapInfo.getDefaultInstance();
          onChanged();
        } else {
          mapInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .FirstBloodMapInfo mapInfo = 1;</code>
       *
       * <pre>
       * 协助者的信息
       * </pre>
       */
      public com.game.pb.CommonPb.FirstBloodMapInfo.Builder getMapInfoBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMapInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .FirstBloodMapInfo mapInfo = 1;</code>
       *
       * <pre>
       * 协助者的信息
       * </pre>
       */
      public com.game.pb.CommonPb.FirstBloodMapInfoOrBuilder getMapInfoOrBuilder() {
        if (mapInfoBuilder_ != null) {
          return mapInfoBuilder_.getMessageOrBuilder();
        } else {
          return mapInfo_;
        }
      }
      /**
       * <code>optional .FirstBloodMapInfo mapInfo = 1;</code>
       *
       * <pre>
       * 协助者的信息
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.game.pb.CommonPb.FirstBloodMapInfo, com.game.pb.CommonPb.FirstBloodMapInfo.Builder, com.game.pb.CommonPb.FirstBloodMapInfoOrBuilder> 
          getMapInfoFieldBuilder() {
        if (mapInfoBuilder_ == null) {
          mapInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.game.pb.CommonPb.FirstBloodMapInfo, com.game.pb.CommonPb.FirstBloodMapInfo.Builder, com.game.pb.CommonPb.FirstBloodMapInfoOrBuilder>(
                  mapInfo_,
                  getParentForChildren(),
                  isClean());
          mapInfo_ = null;
        }
        return mapInfoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:CityFirstBloodRs)
    }

    static {
      defaultInstance = new CityFirstBloodRs(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CityFirstBloodRs)
    public static final int EXT_FIELD_NUMBER = 60302;
    /**
     * <code>extend .Base { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.game.pb.BasePb.Base,
        com.game.pb.FirstBloodPb.CityFirstBloodRs> ext = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.game.pb.FirstBloodPb.CityFirstBloodRs.getDefaultInstance(),
          0,
          com.game.pb.FirstBloodPb.CityFirstBloodRs.class,
          com.game.pb.FirstBloodPb.CityFirstBloodRs.getDefaultInstance());
  }

  public interface AllFirstBloodRqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code AllFirstBloodRq}
   *
   * <pre>
   * 首杀总览信息
   * </pre>
   */
  public static final class AllFirstBloodRq extends
      com.google.protobuf.GeneratedMessage
      implements AllFirstBloodRqOrBuilder {
    // Use AllFirstBloodRq.newBuilder() to construct.
    private AllFirstBloodRq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AllFirstBloodRq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AllFirstBloodRq defaultInstance;
    public static AllFirstBloodRq getDefaultInstance() {
      return defaultInstance;
    }

    public AllFirstBloodRq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AllFirstBloodRq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.pb.FirstBloodPb.internal_static_AllFirstBloodRq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.pb.FirstBloodPb.internal_static_AllFirstBloodRq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.pb.FirstBloodPb.AllFirstBloodRq.class, com.game.pb.FirstBloodPb.AllFirstBloodRq.Builder.class);
    }

    public static com.google.protobuf.Parser<AllFirstBloodRq> PARSER =
        new com.google.protobuf.AbstractParser<AllFirstBloodRq>() {
      public AllFirstBloodRq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AllFirstBloodRq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AllFirstBloodRq> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.game.pb.FirstBloodPb.AllFirstBloodRq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.pb.FirstBloodPb.AllFirstBloodRq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.pb.FirstBloodPb.AllFirstBloodRq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.pb.FirstBloodPb.AllFirstBloodRq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.pb.FirstBloodPb.AllFirstBloodRq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.pb.FirstBloodPb.AllFirstBloodRq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.game.pb.FirstBloodPb.AllFirstBloodRq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.game.pb.FirstBloodPb.AllFirstBloodRq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.game.pb.FirstBloodPb.AllFirstBloodRq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.pb.FirstBloodPb.AllFirstBloodRq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.pb.FirstBloodPb.AllFirstBloodRq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AllFirstBloodRq}
     *
     * <pre>
     * 首杀总览信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game.pb.FirstBloodPb.AllFirstBloodRqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.pb.FirstBloodPb.internal_static_AllFirstBloodRq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.pb.FirstBloodPb.internal_static_AllFirstBloodRq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.pb.FirstBloodPb.AllFirstBloodRq.class, com.game.pb.FirstBloodPb.AllFirstBloodRq.Builder.class);
      }

      // Construct using com.game.pb.FirstBloodPb.AllFirstBloodRq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.pb.FirstBloodPb.internal_static_AllFirstBloodRq_descriptor;
      }

      public com.game.pb.FirstBloodPb.AllFirstBloodRq getDefaultInstanceForType() {
        return com.game.pb.FirstBloodPb.AllFirstBloodRq.getDefaultInstance();
      }

      public com.game.pb.FirstBloodPb.AllFirstBloodRq build() {
        com.game.pb.FirstBloodPb.AllFirstBloodRq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.pb.FirstBloodPb.AllFirstBloodRq buildPartial() {
        com.game.pb.FirstBloodPb.AllFirstBloodRq result = new com.game.pb.FirstBloodPb.AllFirstBloodRq(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.pb.FirstBloodPb.AllFirstBloodRq) {
          return mergeFrom((com.game.pb.FirstBloodPb.AllFirstBloodRq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.pb.FirstBloodPb.AllFirstBloodRq other) {
        if (other == com.game.pb.FirstBloodPb.AllFirstBloodRq.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.pb.FirstBloodPb.AllFirstBloodRq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.pb.FirstBloodPb.AllFirstBloodRq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:AllFirstBloodRq)
    }

    static {
      defaultInstance = new AllFirstBloodRq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:AllFirstBloodRq)
    public static final int EXT_FIELD_NUMBER = 60303;
    /**
     * <code>extend .Base { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.game.pb.BasePb.Base,
        com.game.pb.FirstBloodPb.AllFirstBloodRq> ext = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.game.pb.FirstBloodPb.AllFirstBloodRq.getDefaultInstance(),
          0,
          com.game.pb.FirstBloodPb.AllFirstBloodRq.class,
          com.game.pb.FirstBloodPb.AllFirstBloodRq.getDefaultInstance());
  }

  public interface AllFirstBloodRsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .FirstBloodInfo allInfo = 1;
    /**
     * <code>repeated .FirstBloodInfo allInfo = 1;</code>
     *
     * <pre>
     * 首杀人的信息
     * </pre>
     */
    java.util.List<com.game.pb.CommonPb.FirstBloodInfo> 
        getAllInfoList();
    /**
     * <code>repeated .FirstBloodInfo allInfo = 1;</code>
     *
     * <pre>
     * 首杀人的信息
     * </pre>
     */
    com.game.pb.CommonPb.FirstBloodInfo getAllInfo(int index);
    /**
     * <code>repeated .FirstBloodInfo allInfo = 1;</code>
     *
     * <pre>
     * 首杀人的信息
     * </pre>
     */
    int getAllInfoCount();
    /**
     * <code>repeated .FirstBloodInfo allInfo = 1;</code>
     *
     * <pre>
     * 首杀人的信息
     * </pre>
     */
    java.util.List<? extends com.game.pb.CommonPb.FirstBloodInfoOrBuilder> 
        getAllInfoOrBuilderList();
    /**
     * <code>repeated .FirstBloodInfo allInfo = 1;</code>
     *
     * <pre>
     * 首杀人的信息
     * </pre>
     */
    com.game.pb.CommonPb.FirstBloodInfoOrBuilder getAllInfoOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code AllFirstBloodRs}
   *
   * <pre>
   * 首杀总览信息
   * </pre>
   */
  public static final class AllFirstBloodRs extends
      com.google.protobuf.GeneratedMessage
      implements AllFirstBloodRsOrBuilder {
    // Use AllFirstBloodRs.newBuilder() to construct.
    private AllFirstBloodRs(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AllFirstBloodRs(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AllFirstBloodRs defaultInstance;
    public static AllFirstBloodRs getDefaultInstance() {
      return defaultInstance;
    }

    public AllFirstBloodRs getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AllFirstBloodRs(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                allInfo_ = new java.util.ArrayList<com.game.pb.CommonPb.FirstBloodInfo>();
                mutable_bitField0_ |= 0x00000001;
              }
              allInfo_.add(input.readMessage(com.game.pb.CommonPb.FirstBloodInfo.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          allInfo_ = java.util.Collections.unmodifiableList(allInfo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.pb.FirstBloodPb.internal_static_AllFirstBloodRs_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.pb.FirstBloodPb.internal_static_AllFirstBloodRs_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.pb.FirstBloodPb.AllFirstBloodRs.class, com.game.pb.FirstBloodPb.AllFirstBloodRs.Builder.class);
    }

    public static com.google.protobuf.Parser<AllFirstBloodRs> PARSER =
        new com.google.protobuf.AbstractParser<AllFirstBloodRs>() {
      public AllFirstBloodRs parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AllFirstBloodRs(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AllFirstBloodRs> getParserForType() {
      return PARSER;
    }

    // repeated .FirstBloodInfo allInfo = 1;
    public static final int ALLINFO_FIELD_NUMBER = 1;
    private java.util.List<com.game.pb.CommonPb.FirstBloodInfo> allInfo_;
    /**
     * <code>repeated .FirstBloodInfo allInfo = 1;</code>
     *
     * <pre>
     * 首杀人的信息
     * </pre>
     */
    public java.util.List<com.game.pb.CommonPb.FirstBloodInfo> getAllInfoList() {
      return allInfo_;
    }
    /**
     * <code>repeated .FirstBloodInfo allInfo = 1;</code>
     *
     * <pre>
     * 首杀人的信息
     * </pre>
     */
    public java.util.List<? extends com.game.pb.CommonPb.FirstBloodInfoOrBuilder> 
        getAllInfoOrBuilderList() {
      return allInfo_;
    }
    /**
     * <code>repeated .FirstBloodInfo allInfo = 1;</code>
     *
     * <pre>
     * 首杀人的信息
     * </pre>
     */
    public int getAllInfoCount() {
      return allInfo_.size();
    }
    /**
     * <code>repeated .FirstBloodInfo allInfo = 1;</code>
     *
     * <pre>
     * 首杀人的信息
     * </pre>
     */
    public com.game.pb.CommonPb.FirstBloodInfo getAllInfo(int index) {
      return allInfo_.get(index);
    }
    /**
     * <code>repeated .FirstBloodInfo allInfo = 1;</code>
     *
     * <pre>
     * 首杀人的信息
     * </pre>
     */
    public com.game.pb.CommonPb.FirstBloodInfoOrBuilder getAllInfoOrBuilder(
        int index) {
      return allInfo_.get(index);
    }

    private void initFields() {
      allInfo_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < allInfo_.size(); i++) {
        output.writeMessage(1, allInfo_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < allInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, allInfo_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.game.pb.FirstBloodPb.AllFirstBloodRs parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.pb.FirstBloodPb.AllFirstBloodRs parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.pb.FirstBloodPb.AllFirstBloodRs parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.pb.FirstBloodPb.AllFirstBloodRs parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.pb.FirstBloodPb.AllFirstBloodRs parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.pb.FirstBloodPb.AllFirstBloodRs parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.game.pb.FirstBloodPb.AllFirstBloodRs parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.game.pb.FirstBloodPb.AllFirstBloodRs parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.game.pb.FirstBloodPb.AllFirstBloodRs parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.pb.FirstBloodPb.AllFirstBloodRs parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.pb.FirstBloodPb.AllFirstBloodRs prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AllFirstBloodRs}
     *
     * <pre>
     * 首杀总览信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game.pb.FirstBloodPb.AllFirstBloodRsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.pb.FirstBloodPb.internal_static_AllFirstBloodRs_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.pb.FirstBloodPb.internal_static_AllFirstBloodRs_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.pb.FirstBloodPb.AllFirstBloodRs.class, com.game.pb.FirstBloodPb.AllFirstBloodRs.Builder.class);
      }

      // Construct using com.game.pb.FirstBloodPb.AllFirstBloodRs.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAllInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (allInfoBuilder_ == null) {
          allInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          allInfoBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.pb.FirstBloodPb.internal_static_AllFirstBloodRs_descriptor;
      }

      public com.game.pb.FirstBloodPb.AllFirstBloodRs getDefaultInstanceForType() {
        return com.game.pb.FirstBloodPb.AllFirstBloodRs.getDefaultInstance();
      }

      public com.game.pb.FirstBloodPb.AllFirstBloodRs build() {
        com.game.pb.FirstBloodPb.AllFirstBloodRs result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.pb.FirstBloodPb.AllFirstBloodRs buildPartial() {
        com.game.pb.FirstBloodPb.AllFirstBloodRs result = new com.game.pb.FirstBloodPb.AllFirstBloodRs(this);
        int from_bitField0_ = bitField0_;
        if (allInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            allInfo_ = java.util.Collections.unmodifiableList(allInfo_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.allInfo_ = allInfo_;
        } else {
          result.allInfo_ = allInfoBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.pb.FirstBloodPb.AllFirstBloodRs) {
          return mergeFrom((com.game.pb.FirstBloodPb.AllFirstBloodRs)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.pb.FirstBloodPb.AllFirstBloodRs other) {
        if (other == com.game.pb.FirstBloodPb.AllFirstBloodRs.getDefaultInstance()) return this;
        if (allInfoBuilder_ == null) {
          if (!other.allInfo_.isEmpty()) {
            if (allInfo_.isEmpty()) {
              allInfo_ = other.allInfo_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAllInfoIsMutable();
              allInfo_.addAll(other.allInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.allInfo_.isEmpty()) {
            if (allInfoBuilder_.isEmpty()) {
              allInfoBuilder_.dispose();
              allInfoBuilder_ = null;
              allInfo_ = other.allInfo_;
              bitField0_ = (bitField0_ & ~0x00000001);
              allInfoBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAllInfoFieldBuilder() : null;
            } else {
              allInfoBuilder_.addAllMessages(other.allInfo_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.pb.FirstBloodPb.AllFirstBloodRs parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.pb.FirstBloodPb.AllFirstBloodRs) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .FirstBloodInfo allInfo = 1;
      private java.util.List<com.game.pb.CommonPb.FirstBloodInfo> allInfo_ =
        java.util.Collections.emptyList();
      private void ensureAllInfoIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          allInfo_ = new java.util.ArrayList<com.game.pb.CommonPb.FirstBloodInfo>(allInfo_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.game.pb.CommonPb.FirstBloodInfo, com.game.pb.CommonPb.FirstBloodInfo.Builder, com.game.pb.CommonPb.FirstBloodInfoOrBuilder> allInfoBuilder_;

      /**
       * <code>repeated .FirstBloodInfo allInfo = 1;</code>
       *
       * <pre>
       * 首杀人的信息
       * </pre>
       */
      public java.util.List<com.game.pb.CommonPb.FirstBloodInfo> getAllInfoList() {
        if (allInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(allInfo_);
        } else {
          return allInfoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .FirstBloodInfo allInfo = 1;</code>
       *
       * <pre>
       * 首杀人的信息
       * </pre>
       */
      public int getAllInfoCount() {
        if (allInfoBuilder_ == null) {
          return allInfo_.size();
        } else {
          return allInfoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .FirstBloodInfo allInfo = 1;</code>
       *
       * <pre>
       * 首杀人的信息
       * </pre>
       */
      public com.game.pb.CommonPb.FirstBloodInfo getAllInfo(int index) {
        if (allInfoBuilder_ == null) {
          return allInfo_.get(index);
        } else {
          return allInfoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .FirstBloodInfo allInfo = 1;</code>
       *
       * <pre>
       * 首杀人的信息
       * </pre>
       */
      public Builder setAllInfo(
          int index, com.game.pb.CommonPb.FirstBloodInfo value) {
        if (allInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllInfoIsMutable();
          allInfo_.set(index, value);
          onChanged();
        } else {
          allInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .FirstBloodInfo allInfo = 1;</code>
       *
       * <pre>
       * 首杀人的信息
       * </pre>
       */
      public Builder setAllInfo(
          int index, com.game.pb.CommonPb.FirstBloodInfo.Builder builderForValue) {
        if (allInfoBuilder_ == null) {
          ensureAllInfoIsMutable();
          allInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          allInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .FirstBloodInfo allInfo = 1;</code>
       *
       * <pre>
       * 首杀人的信息
       * </pre>
       */
      public Builder addAllInfo(com.game.pb.CommonPb.FirstBloodInfo value) {
        if (allInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllInfoIsMutable();
          allInfo_.add(value);
          onChanged();
        } else {
          allInfoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .FirstBloodInfo allInfo = 1;</code>
       *
       * <pre>
       * 首杀人的信息
       * </pre>
       */
      public Builder addAllInfo(
          int index, com.game.pb.CommonPb.FirstBloodInfo value) {
        if (allInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllInfoIsMutable();
          allInfo_.add(index, value);
          onChanged();
        } else {
          allInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .FirstBloodInfo allInfo = 1;</code>
       *
       * <pre>
       * 首杀人的信息
       * </pre>
       */
      public Builder addAllInfo(
          com.game.pb.CommonPb.FirstBloodInfo.Builder builderForValue) {
        if (allInfoBuilder_ == null) {
          ensureAllInfoIsMutable();
          allInfo_.add(builderForValue.build());
          onChanged();
        } else {
          allInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .FirstBloodInfo allInfo = 1;</code>
       *
       * <pre>
       * 首杀人的信息
       * </pre>
       */
      public Builder addAllInfo(
          int index, com.game.pb.CommonPb.FirstBloodInfo.Builder builderForValue) {
        if (allInfoBuilder_ == null) {
          ensureAllInfoIsMutable();
          allInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          allInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .FirstBloodInfo allInfo = 1;</code>
       *
       * <pre>
       * 首杀人的信息
       * </pre>
       */
      public Builder addAllAllInfo(
          java.lang.Iterable<? extends com.game.pb.CommonPb.FirstBloodInfo> values) {
        if (allInfoBuilder_ == null) {
          ensureAllInfoIsMutable();
          super.addAll(values, allInfo_);
          onChanged();
        } else {
          allInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .FirstBloodInfo allInfo = 1;</code>
       *
       * <pre>
       * 首杀人的信息
       * </pre>
       */
      public Builder clearAllInfo() {
        if (allInfoBuilder_ == null) {
          allInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          allInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .FirstBloodInfo allInfo = 1;</code>
       *
       * <pre>
       * 首杀人的信息
       * </pre>
       */
      public Builder removeAllInfo(int index) {
        if (allInfoBuilder_ == null) {
          ensureAllInfoIsMutable();
          allInfo_.remove(index);
          onChanged();
        } else {
          allInfoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .FirstBloodInfo allInfo = 1;</code>
       *
       * <pre>
       * 首杀人的信息
       * </pre>
       */
      public com.game.pb.CommonPb.FirstBloodInfo.Builder getAllInfoBuilder(
          int index) {
        return getAllInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .FirstBloodInfo allInfo = 1;</code>
       *
       * <pre>
       * 首杀人的信息
       * </pre>
       */
      public com.game.pb.CommonPb.FirstBloodInfoOrBuilder getAllInfoOrBuilder(
          int index) {
        if (allInfoBuilder_ == null) {
          return allInfo_.get(index);  } else {
          return allInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .FirstBloodInfo allInfo = 1;</code>
       *
       * <pre>
       * 首杀人的信息
       * </pre>
       */
      public java.util.List<? extends com.game.pb.CommonPb.FirstBloodInfoOrBuilder> 
           getAllInfoOrBuilderList() {
        if (allInfoBuilder_ != null) {
          return allInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(allInfo_);
        }
      }
      /**
       * <code>repeated .FirstBloodInfo allInfo = 1;</code>
       *
       * <pre>
       * 首杀人的信息
       * </pre>
       */
      public com.game.pb.CommonPb.FirstBloodInfo.Builder addAllInfoBuilder() {
        return getAllInfoFieldBuilder().addBuilder(
            com.game.pb.CommonPb.FirstBloodInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .FirstBloodInfo allInfo = 1;</code>
       *
       * <pre>
       * 首杀人的信息
       * </pre>
       */
      public com.game.pb.CommonPb.FirstBloodInfo.Builder addAllInfoBuilder(
          int index) {
        return getAllInfoFieldBuilder().addBuilder(
            index, com.game.pb.CommonPb.FirstBloodInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .FirstBloodInfo allInfo = 1;</code>
       *
       * <pre>
       * 首杀人的信息
       * </pre>
       */
      public java.util.List<com.game.pb.CommonPb.FirstBloodInfo.Builder> 
           getAllInfoBuilderList() {
        return getAllInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.game.pb.CommonPb.FirstBloodInfo, com.game.pb.CommonPb.FirstBloodInfo.Builder, com.game.pb.CommonPb.FirstBloodInfoOrBuilder> 
          getAllInfoFieldBuilder() {
        if (allInfoBuilder_ == null) {
          allInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.game.pb.CommonPb.FirstBloodInfo, com.game.pb.CommonPb.FirstBloodInfo.Builder, com.game.pb.CommonPb.FirstBloodInfoOrBuilder>(
                  allInfo_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          allInfo_ = null;
        }
        return allInfoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:AllFirstBloodRs)
    }

    static {
      defaultInstance = new AllFirstBloodRs(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:AllFirstBloodRs)
    public static final int EXT_FIELD_NUMBER = 60304;
    /**
     * <code>extend .Base { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.game.pb.BasePb.Base,
        com.game.pb.FirstBloodPb.AllFirstBloodRs> ext = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.game.pb.FirstBloodPb.AllFirstBloodRs.getDefaultInstance(),
          0,
          com.game.pb.FirstBloodPb.AllFirstBloodRs.class,
          com.game.pb.FirstBloodPb.AllFirstBloodRs.getDefaultInstance());
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CityFirstBloodRq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CityFirstBloodRq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CityFirstBloodRs_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CityFirstBloodRs_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_AllFirstBloodRq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AllFirstBloodRq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_AllFirstBloodRs_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AllFirstBloodRs_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020FirstBlood.proto\032\nBase.proto\032\014Common.p" +
      "roto\"j\n\020CityFirstBloodRq\022\r\n\005mapId\030\001 \001(\005\022" +
      "\014\n\004page\030\002 \001(\005\022\020\n\010cityType\030\003 \001(\0052\'\n\003ext\022\005" +
      ".Base\030\215\327\003 \001(\0132\021.CityFirstBloodRq\"`\n\020City" +
      "FirstBloodRs\022#\n\007mapInfo\030\001 \001(\0132\022.FirstBlo" +
      "odMapInfo2\'\n\003ext\022\005.Base\030\216\327\003 \001(\0132\021.CityFi" +
      "rstBloodRs\"9\n\017AllFirstBloodRq2&\n\003ext\022\005.B" +
      "ase\030\217\327\003 \001(\0132\020.AllFirstBloodRq\"[\n\017AllFirs" +
      "tBloodRs\022 \n\007allInfo\030\001 \003(\0132\017.FirstBloodIn" +
      "fo2&\n\003ext\022\005.Base\030\220\327\003 \001(\0132\020.AllFirstBlood",
      "RsB\033\n\013com.game.pbB\014FirstBloodPb"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_CityFirstBloodRq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_CityFirstBloodRq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CityFirstBloodRq_descriptor,
              new java.lang.String[] { "MapId", "Page", "CityType", });
          internal_static_CityFirstBloodRs_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_CityFirstBloodRs_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CityFirstBloodRs_descriptor,
              new java.lang.String[] { "MapInfo", });
          internal_static_AllFirstBloodRq_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_AllFirstBloodRq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_AllFirstBloodRq_descriptor,
              new java.lang.String[] { });
          internal_static_AllFirstBloodRs_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_AllFirstBloodRs_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_AllFirstBloodRs_descriptor,
              new java.lang.String[] { "AllInfo", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.game.pb.BasePb.getDescriptor(),
          com.game.pb.CommonPb.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
