// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Setting.proto

package com.game.pb;

public final class SettingPb {
  private SettingPb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.game.pb.SettingPb.GetSettingInfoRq.ext);
    registry.add(com.game.pb.SettingPb.GetSettingInfoRs.ext);
    registry.add(com.game.pb.SettingPb.SetSettingRq.ext);
    registry.add(com.game.pb.SettingPb.SetSettingRs.ext);
  }
  public interface GetSettingInfoRqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code GetSettingInfoRq}
   *
   * <pre>
   *获取设置信息请求
   * </pre>
   */
  public static final class GetSettingInfoRq extends
      com.google.protobuf.GeneratedMessage
      implements GetSettingInfoRqOrBuilder {
    // Use GetSettingInfoRq.newBuilder() to construct.
    private GetSettingInfoRq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GetSettingInfoRq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GetSettingInfoRq defaultInstance;
    public static GetSettingInfoRq getDefaultInstance() {
      return defaultInstance;
    }

    public GetSettingInfoRq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GetSettingInfoRq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.pb.SettingPb.internal_static_GetSettingInfoRq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.pb.SettingPb.internal_static_GetSettingInfoRq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.pb.SettingPb.GetSettingInfoRq.class, com.game.pb.SettingPb.GetSettingInfoRq.Builder.class);
    }

    public static com.google.protobuf.Parser<GetSettingInfoRq> PARSER =
        new com.google.protobuf.AbstractParser<GetSettingInfoRq>() {
      public GetSettingInfoRq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetSettingInfoRq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GetSettingInfoRq> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.game.pb.SettingPb.GetSettingInfoRq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.pb.SettingPb.GetSettingInfoRq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.pb.SettingPb.GetSettingInfoRq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.pb.SettingPb.GetSettingInfoRq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.pb.SettingPb.GetSettingInfoRq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.pb.SettingPb.GetSettingInfoRq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.game.pb.SettingPb.GetSettingInfoRq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.game.pb.SettingPb.GetSettingInfoRq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.game.pb.SettingPb.GetSettingInfoRq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.pb.SettingPb.GetSettingInfoRq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.pb.SettingPb.GetSettingInfoRq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetSettingInfoRq}
     *
     * <pre>
     *获取设置信息请求
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game.pb.SettingPb.GetSettingInfoRqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.pb.SettingPb.internal_static_GetSettingInfoRq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.pb.SettingPb.internal_static_GetSettingInfoRq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.pb.SettingPb.GetSettingInfoRq.class, com.game.pb.SettingPb.GetSettingInfoRq.Builder.class);
      }

      // Construct using com.game.pb.SettingPb.GetSettingInfoRq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.pb.SettingPb.internal_static_GetSettingInfoRq_descriptor;
      }

      public com.game.pb.SettingPb.GetSettingInfoRq getDefaultInstanceForType() {
        return com.game.pb.SettingPb.GetSettingInfoRq.getDefaultInstance();
      }

      public com.game.pb.SettingPb.GetSettingInfoRq build() {
        com.game.pb.SettingPb.GetSettingInfoRq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.pb.SettingPb.GetSettingInfoRq buildPartial() {
        com.game.pb.SettingPb.GetSettingInfoRq result = new com.game.pb.SettingPb.GetSettingInfoRq(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.pb.SettingPb.GetSettingInfoRq) {
          return mergeFrom((com.game.pb.SettingPb.GetSettingInfoRq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.pb.SettingPb.GetSettingInfoRq other) {
        if (other == com.game.pb.SettingPb.GetSettingInfoRq.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.pb.SettingPb.GetSettingInfoRq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.pb.SettingPb.GetSettingInfoRq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:GetSettingInfoRq)
    }

    static {
      defaultInstance = new GetSettingInfoRq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:GetSettingInfoRq)
    public static final int EXT_FIELD_NUMBER = 31001;
    /**
     * <code>extend .Base { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.game.pb.BasePb.Base,
        com.game.pb.SettingPb.GetSettingInfoRq> ext = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.game.pb.SettingPb.GetSettingInfoRq.getDefaultInstance(),
          0,
          com.game.pb.SettingPb.GetSettingInfoRq.class,
          com.game.pb.SettingPb.GetSettingInfoRq.getDefaultInstance());
  }

  public interface GetSettingInfoRsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .SettingInfo info = 1;
    /**
     * <code>optional .SettingInfo info = 1;</code>
     *
     * <pre>
     *设置信息
     * </pre>
     */
    boolean hasInfo();
    /**
     * <code>optional .SettingInfo info = 1;</code>
     *
     * <pre>
     *设置信息
     * </pre>
     */
    com.game.pb.CommonPb.SettingInfo getInfo();
    /**
     * <code>optional .SettingInfo info = 1;</code>
     *
     * <pre>
     *设置信息
     * </pre>
     */
    com.game.pb.CommonPb.SettingInfoOrBuilder getInfoOrBuilder();
  }
  /**
   * Protobuf type {@code GetSettingInfoRs}
   *
   * <pre>
   *获取设置信息响应
   * </pre>
   */
  public static final class GetSettingInfoRs extends
      com.google.protobuf.GeneratedMessage
      implements GetSettingInfoRsOrBuilder {
    // Use GetSettingInfoRs.newBuilder() to construct.
    private GetSettingInfoRs(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GetSettingInfoRs(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GetSettingInfoRs defaultInstance;
    public static GetSettingInfoRs getDefaultInstance() {
      return defaultInstance;
    }

    public GetSettingInfoRs getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GetSettingInfoRs(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.game.pb.CommonPb.SettingInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = info_.toBuilder();
              }
              info_ = input.readMessage(com.game.pb.CommonPb.SettingInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(info_);
                info_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.pb.SettingPb.internal_static_GetSettingInfoRs_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.pb.SettingPb.internal_static_GetSettingInfoRs_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.pb.SettingPb.GetSettingInfoRs.class, com.game.pb.SettingPb.GetSettingInfoRs.Builder.class);
    }

    public static com.google.protobuf.Parser<GetSettingInfoRs> PARSER =
        new com.google.protobuf.AbstractParser<GetSettingInfoRs>() {
      public GetSettingInfoRs parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetSettingInfoRs(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GetSettingInfoRs> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .SettingInfo info = 1;
    public static final int INFO_FIELD_NUMBER = 1;
    private com.game.pb.CommonPb.SettingInfo info_;
    /**
     * <code>optional .SettingInfo info = 1;</code>
     *
     * <pre>
     *设置信息
     * </pre>
     */
    public boolean hasInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .SettingInfo info = 1;</code>
     *
     * <pre>
     *设置信息
     * </pre>
     */
    public com.game.pb.CommonPb.SettingInfo getInfo() {
      return info_;
    }
    /**
     * <code>optional .SettingInfo info = 1;</code>
     *
     * <pre>
     *设置信息
     * </pre>
     */
    public com.game.pb.CommonPb.SettingInfoOrBuilder getInfoOrBuilder() {
      return info_;
    }

    private void initFields() {
      info_ = com.game.pb.CommonPb.SettingInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, info_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, info_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.game.pb.SettingPb.GetSettingInfoRs parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.pb.SettingPb.GetSettingInfoRs parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.pb.SettingPb.GetSettingInfoRs parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.pb.SettingPb.GetSettingInfoRs parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.pb.SettingPb.GetSettingInfoRs parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.pb.SettingPb.GetSettingInfoRs parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.game.pb.SettingPb.GetSettingInfoRs parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.game.pb.SettingPb.GetSettingInfoRs parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.game.pb.SettingPb.GetSettingInfoRs parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.pb.SettingPb.GetSettingInfoRs parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.pb.SettingPb.GetSettingInfoRs prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetSettingInfoRs}
     *
     * <pre>
     *获取设置信息响应
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game.pb.SettingPb.GetSettingInfoRsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.pb.SettingPb.internal_static_GetSettingInfoRs_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.pb.SettingPb.internal_static_GetSettingInfoRs_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.pb.SettingPb.GetSettingInfoRs.class, com.game.pb.SettingPb.GetSettingInfoRs.Builder.class);
      }

      // Construct using com.game.pb.SettingPb.GetSettingInfoRs.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (infoBuilder_ == null) {
          info_ = com.game.pb.CommonPb.SettingInfo.getDefaultInstance();
        } else {
          infoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.pb.SettingPb.internal_static_GetSettingInfoRs_descriptor;
      }

      public com.game.pb.SettingPb.GetSettingInfoRs getDefaultInstanceForType() {
        return com.game.pb.SettingPb.GetSettingInfoRs.getDefaultInstance();
      }

      public com.game.pb.SettingPb.GetSettingInfoRs build() {
        com.game.pb.SettingPb.GetSettingInfoRs result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.pb.SettingPb.GetSettingInfoRs buildPartial() {
        com.game.pb.SettingPb.GetSettingInfoRs result = new com.game.pb.SettingPb.GetSettingInfoRs(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (infoBuilder_ == null) {
          result.info_ = info_;
        } else {
          result.info_ = infoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.pb.SettingPb.GetSettingInfoRs) {
          return mergeFrom((com.game.pb.SettingPb.GetSettingInfoRs)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.pb.SettingPb.GetSettingInfoRs other) {
        if (other == com.game.pb.SettingPb.GetSettingInfoRs.getDefaultInstance()) return this;
        if (other.hasInfo()) {
          mergeInfo(other.getInfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.pb.SettingPb.GetSettingInfoRs parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.pb.SettingPb.GetSettingInfoRs) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .SettingInfo info = 1;
      private com.game.pb.CommonPb.SettingInfo info_ = com.game.pb.CommonPb.SettingInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.game.pb.CommonPb.SettingInfo, com.game.pb.CommonPb.SettingInfo.Builder, com.game.pb.CommonPb.SettingInfoOrBuilder> infoBuilder_;
      /**
       * <code>optional .SettingInfo info = 1;</code>
       *
       * <pre>
       *设置信息
       * </pre>
       */
      public boolean hasInfo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .SettingInfo info = 1;</code>
       *
       * <pre>
       *设置信息
       * </pre>
       */
      public com.game.pb.CommonPb.SettingInfo getInfo() {
        if (infoBuilder_ == null) {
          return info_;
        } else {
          return infoBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .SettingInfo info = 1;</code>
       *
       * <pre>
       *设置信息
       * </pre>
       */
      public Builder setInfo(com.game.pb.CommonPb.SettingInfo value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          info_ = value;
          onChanged();
        } else {
          infoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .SettingInfo info = 1;</code>
       *
       * <pre>
       *设置信息
       * </pre>
       */
      public Builder setInfo(
          com.game.pb.CommonPb.SettingInfo.Builder builderForValue) {
        if (infoBuilder_ == null) {
          info_ = builderForValue.build();
          onChanged();
        } else {
          infoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .SettingInfo info = 1;</code>
       *
       * <pre>
       *设置信息
       * </pre>
       */
      public Builder mergeInfo(com.game.pb.CommonPb.SettingInfo value) {
        if (infoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              info_ != com.game.pb.CommonPb.SettingInfo.getDefaultInstance()) {
            info_ =
              com.game.pb.CommonPb.SettingInfo.newBuilder(info_).mergeFrom(value).buildPartial();
          } else {
            info_ = value;
          }
          onChanged();
        } else {
          infoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .SettingInfo info = 1;</code>
       *
       * <pre>
       *设置信息
       * </pre>
       */
      public Builder clearInfo() {
        if (infoBuilder_ == null) {
          info_ = com.game.pb.CommonPb.SettingInfo.getDefaultInstance();
          onChanged();
        } else {
          infoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .SettingInfo info = 1;</code>
       *
       * <pre>
       *设置信息
       * </pre>
       */
      public com.game.pb.CommonPb.SettingInfo.Builder getInfoBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .SettingInfo info = 1;</code>
       *
       * <pre>
       *设置信息
       * </pre>
       */
      public com.game.pb.CommonPb.SettingInfoOrBuilder getInfoOrBuilder() {
        if (infoBuilder_ != null) {
          return infoBuilder_.getMessageOrBuilder();
        } else {
          return info_;
        }
      }
      /**
       * <code>optional .SettingInfo info = 1;</code>
       *
       * <pre>
       *设置信息
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.game.pb.CommonPb.SettingInfo, com.game.pb.CommonPb.SettingInfo.Builder, com.game.pb.CommonPb.SettingInfoOrBuilder> 
          getInfoFieldBuilder() {
        if (infoBuilder_ == null) {
          infoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.game.pb.CommonPb.SettingInfo, com.game.pb.CommonPb.SettingInfo.Builder, com.game.pb.CommonPb.SettingInfoOrBuilder>(
                  info_,
                  getParentForChildren(),
                  isClean());
          info_ = null;
        }
        return infoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:GetSettingInfoRs)
    }

    static {
      defaultInstance = new GetSettingInfoRs(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:GetSettingInfoRs)
    public static final int EXT_FIELD_NUMBER = 31002;
    /**
     * <code>extend .Base { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.game.pb.BasePb.Base,
        com.game.pb.SettingPb.GetSettingInfoRs> ext = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.game.pb.SettingPb.GetSettingInfoRs.getDefaultInstance(),
          0,
          com.game.pb.SettingPb.GetSettingInfoRs.class,
          com.game.pb.SettingPb.GetSettingInfoRs.getDefaultInstance());
  }

  public interface SetSettingRqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .SettingInfo info = 1;
    /**
     * <code>optional .SettingInfo info = 1;</code>
     *
     * <pre>
     *设置信息
     * </pre>
     */
    boolean hasInfo();
    /**
     * <code>optional .SettingInfo info = 1;</code>
     *
     * <pre>
     *设置信息
     * </pre>
     */
    com.game.pb.CommonPb.SettingInfo getInfo();
    /**
     * <code>optional .SettingInfo info = 1;</code>
     *
     * <pre>
     *设置信息
     * </pre>
     */
    com.game.pb.CommonPb.SettingInfoOrBuilder getInfoOrBuilder();
  }
  /**
   * Protobuf type {@code SetSettingRq}
   *
   * <pre>
   *进行设置状态设置请求
   * </pre>
   */
  public static final class SetSettingRq extends
      com.google.protobuf.GeneratedMessage
      implements SetSettingRqOrBuilder {
    // Use SetSettingRq.newBuilder() to construct.
    private SetSettingRq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SetSettingRq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SetSettingRq defaultInstance;
    public static SetSettingRq getDefaultInstance() {
      return defaultInstance;
    }

    public SetSettingRq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SetSettingRq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.game.pb.CommonPb.SettingInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = info_.toBuilder();
              }
              info_ = input.readMessage(com.game.pb.CommonPb.SettingInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(info_);
                info_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.pb.SettingPb.internal_static_SetSettingRq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.pb.SettingPb.internal_static_SetSettingRq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.pb.SettingPb.SetSettingRq.class, com.game.pb.SettingPb.SetSettingRq.Builder.class);
    }

    public static com.google.protobuf.Parser<SetSettingRq> PARSER =
        new com.google.protobuf.AbstractParser<SetSettingRq>() {
      public SetSettingRq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SetSettingRq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SetSettingRq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .SettingInfo info = 1;
    public static final int INFO_FIELD_NUMBER = 1;
    private com.game.pb.CommonPb.SettingInfo info_;
    /**
     * <code>optional .SettingInfo info = 1;</code>
     *
     * <pre>
     *设置信息
     * </pre>
     */
    public boolean hasInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .SettingInfo info = 1;</code>
     *
     * <pre>
     *设置信息
     * </pre>
     */
    public com.game.pb.CommonPb.SettingInfo getInfo() {
      return info_;
    }
    /**
     * <code>optional .SettingInfo info = 1;</code>
     *
     * <pre>
     *设置信息
     * </pre>
     */
    public com.game.pb.CommonPb.SettingInfoOrBuilder getInfoOrBuilder() {
      return info_;
    }

    private void initFields() {
      info_ = com.game.pb.CommonPb.SettingInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, info_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, info_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.game.pb.SettingPb.SetSettingRq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.pb.SettingPb.SetSettingRq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.pb.SettingPb.SetSettingRq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.pb.SettingPb.SetSettingRq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.pb.SettingPb.SetSettingRq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.pb.SettingPb.SetSettingRq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.game.pb.SettingPb.SetSettingRq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.game.pb.SettingPb.SetSettingRq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.game.pb.SettingPb.SetSettingRq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.pb.SettingPb.SetSettingRq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.pb.SettingPb.SetSettingRq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SetSettingRq}
     *
     * <pre>
     *进行设置状态设置请求
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game.pb.SettingPb.SetSettingRqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.pb.SettingPb.internal_static_SetSettingRq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.pb.SettingPb.internal_static_SetSettingRq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.pb.SettingPb.SetSettingRq.class, com.game.pb.SettingPb.SetSettingRq.Builder.class);
      }

      // Construct using com.game.pb.SettingPb.SetSettingRq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (infoBuilder_ == null) {
          info_ = com.game.pb.CommonPb.SettingInfo.getDefaultInstance();
        } else {
          infoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.pb.SettingPb.internal_static_SetSettingRq_descriptor;
      }

      public com.game.pb.SettingPb.SetSettingRq getDefaultInstanceForType() {
        return com.game.pb.SettingPb.SetSettingRq.getDefaultInstance();
      }

      public com.game.pb.SettingPb.SetSettingRq build() {
        com.game.pb.SettingPb.SetSettingRq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.pb.SettingPb.SetSettingRq buildPartial() {
        com.game.pb.SettingPb.SetSettingRq result = new com.game.pb.SettingPb.SetSettingRq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (infoBuilder_ == null) {
          result.info_ = info_;
        } else {
          result.info_ = infoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.pb.SettingPb.SetSettingRq) {
          return mergeFrom((com.game.pb.SettingPb.SetSettingRq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.pb.SettingPb.SetSettingRq other) {
        if (other == com.game.pb.SettingPb.SetSettingRq.getDefaultInstance()) return this;
        if (other.hasInfo()) {
          mergeInfo(other.getInfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.pb.SettingPb.SetSettingRq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.pb.SettingPb.SetSettingRq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .SettingInfo info = 1;
      private com.game.pb.CommonPb.SettingInfo info_ = com.game.pb.CommonPb.SettingInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.game.pb.CommonPb.SettingInfo, com.game.pb.CommonPb.SettingInfo.Builder, com.game.pb.CommonPb.SettingInfoOrBuilder> infoBuilder_;
      /**
       * <code>optional .SettingInfo info = 1;</code>
       *
       * <pre>
       *设置信息
       * </pre>
       */
      public boolean hasInfo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .SettingInfo info = 1;</code>
       *
       * <pre>
       *设置信息
       * </pre>
       */
      public com.game.pb.CommonPb.SettingInfo getInfo() {
        if (infoBuilder_ == null) {
          return info_;
        } else {
          return infoBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .SettingInfo info = 1;</code>
       *
       * <pre>
       *设置信息
       * </pre>
       */
      public Builder setInfo(com.game.pb.CommonPb.SettingInfo value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          info_ = value;
          onChanged();
        } else {
          infoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .SettingInfo info = 1;</code>
       *
       * <pre>
       *设置信息
       * </pre>
       */
      public Builder setInfo(
          com.game.pb.CommonPb.SettingInfo.Builder builderForValue) {
        if (infoBuilder_ == null) {
          info_ = builderForValue.build();
          onChanged();
        } else {
          infoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .SettingInfo info = 1;</code>
       *
       * <pre>
       *设置信息
       * </pre>
       */
      public Builder mergeInfo(com.game.pb.CommonPb.SettingInfo value) {
        if (infoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              info_ != com.game.pb.CommonPb.SettingInfo.getDefaultInstance()) {
            info_ =
              com.game.pb.CommonPb.SettingInfo.newBuilder(info_).mergeFrom(value).buildPartial();
          } else {
            info_ = value;
          }
          onChanged();
        } else {
          infoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .SettingInfo info = 1;</code>
       *
       * <pre>
       *设置信息
       * </pre>
       */
      public Builder clearInfo() {
        if (infoBuilder_ == null) {
          info_ = com.game.pb.CommonPb.SettingInfo.getDefaultInstance();
          onChanged();
        } else {
          infoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .SettingInfo info = 1;</code>
       *
       * <pre>
       *设置信息
       * </pre>
       */
      public com.game.pb.CommonPb.SettingInfo.Builder getInfoBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .SettingInfo info = 1;</code>
       *
       * <pre>
       *设置信息
       * </pre>
       */
      public com.game.pb.CommonPb.SettingInfoOrBuilder getInfoOrBuilder() {
        if (infoBuilder_ != null) {
          return infoBuilder_.getMessageOrBuilder();
        } else {
          return info_;
        }
      }
      /**
       * <code>optional .SettingInfo info = 1;</code>
       *
       * <pre>
       *设置信息
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.game.pb.CommonPb.SettingInfo, com.game.pb.CommonPb.SettingInfo.Builder, com.game.pb.CommonPb.SettingInfoOrBuilder> 
          getInfoFieldBuilder() {
        if (infoBuilder_ == null) {
          infoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.game.pb.CommonPb.SettingInfo, com.game.pb.CommonPb.SettingInfo.Builder, com.game.pb.CommonPb.SettingInfoOrBuilder>(
                  info_,
                  getParentForChildren(),
                  isClean());
          info_ = null;
        }
        return infoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:SetSettingRq)
    }

    static {
      defaultInstance = new SetSettingRq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SetSettingRq)
    public static final int EXT_FIELD_NUMBER = 31003;
    /**
     * <code>extend .Base { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.game.pb.BasePb.Base,
        com.game.pb.SettingPb.SetSettingRq> ext = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.game.pb.SettingPb.SetSettingRq.getDefaultInstance(),
          0,
          com.game.pb.SettingPb.SetSettingRq.class,
          com.game.pb.SettingPb.SetSettingRq.getDefaultInstance());
  }

  public interface SetSettingRsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .SettingInfo info = 1;
    /**
     * <code>optional .SettingInfo info = 1;</code>
     *
     * <pre>
     *设置信息
     * </pre>
     */
    boolean hasInfo();
    /**
     * <code>optional .SettingInfo info = 1;</code>
     *
     * <pre>
     *设置信息
     * </pre>
     */
    com.game.pb.CommonPb.SettingInfo getInfo();
    /**
     * <code>optional .SettingInfo info = 1;</code>
     *
     * <pre>
     *设置信息
     * </pre>
     */
    com.game.pb.CommonPb.SettingInfoOrBuilder getInfoOrBuilder();
  }
  /**
   * Protobuf type {@code SetSettingRs}
   *
   * <pre>
   *进行设置状态设置响应(服务器保存)
   * </pre>
   */
  public static final class SetSettingRs extends
      com.google.protobuf.GeneratedMessage
      implements SetSettingRsOrBuilder {
    // Use SetSettingRs.newBuilder() to construct.
    private SetSettingRs(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SetSettingRs(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SetSettingRs defaultInstance;
    public static SetSettingRs getDefaultInstance() {
      return defaultInstance;
    }

    public SetSettingRs getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SetSettingRs(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.game.pb.CommonPb.SettingInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = info_.toBuilder();
              }
              info_ = input.readMessage(com.game.pb.CommonPb.SettingInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(info_);
                info_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.pb.SettingPb.internal_static_SetSettingRs_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.pb.SettingPb.internal_static_SetSettingRs_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.pb.SettingPb.SetSettingRs.class, com.game.pb.SettingPb.SetSettingRs.Builder.class);
    }

    public static com.google.protobuf.Parser<SetSettingRs> PARSER =
        new com.google.protobuf.AbstractParser<SetSettingRs>() {
      public SetSettingRs parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SetSettingRs(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SetSettingRs> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .SettingInfo info = 1;
    public static final int INFO_FIELD_NUMBER = 1;
    private com.game.pb.CommonPb.SettingInfo info_;
    /**
     * <code>optional .SettingInfo info = 1;</code>
     *
     * <pre>
     *设置信息
     * </pre>
     */
    public boolean hasInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .SettingInfo info = 1;</code>
     *
     * <pre>
     *设置信息
     * </pre>
     */
    public com.game.pb.CommonPb.SettingInfo getInfo() {
      return info_;
    }
    /**
     * <code>optional .SettingInfo info = 1;</code>
     *
     * <pre>
     *设置信息
     * </pre>
     */
    public com.game.pb.CommonPb.SettingInfoOrBuilder getInfoOrBuilder() {
      return info_;
    }

    private void initFields() {
      info_ = com.game.pb.CommonPb.SettingInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, info_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, info_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.game.pb.SettingPb.SetSettingRs parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.pb.SettingPb.SetSettingRs parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.pb.SettingPb.SetSettingRs parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.pb.SettingPb.SetSettingRs parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.pb.SettingPb.SetSettingRs parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.pb.SettingPb.SetSettingRs parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.game.pb.SettingPb.SetSettingRs parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.game.pb.SettingPb.SetSettingRs parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.game.pb.SettingPb.SetSettingRs parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.pb.SettingPb.SetSettingRs parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.pb.SettingPb.SetSettingRs prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SetSettingRs}
     *
     * <pre>
     *进行设置状态设置响应(服务器保存)
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game.pb.SettingPb.SetSettingRsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.pb.SettingPb.internal_static_SetSettingRs_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.pb.SettingPb.internal_static_SetSettingRs_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.pb.SettingPb.SetSettingRs.class, com.game.pb.SettingPb.SetSettingRs.Builder.class);
      }

      // Construct using com.game.pb.SettingPb.SetSettingRs.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (infoBuilder_ == null) {
          info_ = com.game.pb.CommonPb.SettingInfo.getDefaultInstance();
        } else {
          infoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.pb.SettingPb.internal_static_SetSettingRs_descriptor;
      }

      public com.game.pb.SettingPb.SetSettingRs getDefaultInstanceForType() {
        return com.game.pb.SettingPb.SetSettingRs.getDefaultInstance();
      }

      public com.game.pb.SettingPb.SetSettingRs build() {
        com.game.pb.SettingPb.SetSettingRs result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.pb.SettingPb.SetSettingRs buildPartial() {
        com.game.pb.SettingPb.SetSettingRs result = new com.game.pb.SettingPb.SetSettingRs(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (infoBuilder_ == null) {
          result.info_ = info_;
        } else {
          result.info_ = infoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.pb.SettingPb.SetSettingRs) {
          return mergeFrom((com.game.pb.SettingPb.SetSettingRs)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.pb.SettingPb.SetSettingRs other) {
        if (other == com.game.pb.SettingPb.SetSettingRs.getDefaultInstance()) return this;
        if (other.hasInfo()) {
          mergeInfo(other.getInfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.pb.SettingPb.SetSettingRs parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.pb.SettingPb.SetSettingRs) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .SettingInfo info = 1;
      private com.game.pb.CommonPb.SettingInfo info_ = com.game.pb.CommonPb.SettingInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.game.pb.CommonPb.SettingInfo, com.game.pb.CommonPb.SettingInfo.Builder, com.game.pb.CommonPb.SettingInfoOrBuilder> infoBuilder_;
      /**
       * <code>optional .SettingInfo info = 1;</code>
       *
       * <pre>
       *设置信息
       * </pre>
       */
      public boolean hasInfo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .SettingInfo info = 1;</code>
       *
       * <pre>
       *设置信息
       * </pre>
       */
      public com.game.pb.CommonPb.SettingInfo getInfo() {
        if (infoBuilder_ == null) {
          return info_;
        } else {
          return infoBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .SettingInfo info = 1;</code>
       *
       * <pre>
       *设置信息
       * </pre>
       */
      public Builder setInfo(com.game.pb.CommonPb.SettingInfo value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          info_ = value;
          onChanged();
        } else {
          infoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .SettingInfo info = 1;</code>
       *
       * <pre>
       *设置信息
       * </pre>
       */
      public Builder setInfo(
          com.game.pb.CommonPb.SettingInfo.Builder builderForValue) {
        if (infoBuilder_ == null) {
          info_ = builderForValue.build();
          onChanged();
        } else {
          infoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .SettingInfo info = 1;</code>
       *
       * <pre>
       *设置信息
       * </pre>
       */
      public Builder mergeInfo(com.game.pb.CommonPb.SettingInfo value) {
        if (infoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              info_ != com.game.pb.CommonPb.SettingInfo.getDefaultInstance()) {
            info_ =
              com.game.pb.CommonPb.SettingInfo.newBuilder(info_).mergeFrom(value).buildPartial();
          } else {
            info_ = value;
          }
          onChanged();
        } else {
          infoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .SettingInfo info = 1;</code>
       *
       * <pre>
       *设置信息
       * </pre>
       */
      public Builder clearInfo() {
        if (infoBuilder_ == null) {
          info_ = com.game.pb.CommonPb.SettingInfo.getDefaultInstance();
          onChanged();
        } else {
          infoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .SettingInfo info = 1;</code>
       *
       * <pre>
       *设置信息
       * </pre>
       */
      public com.game.pb.CommonPb.SettingInfo.Builder getInfoBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .SettingInfo info = 1;</code>
       *
       * <pre>
       *设置信息
       * </pre>
       */
      public com.game.pb.CommonPb.SettingInfoOrBuilder getInfoOrBuilder() {
        if (infoBuilder_ != null) {
          return infoBuilder_.getMessageOrBuilder();
        } else {
          return info_;
        }
      }
      /**
       * <code>optional .SettingInfo info = 1;</code>
       *
       * <pre>
       *设置信息
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.game.pb.CommonPb.SettingInfo, com.game.pb.CommonPb.SettingInfo.Builder, com.game.pb.CommonPb.SettingInfoOrBuilder> 
          getInfoFieldBuilder() {
        if (infoBuilder_ == null) {
          infoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.game.pb.CommonPb.SettingInfo, com.game.pb.CommonPb.SettingInfo.Builder, com.game.pb.CommonPb.SettingInfoOrBuilder>(
                  info_,
                  getParentForChildren(),
                  isClean());
          info_ = null;
        }
        return infoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:SetSettingRs)
    }

    static {
      defaultInstance = new SetSettingRs(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SetSettingRs)
    public static final int EXT_FIELD_NUMBER = 31004;
    /**
     * <code>extend .Base { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.game.pb.BasePb.Base,
        com.game.pb.SettingPb.SetSettingRs> ext = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.game.pb.SettingPb.SetSettingRs.getDefaultInstance(),
          0,
          com.game.pb.SettingPb.SetSettingRs.class,
          com.game.pb.SettingPb.SetSettingRs.getDefaultInstance());
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_GetSettingInfoRq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetSettingInfoRq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_GetSettingInfoRs_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetSettingInfoRs_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SetSettingRq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SetSettingRq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SetSettingRs_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SetSettingRs_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rSetting.proto\032\nBase.proto\032\014Common.prot" +
      "o\";\n\020GetSettingInfoRq2\'\n\003ext\022\005.Base\030\231\362\001 " +
      "\001(\0132\021.GetSettingInfoRq\"W\n\020GetSettingInfo" +
      "Rs\022\032\n\004info\030\001 \001(\0132\014.SettingInfo2\'\n\003ext\022\005." +
      "Base\030\232\362\001 \001(\0132\021.GetSettingInfoRs\"O\n\014SetSe" +
      "ttingRq\022\032\n\004info\030\001 \001(\0132\014.SettingInfo2#\n\003e" +
      "xt\022\005.Base\030\233\362\001 \001(\0132\r.SetSettingRq\"O\n\014SetS" +
      "ettingRs\022\032\n\004info\030\001 \001(\0132\014.SettingInfo2#\n\003" +
      "ext\022\005.Base\030\234\362\001 \001(\0132\r.SetSettingRsB\030\n\013com" +
      ".game.pbB\tSettingPb"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_GetSettingInfoRq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_GetSettingInfoRq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_GetSettingInfoRq_descriptor,
              new java.lang.String[] { });
          internal_static_GetSettingInfoRs_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_GetSettingInfoRs_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_GetSettingInfoRs_descriptor,
              new java.lang.String[] { "Info", });
          internal_static_SetSettingRq_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_SetSettingRq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SetSettingRq_descriptor,
              new java.lang.String[] { "Info", });
          internal_static_SetSettingRs_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_SetSettingRs_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SetSettingRs_descriptor,
              new java.lang.String[] { "Info", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.game.pb.BasePb.getDescriptor(),
          com.game.pb.CommonPb.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
